//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.235
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Drag_AND_Drop_between_Forms.Properties {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso con establecimiento inflexible de tipos, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o vuelva a generar su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Drag_AND_Drop_between_Forms.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso con establecimiento inflexible de tipos.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Bitmap _300px_NewtonIteration_Ani {
            get {
                object obj = ResourceManager.GetObject("300px-NewtonIteration_Ani", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _300px_NewtonIteration_Ani1 {
            get {
                object obj = ResourceManager.GetObject("300px-NewtonIteration_Ani1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Bomba {
            get {
                object obj = ResourceManager.GetObject("Bomba", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Bomba_Tipo_4 {
            get {
                object obj = ResourceManager.GetObject("Bomba Tipo 4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Broyden1 {
            get {
                object obj = ResourceManager.GetObject("Broyden1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Broyden2 {
            get {
                object obj = ResourceManager.GetObject("Broyden2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Broyden3 {
            get {
                object obj = ResourceManager.GetObject("Broyden3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Caldera_Tipo_6 {
            get {
                object obj = ResourceManager.GetObject("Caldera Tipo 6", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Calentador {
            get {
                object obj = ResourceManager.GetObject("Calentador", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Calentador_Tipo_7 {
            get {
                object obj = ResourceManager.GetObject("Calentador Tipo 7", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Calentador1 {
            get {
                object obj = ResourceManager.GetObject("Calentador1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Condensador {
            get {
                object obj = ResourceManager.GetObject("Condensador", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Condensador_Tipo_15 {
            get {
                object obj = ResourceManager.GetObject("Condensador Tipo 15", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Condensador_Tipo_8 {
            get {
                object obj = ResourceManager.GetObject("Condensador Tipo 8", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Condensador1 {
            get {
                object obj = ResourceManager.GetObject("Condensador1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Condicion_Contorno_Tipo_1 {
            get {
                object obj = ResourceManager.GetObject("Condicion Contorno Tipo 1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Conexionentrada {
            get {
                object obj = ResourceManager.GetObject("Conexionentrada", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Conexionsalida {
            get {
                object obj = ResourceManager.GetObject("Conexionsalida", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Counter_current_profile {
            get {
                object obj = ResourceManager.GetObject("Counter-current_profile", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Cursor {
            get {
                object obj = ResourceManager.GetObject("Cursor", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Cursor1 {
            get {
                object obj = ResourceManager.GetObject("Cursor1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Datos_de_Entrada_MSR_Tipo_14 {
            get {
                object obj = ResourceManager.GetObject("Datos de Entrada MSR Tipo 14", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Datos_de_Entrada_Separador_Humedad_Tipo_13 {
            get {
                object obj = ResourceManager.GetObject("Datos de Entrada Separador Humedad Tipo 13", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Datos_Entrada_Bomba_Tipo_4 {
            get {
                object obj = ResourceManager.GetObject("Datos Entrada Bomba Tipo 4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Datos_Entrada_Caldera_Tipo_6 {
            get {
                object obj = ResourceManager.GetObject("Datos Entrada Caldera Tipo 6", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Datos_Entrada_Calentador_Tipo_7 {
            get {
                object obj = ResourceManager.GetObject("Datos Entrada Calentador Tipo 7", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Datos_Entrada_CondContorno_Tipo_1 {
            get {
                object obj = ResourceManager.GetObject("Datos Entrada CondContorno Tipo 1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Datos_Entrada_Condensador_Tipo_15 {
            get {
                object obj = ResourceManager.GetObject("Datos Entrada Condensador Tipo 15", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Datos_Entrada_Condensador_Tipo_8 {
            get {
                object obj = ResourceManager.GetObject("Datos Entrada Condensador Tipo 8", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Datos_Entrada_Desaireador_Tipo_18 {
            get {
                object obj = ResourceManager.GetObject("Datos Entrada Desaireador Tipo 18", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Datos_Entrada_Divisor_Entalpia_Fija_Tipo_20 {
            get {
                object obj = ResourceManager.GetObject("Datos Entrada Divisor Entalpia Fija Tipo 20", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Datos_Entrada_Divisor_Tipo_2 {
            get {
                object obj = ResourceManager.GetObject("Datos Entrada Divisor Tipo 2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Datos_Entrada_Mezclador_Tipo_5 {
            get {
                object obj = ResourceManager.GetObject("Datos Entrada Mezclador Tipo 5", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Datos_Entrada_Perdida_Carga_Tipo_3 {
            get {
                object obj = ResourceManager.GetObject("Datos Entrada Perdida Carga Tipo 3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Datos_Entrada_Tanque_Vaporización_Instantanea_Tipo_21 {
            get {
                object obj = ResourceManager.GetObject("Datos Entrada Tanque Vaporización Instantanea Tipo 21", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Datos_Entrada_Turbina_Auxiliar_Tipo_11 {
            get {
                object obj = ResourceManager.GetObject("Datos Entrada Turbina Auxiliar Tipo 11", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Datos_Entrada_Turbina_Tipo_10 {
            get {
                object obj = ResourceManager.GetObject("Datos Entrada Turbina Tipo 10", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Datos_Entrada_Turbina_Tipo_9 {
            get {
                object obj = ResourceManager.GetObject("Datos Entrada Turbina Tipo 9", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Datos_Entrada_Turbina_Tipo_91 {
            get {
                object obj = ResourceManager.GetObject("Datos Entrada Turbina Tipo 91", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Datos_Entrada_Valvula_Control_Tipo_19 {
            get {
                object obj = ResourceManager.GetObject("Datos Entrada Valvula Control Tipo 19", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Datos1_de_Entrada_MSR_Tipo_14 {
            get {
                object obj = ResourceManager.GetObject("Datos1 de Entrada MSR Tipo 14", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Datos1_Entrada_Calentador_Tipo_7 {
            get {
                object obj = ResourceManager.GetObject("Datos1 Entrada Calentador Tipo 7", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Datos1_Entrada_Condensador_Tipo_8 {
            get {
                object obj = ResourceManager.GetObject("Datos1 Entrada Condensador Tipo 8", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Datos1_Entrada_Turbina_Tipo_9 {
            get {
                object obj = ResourceManager.GetObject("Datos1 Entrada Turbina Tipo 9", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Datos1_Entrada_Turbina_Tipo_91 {
            get {
                object obj = ResourceManager.GetObject("Datos1 Entrada Turbina Tipo 91", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Desaireador_Tipo_18 {
            get {
                object obj = ResourceManager.GetObject("Desaireador Tipo 18", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Desgasificador {
            get {
                object obj = ResourceManager.GetObject("Desgasificador", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Divisor {
            get {
                object obj = ResourceManager.GetObject("Divisor", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Divisor_Entalpia_Fija_Tipo_20 {
            get {
                object obj = ResourceManager.GetObject("Divisor Entalpia Fija Tipo 20", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Divisor_Tipo_2 {
            get {
                object obj = ResourceManager.GetObject("Divisor Tipo 2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Divisor1 {
            get {
                object obj = ResourceManager.GetObject("Divisor1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Ecuacioines_Desaireador_Tipo_18 {
            get {
                object obj = ResourceManager.GetObject("Ecuacioines Desaireador Tipo 18", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Ecuaciones_Bomba_Tipo_4 {
            get {
                object obj = ResourceManager.GetObject("Ecuaciones Bomba Tipo 4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Ecuaciones_Caldera_Tipo_6 {
            get {
                object obj = ResourceManager.GetObject("Ecuaciones Caldera Tipo 6", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Ecuaciones_Calentador_Tipo_7 {
            get {
                object obj = ResourceManager.GetObject("Ecuaciones Calentador Tipo 7", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Ecuaciones_CondContorno_Tipo_1 {
            get {
                object obj = ResourceManager.GetObject("Ecuaciones CondContorno Tipo 1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Ecuaciones_Condensador_Tipo_15 {
            get {
                object obj = ResourceManager.GetObject("Ecuaciones Condensador Tipo 15", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Ecuaciones_Condensador_Tipo_8 {
            get {
                object obj = ResourceManager.GetObject("Ecuaciones Condensador Tipo 8", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Ecuaciones_Condensador_Tipo_81 {
            get {
                object obj = ResourceManager.GetObject("Ecuaciones Condensador Tipo 81", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Ecuaciones_Divisor_Entalpia_Fija_Tipo_20 {
            get {
                object obj = ResourceManager.GetObject("Ecuaciones Divisor Entalpia Fija Tipo 20", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Ecuaciones_Divisor_Tipo_2 {
            get {
                object obj = ResourceManager.GetObject("Ecuaciones Divisor Tipo 2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Ecuaciones_Mezclador_Tipo_5 {
            get {
                object obj = ResourceManager.GetObject("Ecuaciones Mezclador Tipo 5", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Ecuaciones_MSR_Tipo_14 {
            get {
                object obj = ResourceManager.GetObject("Ecuaciones MSR Tipo 14", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Ecuaciones_Perdida_Carga_Tipo_3 {
            get {
                object obj = ResourceManager.GetObject("Ecuaciones Perdida Carga Tipo 3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Ecuaciones_Separador_Humedad_Tipo_13 {
            get {
                object obj = ResourceManager.GetObject("Ecuaciones Separador Humedad Tipo 13", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Ecuaciones_Tanque_Vaporización_Instantanea_Tipo_21 {
            get {
                object obj = ResourceManager.GetObject("Ecuaciones Tanque Vaporización Instantanea Tipo 21", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Ecuaciones_Turbina_Auxiliar_Tipo_11 {
            get {
                object obj = ResourceManager.GetObject("Ecuaciones Turbina Auxiliar Tipo 11", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Ecuaciones_Turbina_Tipo_10 {
            get {
                object obj = ResourceManager.GetObject("Ecuaciones Turbina Tipo 10", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Ecuaciones_Turbina_Tipo_9 {
            get {
                object obj = ResourceManager.GetObject("Ecuaciones Turbina Tipo 9", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Ecuaciones_Turbina_Tipo_91 {
            get {
                object obj = ResourceManager.GetObject("Ecuaciones Turbina Tipo 91", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Ecuaciones_Valvula_Tipo_19 {
            get {
                object obj = ResourceManager.GetObject("Ecuaciones Valvula Tipo 19", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Ecuaciones1_MSR_Tipo_14 {
            get {
                object obj = ResourceManager.GetObject("Ecuaciones1 MSR Tipo 14", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Ecuaciones1_Separador_Humedad_Tipo_13 {
            get {
                object obj = ResourceManager.GetObject("Ecuaciones1 Separador Humedad Tipo 13", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Error_Maximo {
            get {
                object obj = ResourceManager.GetObject("Error Maximo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Factor_Iteraciones {
            get {
                object obj = ResourceManager.GetObject("Factor Iteraciones", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Fuente {
            get {
                object obj = ResourceManager.GetObject("Fuente", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Heat_exchanger_Segmented {
            get {
                object obj = ResourceManager.GetObject("Heat_exchanger_Segmented", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Icono_Turbina {
            get {
                object obj = ResourceManager.GetObject("Icono Turbina", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Imagen_Balance_Energía {
            get {
                object obj = ResourceManager.GetObject("Imagen Balance Energía", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Imagen_Balance_Energía1 {
            get {
                object obj = ResourceManager.GetObject("Imagen Balance Energía1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Imagen_Balance_Energía2 {
            get {
                object obj = ResourceManager.GetObject("Imagen Balance Energía2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Mezclador {
            get {
                object obj = ResourceManager.GetObject("Mezclador", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Mezclador_Tipo_5 {
            get {
                object obj = ResourceManager.GetObject("Mezclador Tipo 5", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Mezclador1 {
            get {
                object obj = ResourceManager.GetObject("Mezclador1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Mezclador11 {
            get {
                object obj = ResourceManager.GetObject("Mezclador11", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Mezclador12 {
            get {
                object obj = ResourceManager.GetObject("Mezclador12", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap MSR {
            get {
                object obj = ResourceManager.GetObject("MSR", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap MSR_Tipo_14 {
            get {
                object obj = ResourceManager.GetObject("MSR Tipo 14", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap MSR1 {
            get {
                object obj = ResourceManager.GetObject("MSR1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Newton_iteration {
            get {
                object obj = ResourceManager.GetObject("Newton_iteration", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Newton_iteration2 {
            get {
                object obj = ResourceManager.GetObject("Newton_iteration2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Newton_iteration4 {
            get {
                object obj = ResourceManager.GetObject("Newton_iteration4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Newton_Raphson1 {
            get {
                object obj = ResourceManager.GetObject("Newton Raphson1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Newton_Raphson11 {
            get {
                object obj = ResourceManager.GetObject("Newton Raphson11", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Newtonaa {
            get {
                object obj = ResourceManager.GetObject("Newtonaa", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap NewtonIteration1 {
            get {
                object obj = ResourceManager.GetObject("NewtonIteration1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap NewtonIteration2 {
            get {
                object obj = ResourceManager.GetObject("NewtonIteration2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap NewtonIteration3 {
            get {
                object obj = ResourceManager.GetObject("NewtonIteration3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap NewtonIteration5 {
            get {
                object obj = ResourceManager.GetObject("NewtonIteration5", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Perdida_Carga_Tipo_3 {
            get {
                object obj = ResourceManager.GetObject("Perdida Carga Tipo 3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Perdidacarga {
            get {
                object obj = ResourceManager.GetObject("Perdidacarga", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Perdidacarga1 {
            get {
                object obj = ResourceManager.GetObject("Perdidacarga1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Separador_de_Humedad_Tipo_13 {
            get {
                object obj = ResourceManager.GetObject("Separador de Humedad Tipo 13", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap SepHumedad {
            get {
                object obj = ResourceManager.GetObject("SepHumedad", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Sephumedad1 {
            get {
                object obj = ResourceManager.GetObject("Sephumedad1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Shell_side {
            get {
                object obj = ResourceManager.GetObject("Shell-side", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Sumidero {
            get {
                object obj = ResourceManager.GetObject("Sumidero", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Tanque_Vaporización_Instantanea_Tipo_21 {
            get {
                object obj = ResourceManager.GetObject("Tanque Vaporización Instantanea Tipo 21", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Tube_side_copy {
            get {
                object obj = ResourceManager.GetObject("Tube-side_copy", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Turbina_Auxiliar_Tipo_11 {
            get {
                object obj = ResourceManager.GetObject("Turbina Auxiliar Tipo 11", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Turbina_Tipo_10 {
            get {
                object obj = ResourceManager.GetObject("Turbina Tipo 10", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Turbina_Tipo_9 {
            get {
                object obj = ResourceManager.GetObject("Turbina Tipo 9", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Turbina1 {
            get {
                object obj = ResourceManager.GetObject("Turbina1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Turbina3 {
            get {
                object obj = ResourceManager.GetObject("Turbina3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Turbinaboton {
            get {
                object obj = ResourceManager.GetObject("Turbinaboton", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap TurbinaDibujo {
            get {
                object obj = ResourceManager.GetObject("TurbinaDibujo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Valvula {
            get {
                object obj = ResourceManager.GetObject("Valvula", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Valvula_Control_Tipo_19 {
            get {
                object obj = ResourceManager.GetObject("Valvula Control Tipo 19", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap WATER_DROP {
            get {
                object obj = ResourceManager.GetObject("WATER DROP", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
