     EMPRESARIOS AGRUPADOS, A.I.E.                                                                             PAGINA     1
                                                      **********************                           FECHA Mon Dec  6 2010
  GHESA INGENIERIA Y TECNOLOGIA, S.A                  *      HBAL-05       *
                                                      * ================== *
  DEPARTAMENTO DE ANALISIS MECANICOS                  **********************
  ==================================


              Balance original de CERNAVODA(CNN RUMANIA) 700 mw - Pcondensador = 4.23 kPA     


         1         1         1         0         2         0    0        
  1.04400E+03  4.69000E+01  0.00000E+00  0.00000E+00  1.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00
         2         2         2         0         3       115    0        
  1.00000E-06  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00
        89         3         3         0       120         0    0        
  1.40000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00
         3         2       120         0         4        54    0        
  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00
         4         2         4         0         5       113    0        
  9.23600E-01  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00
         5         2         5         0         6        56    0        
  4.93060E-01  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00
         6        19         6         0         7         0    0        
  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00
         7         9         7         0         8         0    0        
  8.49060E-01  0.00000E+00  3.12510E+01  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00
         8        13         8         0         9        57    0        
  1.55000E-03  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00
         9         2         9         0        10        86    0        
  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00
        10         9        10         0        11         0    0        
  8.08000E-01  0.00000E+00  8.85678E+01  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00
        11        20        11         0        12        87    0        
  9.83056E-01  2.57610E+03  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00
        12        20        12         0        13        88    0        
  9.83056E-01  2.57870E+03  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00
        13         3        13         0        14         0    0        
  1.20000E-01  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00
        14        13        14         0        15        89    0        
  9.30000E-01  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00
        15        14        15        90        16        92    0        
  1.40000E-01  0.00000E+00  0.00000E+00  0.00000E+00  2.03000E+01  1.00000E+00  6.62000E-01  0.00000E+00  0.00000E+00
        16         3        16         0        17         0    0        
  1.20000E-01  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00
        17         9        17         0        18         0    0        
  8.84500E-01  0.00000E+00  1.14475E+02  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00
        18         2        18         0        19        58    0        
  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00
        19         9        19         0        20         0    0        
  9.07000E-01  0.00000E+00  2.36865E+02  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00
        20        13        20         0        21        94    0        
  1.00000E-06  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00
        21         2        21         0        22        60    0        
  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00
        22         9        22         0        23         0    0        
  8.52000E-01  0.00000E+00  5.08828E+02  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00
        23        13        23         0        24        96    0        
  4.65000E-02  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00
        24         2        24         0        25        62    0        
  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00
     EMPRESARIOS AGRUPADOS, A.I.E.                                                                             PAGINA     2
                                                      **********************                           FECHA Mon Dec  6 2010
  GHESA INGENIERIA Y TECNOLOGIA, S.A                  *      HBAL-05       *
                                                      * ================== *
  DEPARTAMENTO DE ANALISIS MECANICOS                  **********************
  ==================================


              Balance original de CERNAVODA(CNN RUMANIA) 700 mw - Pcondensador = 4.23 kPA     


        25         9        25         0        26         0    0        
  8.00000E-01  0.00000E+00  1.14775E+03  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00
        26        13        26         0        27        98    0        
  6.00000E-02  5.05800E-03  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00
        27         2        27         0        28        64    0        
  1.00000E-05  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00
        28         9        28         0        29         0    0        
  8.22000E-01  0.00000E+00  1.81337E+03  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00
        29        13        29         0        30       101    0        
  6.26800E-02  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00
        30         2        30         0        31        66    0        
  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00
        31         9        31         0        32         0    0        
  8.00000E-01  0.00000E+00  2.80461E+03  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00
        32        13        32         0        33       103    0        
  6.12500E-02  5.00000E-03  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00
        33         2        33         0        34        68    0        
  1.00000E-07  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00
        34         9        34         0        35         0    0        
  6.61600E-01  0.00000E+00  5.14406E+03  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00
        35         8        35        83        36         0    0        
  4.23000E-02  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00
        36         3        36         0        37         0    0        
 -5.00000E-01  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00
        37         4        37         0        38         0    0        
  0.00000E+00  0.00000E+00  0.00000E+00  8.00000E-01  0.00000E+00  0.00000E+00  3.00000E+00  0.00000E+00  0.00000E+00
        38         3        38         0        39         0    0        
  5.00000E-01  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00
        39        15        39       105        40       106    0        
 -1.13600E-02  0.00000E+00  1.29000E-07  0.00000E+00  0.00000E+00  1.00000E+00  1.01320E+00  0.00000E+00  0.00000E+00
        40         3        40         0        41         0    0        
  5.00000E-01  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00
        41         7        41       102        42        71    0        
  1.00000E+00  0.00000E+00  0.00000E+00  5.60000E+00  2.80000E+00  1.00000E+00  0.00000E+00  0.00000E+00  1.07000E+02
        42         3        42         0        43         0    0        
  5.00000E-01  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00
        43         7        43        97        44        82    0        
  1.00000E+00  0.00000E+00  0.00000E+00  5.60000E+00  2.80000E+00  1.00000E+00  0.00000E+00  0.00000E+00  1.08000E+02
        44         3        44         0        45         0    0        
  5.00000E-01  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00
        45         7        45        95        46       108    0        
  1.00000E+00  0.00000E+00  0.00000E+00  5.60000E+00  2.80000E+00  1.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00
        46         3        46         0        47         0    0        
  5.00000E-01  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00
        47        18        47        93        48       100    0        
  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  1.00000E+00  1.00000E+00  0.00000E+00  1.09000E+02
        48         3        48         0        49         0    0        
 -5.00000E-01  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00
        49         4        49         0        50         0    0        
  0.00000E+00  0.00000E+00  0.00000E+00  8.30000E-01  0.00000E+00  0.00000E+00  2.00000E+00  0.00000E+00  0.00000E+00
     EMPRESARIOS AGRUPADOS, A.I.E.                                                                             PAGINA     3
                                                      **********************                           FECHA Mon Dec  6 2010
  GHESA INGENIERIA Y TECNOLOGIA, S.A                  *      HBAL-05       *
                                                      * ================== *
  DEPARTAMENTO DE ANALISIS MECANICOS                  **********************
  ==================================


              Balance original de CERNAVODA(CNN RUMANIA) 700 mw - Pcondensador = 4.23 kPA     


        50         3        50         0        51         0    0        
  5.00000E-01  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00
        51         7        51       110        52        72    0        
  1.00000E+00  0.00000E+00  0.00000E+00  5.60000E+00  2.80000E+00  1.00000E+00  0.00000E+00  0.00000E+00  1.16000E+02
        52         3        52         0        53         0    0        
  5.00000E-01  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00
        53         6       114         0         1         0    0        
  9.91000E+00  0.00000E+00  0.00000E+00  0.00000E+00  2.79320E+03  0.00000E+00  1.00000E+00  0.00000E+00  1.00000E+00
        54         3        54         0        55         0    0        
  1.37000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00
        55         2        55         0        90        91    0        
  6.92300E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00
        56         2        56         0        85        75    0        
  1.44720E-01  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00
        57         5        57        86        84         0    0        
  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00
        58         3        58         0        59         0    0        
  2.61000E-01  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00
        59         2        59         0        93       112    0        
  9.09000E-02  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00
        60         5        60        94        61         0    0        
  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00
        61         3        61         0        95         0    0        
  1.10000E-01  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00
        62         5        62        96        63         0    0        
  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00
        63         3        63         0        97         0    0        
  4.40000E-02  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00
        64         5        64        98        65         0    0        
  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00
        65         3        65         0        99         0    0        
  3.00000E-02  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00
        66         5        66       101        67         0    0        
  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00
        67         3        67         0       102         0    0        
  1.60000E-02  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00
        68         5        68       103        69         0    0        
  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00
        69         3        69         0       104         0    0        
  1.00000E-02  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00
        70         5        70       111        80         0    0        
  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00
        71         5        71       106        70         0    0        
  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00
        72         5        72        89       109         0    0        
  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00
        73         5        73        85        74         0    0        
  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00
        74         5        74        91       117         0    0        
  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00
     EMPRESARIOS AGRUPADOS, A.I.E.                                                                             PAGINA     4
                                                      **********************                           FECHA Mon Dec  6 2010
  GHESA INGENIERIA Y TECNOLOGIA, S.A                  *      HBAL-05       *
                                                      * ================== *
  DEPARTAMENTO DE ANALISIS MECANICOS                  **********************
  ==================================


              Balance original de CERNAVODA(CNN RUMANIA) 700 mw - Pcondensador = 4.23 kPA     


        75         5       119       115        76         0    0        
  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00
        76         5        76        88        77         0    0        
  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00
        77         5        77       112        78         0    0        
  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00
        78         5        78       100        79         0    0        
  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00
        79         2        79         0       111       105    0        
  1.07110E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00
        80         5        80       113        81         0    0        
  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00
        81         5        81       104        83         0    0        
  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00
        82         5        82        99       107         0    0        
  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00
        84         3        84         0        73         0    0        
  4.10000E-01  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00
        85         5        53       118       114         0    0        
  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00
        86         2        92         0       118       116    0        
  0.00000E+00  1.00000E-06  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00
        87         5        87        75       119         0    0        
  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00
        88         3       117         0       110         0    0        
  4.00000E-01  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00
     EMPRESARIOS AGRUPADOS, A.I.E.                                                                             PAGINA     5
                                                      **********************                           FECHA Mon Dec  6 2010
  GHESA INGENIERIA Y TECNOLOGIA, S.A                  *      HBAL-05       *
                                                      * ================== *
  DEPARTAMENTO DE ANALISIS MECANICOS                  **********************
  ==================================


              Balance original de CERNAVODA(CNN RUMANIA) 700 mw - Pcondensador = 4.23 kPA     


          LA CORRIENTE     1 SALE DEL EQUIPO    53 Y ENTRA AL EQUIPO     1
          LA CORRIENTE     2 SALE DEL EQUIPO     1 Y ENTRA AL EQUIPO     2
          LA CORRIENTE     3 SALE DEL EQUIPO     2 Y ENTRA AL EQUIPO    89
          LA CORRIENTE     4 SALE DEL EQUIPO     3 Y ENTRA AL EQUIPO     4
          LA CORRIENTE     5 SALE DEL EQUIPO     4 Y ENTRA AL EQUIPO     5
          LA CORRIENTE     6 SALE DEL EQUIPO     5 Y ENTRA AL EQUIPO     6
          LA CORRIENTE     7 SALE DEL EQUIPO     6 Y ENTRA AL EQUIPO     7
          LA CORRIENTE     8 SALE DEL EQUIPO     7 Y ENTRA AL EQUIPO     8
          LA CORRIENTE     9 SALE DEL EQUIPO     8 Y ENTRA AL EQUIPO     9
          LA CORRIENTE    10 SALE DEL EQUIPO     9 Y ENTRA AL EQUIPO    10
          LA CORRIENTE    11 SALE DEL EQUIPO    10 Y ENTRA AL EQUIPO    11
          LA CORRIENTE    12 SALE DEL EQUIPO    11 Y ENTRA AL EQUIPO    12
          LA CORRIENTE    13 SALE DEL EQUIPO    12 Y ENTRA AL EQUIPO    13
          LA CORRIENTE    14 SALE DEL EQUIPO    13 Y ENTRA AL EQUIPO    14
          LA CORRIENTE    15 SALE DEL EQUIPO    14 Y ENTRA AL EQUIPO    15
          LA CORRIENTE    16 SALE DEL EQUIPO    15 Y ENTRA AL EQUIPO    16
          LA CORRIENTE    17 SALE DEL EQUIPO    16 Y ENTRA AL EQUIPO    17
          LA CORRIENTE    18 SALE DEL EQUIPO    17 Y ENTRA AL EQUIPO    18
          LA CORRIENTE    19 SALE DEL EQUIPO    18 Y ENTRA AL EQUIPO    19
          LA CORRIENTE    20 SALE DEL EQUIPO    19 Y ENTRA AL EQUIPO    20
          LA CORRIENTE    21 SALE DEL EQUIPO    20 Y ENTRA AL EQUIPO    21
          LA CORRIENTE    22 SALE DEL EQUIPO    21 Y ENTRA AL EQUIPO    22
          LA CORRIENTE    23 SALE DEL EQUIPO    22 Y ENTRA AL EQUIPO    23
          LA CORRIENTE    24 SALE DEL EQUIPO    23 Y ENTRA AL EQUIPO    24
          LA CORRIENTE    25 SALE DEL EQUIPO    24 Y ENTRA AL EQUIPO    25
          LA CORRIENTE    26 SALE DEL EQUIPO    25 Y ENTRA AL EQUIPO    26
          LA CORRIENTE    27 SALE DEL EQUIPO    26 Y ENTRA AL EQUIPO    27
          LA CORRIENTE    28 SALE DEL EQUIPO    27 Y ENTRA AL EQUIPO    28
          LA CORRIENTE    29 SALE DEL EQUIPO    28 Y ENTRA AL EQUIPO    29
          LA CORRIENTE    30 SALE DEL EQUIPO    29 Y ENTRA AL EQUIPO    30
          LA CORRIENTE    31 SALE DEL EQUIPO    30 Y ENTRA AL EQUIPO    31
          LA CORRIENTE    32 SALE DEL EQUIPO    31 Y ENTRA AL EQUIPO    32
          LA CORRIENTE    33 SALE DEL EQUIPO    32 Y ENTRA AL EQUIPO    33
          LA CORRIENTE    34 SALE DEL EQUIPO    33 Y ENTRA AL EQUIPO    34
          LA CORRIENTE    35 SALE DEL EQUIPO    34 Y ENTRA AL EQUIPO    35
          LA CORRIENTE    36 SALE DEL EQUIPO    35 Y ENTRA AL EQUIPO    36
          LA CORRIENTE    37 SALE DEL EQUIPO    36 Y ENTRA AL EQUIPO    37
          LA CORRIENTE    38 SALE DEL EQUIPO    37 Y ENTRA AL EQUIPO    38
          LA CORRIENTE    39 SALE DEL EQUIPO    38 Y ENTRA AL EQUIPO    39
          LA CORRIENTE    40 SALE DEL EQUIPO    39 Y ENTRA AL EQUIPO    40
          LA CORRIENTE    41 SALE DEL EQUIPO    40 Y ENTRA AL EQUIPO    41
          LA CORRIENTE    42 SALE DEL EQUIPO    41 Y ENTRA AL EQUIPO    42
          LA CORRIENTE    43 SALE DEL EQUIPO    42 Y ENTRA AL EQUIPO    43
          LA CORRIENTE    44 SALE DEL EQUIPO    43 Y ENTRA AL EQUIPO    44
          LA CORRIENTE    45 SALE DEL EQUIPO    44 Y ENTRA AL EQUIPO    45
          LA CORRIENTE    46 SALE DEL EQUIPO    45 Y ENTRA AL EQUIPO    46
          LA CORRIENTE    47 SALE DEL EQUIPO    46 Y ENTRA AL EQUIPO    47
          LA CORRIENTE    48 SALE DEL EQUIPO    47 Y ENTRA AL EQUIPO    48
          LA CORRIENTE    49 SALE DEL EQUIPO    48 Y ENTRA AL EQUIPO    49
          LA CORRIENTE    50 SALE DEL EQUIPO    49 Y ENTRA AL EQUIPO    50
     EMPRESARIOS AGRUPADOS, A.I.E.                                                                             PAGINA     6
                                                      **********************                           FECHA Mon Dec  6 2010
  GHESA INGENIERIA Y TECNOLOGIA, S.A                  *      HBAL-05       *
                                                      * ================== *
  DEPARTAMENTO DE ANALISIS MECANICOS                  **********************
  ==================================


              Balance original de CERNAVODA(CNN RUMANIA) 700 mw - Pcondensador = 4.23 kPA     


          LA CORRIENTE    51 SALE DEL EQUIPO    50 Y ENTRA AL EQUIPO    51
          LA CORRIENTE    52 SALE DEL EQUIPO    51 Y ENTRA AL EQUIPO    52
          LA CORRIENTE    53 SALE DEL EQUIPO    52 Y ENTRA AL EQUIPO    85
          LA CORRIENTE    54 SALE DEL EQUIPO     3 Y ENTRA AL EQUIPO    54
          LA CORRIENTE    55 SALE DEL EQUIPO    54 Y ENTRA AL EQUIPO    55
          LA CORRIENTE    56 SALE DEL EQUIPO     5 Y ENTRA AL EQUIPO    56
          LA CORRIENTE    57 SALE DEL EQUIPO     8 Y ENTRA AL EQUIPO    57
          LA CORRIENTE    58 SALE DEL EQUIPO    18 Y ENTRA AL EQUIPO    58
          LA CORRIENTE    59 SALE DEL EQUIPO    58 Y ENTRA AL EQUIPO    59
          LA CORRIENTE    60 SALE DEL EQUIPO    21 Y ENTRA AL EQUIPO    60
          LA CORRIENTE    61 SALE DEL EQUIPO    60 Y ENTRA AL EQUIPO    61
          LA CORRIENTE    62 SALE DEL EQUIPO    24 Y ENTRA AL EQUIPO    62
          LA CORRIENTE    63 SALE DEL EQUIPO    62 Y ENTRA AL EQUIPO    63
          LA CORRIENTE    64 SALE DEL EQUIPO    27 Y ENTRA AL EQUIPO    64
          LA CORRIENTE    65 SALE DEL EQUIPO    64 Y ENTRA AL EQUIPO    65
          LA CORRIENTE    66 SALE DEL EQUIPO    30 Y ENTRA AL EQUIPO    66
          LA CORRIENTE    67 SALE DEL EQUIPO    66 Y ENTRA AL EQUIPO    67
          LA CORRIENTE    68 SALE DEL EQUIPO    33 Y ENTRA AL EQUIPO    68
          LA CORRIENTE    69 SALE DEL EQUIPO    68 Y ENTRA AL EQUIPO    69
          LA CORRIENTE    70 SALE DEL EQUIPO    71 Y ENTRA AL EQUIPO    70
          LA CORRIENTE    71 SALE DEL EQUIPO    41 Y ENTRA AL EQUIPO    71
          LA CORRIENTE    72 SALE DEL EQUIPO    51 Y ENTRA AL EQUIPO    72
          LA CORRIENTE    73 SALE DEL EQUIPO    84 Y ENTRA AL EQUIPO    73
          LA CORRIENTE    74 SALE DEL EQUIPO    73 Y ENTRA AL EQUIPO    74
          LA CORRIENTE    75 SALE DEL EQUIPO    56 Y ENTRA AL EQUIPO    87
          LA CORRIENTE    76 SALE DEL EQUIPO    75 Y ENTRA AL EQUIPO    76
          LA CORRIENTE    77 SALE DEL EQUIPO    76 Y ENTRA AL EQUIPO    77
          LA CORRIENTE    78 SALE DEL EQUIPO    77 Y ENTRA AL EQUIPO    78
          LA CORRIENTE    79 SALE DEL EQUIPO    78 Y ENTRA AL EQUIPO    79
          LA CORRIENTE    80 SALE DEL EQUIPO    70 Y ENTRA AL EQUIPO    80
          LA CORRIENTE    81 SALE DEL EQUIPO    80 Y ENTRA AL EQUIPO    81
          LA CORRIENTE    82 SALE DEL EQUIPO    43 Y ENTRA AL EQUIPO    82
          LA CORRIENTE    83 SALE DEL EQUIPO    81 Y ENTRA AL EQUIPO    35
          LA CORRIENTE    84 SALE DEL EQUIPO    57 Y ENTRA AL EQUIPO    84
          LA CORRIENTE    85 SALE DEL EQUIPO    56 Y ENTRA AL EQUIPO    73
          LA CORRIENTE    86 SALE DEL EQUIPO     9 Y ENTRA AL EQUIPO    57
          LA CORRIENTE    87 SALE DEL EQUIPO    11 Y ENTRA AL EQUIPO    87
          LA CORRIENTE    88 SALE DEL EQUIPO    12 Y ENTRA AL EQUIPO    76
          LA CORRIENTE    89 SALE DEL EQUIPO    14 Y ENTRA AL EQUIPO    72
          LA CORRIENTE    90 SALE DEL EQUIPO    55 Y ENTRA AL EQUIPO    15
          LA CORRIENTE    91 SALE DEL EQUIPO    55 Y ENTRA AL EQUIPO    74
          LA CORRIENTE    92 SALE DEL EQUIPO    15 Y ENTRA AL EQUIPO    86
          LA CORRIENTE    93 SALE DEL EQUIPO    59 Y ENTRA AL EQUIPO    47
          LA CORRIENTE    94 SALE DEL EQUIPO    20 Y ENTRA AL EQUIPO    60
          LA CORRIENTE    95 SALE DEL EQUIPO    61 Y ENTRA AL EQUIPO    45
          LA CORRIENTE    96 SALE DEL EQUIPO    23 Y ENTRA AL EQUIPO    62
          LA CORRIENTE    97 SALE DEL EQUIPO    63 Y ENTRA AL EQUIPO    43
          LA CORRIENTE    98 SALE DEL EQUIPO    26 Y ENTRA AL EQUIPO    64
          LA CORRIENTE    99 SALE DEL EQUIPO    65 Y ENTRA AL EQUIPO    82
          LA CORRIENTE   100 SALE DEL EQUIPO    47 Y ENTRA AL EQUIPO    78
     EMPRESARIOS AGRUPADOS, A.I.E.                                                                             PAGINA     7
                                                      **********************                           FECHA Mon Dec  6 2010
  GHESA INGENIERIA Y TECNOLOGIA, S.A                  *      HBAL-05       *
                                                      * ================== *
  DEPARTAMENTO DE ANALISIS MECANICOS                  **********************
  ==================================


              Balance original de CERNAVODA(CNN RUMANIA) 700 mw - Pcondensador = 4.23 kPA     


          LA CORRIENTE   101 SALE DEL EQUIPO    29 Y ENTRA AL EQUIPO    66
          LA CORRIENTE   102 SALE DEL EQUIPO    67 Y ENTRA AL EQUIPO    41
          LA CORRIENTE   103 SALE DEL EQUIPO    32 Y ENTRA AL EQUIPO    68
          LA CORRIENTE   104 SALE DEL EQUIPO    69 Y ENTRA AL EQUIPO    81
          LA CORRIENTE   105 SALE DEL EQUIPO    79 Y ENTRA AL EQUIPO    39
          LA CORRIENTE   106 SALE DEL EQUIPO    39 Y ENTRA AL EQUIPO    71
          LA CORRIENTE   107 SALE DEL EQUIPO    82 Y ENTRA AL EQUIPO    41
          LA CORRIENTE   108 SALE DEL EQUIPO    45 Y ENTRA AL EQUIPO    43
          LA CORRIENTE   109 SALE DEL EQUIPO    72 Y ENTRA AL EQUIPO    47
          LA CORRIENTE   110 SALE DEL EQUIPO    88 Y ENTRA AL EQUIPO    51
          LA CORRIENTE   111 SALE DEL EQUIPO    79 Y ENTRA AL EQUIPO    70
          LA CORRIENTE   112 SALE DEL EQUIPO    59 Y ENTRA AL EQUIPO    77
          LA CORRIENTE   113 SALE DEL EQUIPO     4 Y ENTRA AL EQUIPO    80
          LA CORRIENTE   114 SALE DEL EQUIPO    85 Y ENTRA AL EQUIPO    53
          LA CORRIENTE   115 SALE DEL EQUIPO     2 Y ENTRA AL EQUIPO    75
          LA CORRIENTE   116 SALE DEL EQUIPO    86 Y ENTRA AL EQUIPO    51
          LA CORRIENTE   117 SALE DEL EQUIPO    74 Y ENTRA AL EQUIPO    88
          LA CORRIENTE   118 SALE DEL EQUIPO    86 Y ENTRA AL EQUIPO    85
          LA CORRIENTE   119 SALE DEL EQUIPO    87 Y ENTRA AL EQUIPO    75
          LA CORRIENTE   120 SALE DEL EQUIPO    89 Y ENTRA AL EQUIPO     3
     EMPRESARIOS AGRUPADOS, A.I.E.                                                                             PAGINA     8
                                                      **********************                           FECHA Mon Dec  6 2010
  GHESA INGENIERIA Y TECNOLOGIA, S.A                  *      HBAL-05       *
                                                      * ================== *
  DEPARTAMENTO DE ANALISIS MECANICOS                  **********************
  ==================================


              Balance original de CERNAVODA(CNN RUMANIA) 700 mw - Pcondensador = 4.23 kPA     


     EMPRESARIOS AGRUPADOS, A.I.E.                                                                             PAGINA     9
                                                      **********************                           FECHA Mon Dec  6 2010
  GHESA INGENIERIA Y TECNOLOGIA, S.A                  *      HBAL-05       *
                                                      * ================== *
  DEPARTAMENTO DE ANALISIS MECANICOS                  **********************
  ==================================


              Balance original de CERNAVODA(CNN RUMANIA) 700 mw - Pcondensador = 4.23 kPA     


 EL EQUIPO       1 GENERA LAS ECUACIONES     1 --     4
 EL EQUIPO       2 GENERA LAS ECUACIONES     5 --    10
 EL EQUIPO       3 GENERA LAS ECUACIONES    11 --    15
 EL EQUIPO       4 GENERA LAS ECUACIONES    16 --    21
 EL EQUIPO       5 GENERA LAS ECUACIONES    22 --    27
 EL EQUIPO       6 GENERA LAS ECUACIONES    28 --    29
 EL EQUIPO       7 GENERA LAS ECUACIONES    30 --    32
 EL EQUIPO       8 GENERA LAS ECUACIONES    33 --    38
 EL EQUIPO       9 GENERA LAS ECUACIONES    39 --    43
 EL EQUIPO      10 GENERA LAS ECUACIONES    44 --    46
 EL EQUIPO      11 GENERA LAS ECUACIONES    47 --    52
 EL EQUIPO      12 GENERA LAS ECUACIONES    53 --    58
 EL EQUIPO      13 GENERA LAS ECUACIONES    59 --    61
 EL EQUIPO      14 GENERA LAS ECUACIONES    62 --    67
 EL EQUIPO      15 GENERA LAS ECUACIONES    68 --    74
 EL EQUIPO      16 GENERA LAS ECUACIONES    75 --    77
 EL EQUIPO      17 GENERA LAS ECUACIONES    78 --    80
 EL EQUIPO      18 GENERA LAS ECUACIONES    81 --    85
 EL EQUIPO      19 GENERA LAS ECUACIONES    86 --    88
 EL EQUIPO      20 GENERA LAS ECUACIONES    89 --    94
 EL EQUIPO      21 GENERA LAS ECUACIONES    95 --    99
 EL EQUIPO      22 GENERA LAS ECUACIONES   100 --   102
 EL EQUIPO      23 GENERA LAS ECUACIONES   103 --   108
 EL EQUIPO      24 GENERA LAS ECUACIONES   109 --   113
 EL EQUIPO      25 GENERA LAS ECUACIONES   114 --   116
 EL EQUIPO      26 GENERA LAS ECUACIONES   117 --   122
 EL EQUIPO      27 GENERA LAS ECUACIONES   123 --   128
 EL EQUIPO      28 GENERA LAS ECUACIONES   129 --   131
 EL EQUIPO      29 GENERA LAS ECUACIONES   132 --   137
 EL EQUIPO      30 GENERA LAS ECUACIONES   138 --   142
 EL EQUIPO      31 GENERA LAS ECUACIONES   143 --   145
 EL EQUIPO      32 GENERA LAS ECUACIONES   146 --   151
 EL EQUIPO      33 GENERA LAS ECUACIONES   152 --   157
 EL EQUIPO      34 GENERA LAS ECUACIONES   158 --   160
 EL EQUIPO      35 GENERA LAS ECUACIONES   161 --   164
 EL EQUIPO      36 GENERA LAS ECUACIONES   165 --   167
 EL EQUIPO      37 GENERA LAS ECUACIONES   168 --   169
 EL EQUIPO      38 GENERA LAS ECUACIONES   170 --   172
 EL EQUIPO      39 GENERA LAS ECUACIONES   173 --   178
 EL EQUIPO      40 GENERA LAS ECUACIONES   179 --   181
 EL EQUIPO      41 GENERA LAS ECUACIONES   182 --   188
 EL EQUIPO      42 GENERA LAS ECUACIONES   189 --   191
 EL EQUIPO      43 GENERA LAS ECUACIONES   192 --   198
 EL EQUIPO      44 GENERA LAS ECUACIONES   199 --   201
 EL EQUIPO      45 GENERA LAS ECUACIONES   202 --   208
 EL EQUIPO      46 GENERA LAS ECUACIONES   209 --   211
 EL EQUIPO      47 GENERA LAS ECUACIONES   212 --   219
 EL EQUIPO      48 GENERA LAS ECUACIONES   220 --   222
 EL EQUIPO      49 GENERA LAS ECUACIONES   223 --   224
 EL EQUIPO      50 GENERA LAS ECUACIONES   225 --   227
     EMPRESARIOS AGRUPADOS, A.I.E.                                                                             PAGINA    10
                                                      **********************                           FECHA Mon Dec  6 2010
  GHESA INGENIERIA Y TECNOLOGIA, S.A                  *      HBAL-05       *
                                                      * ================== *
  DEPARTAMENTO DE ANALISIS MECANICOS                  **********************
  ==================================


              Balance original de CERNAVODA(CNN RUMANIA) 700 mw - Pcondensador = 4.23 kPA     


 EL EQUIPO      51 GENERA LAS ECUACIONES   228 --   234
 EL EQUIPO      52 GENERA LAS ECUACIONES   235 --   237
 EL EQUIPO      53 GENERA LAS ECUACIONES   238 --   240
 EL EQUIPO      54 GENERA LAS ECUACIONES   241 --   243
 EL EQUIPO      55 GENERA LAS ECUACIONES   244 --   249
 EL EQUIPO      56 GENERA LAS ECUACIONES   250 --   255
 EL EQUIPO      57 GENERA LAS ECUACIONES   256 --   258
 EL EQUIPO      58 GENERA LAS ECUACIONES   259 --   261
 EL EQUIPO      59 GENERA LAS ECUACIONES   262 --   267
 EL EQUIPO      60 GENERA LAS ECUACIONES   268 --   270
 EL EQUIPO      61 GENERA LAS ECUACIONES   271 --   273
 EL EQUIPO      62 GENERA LAS ECUACIONES   274 --   276
 EL EQUIPO      63 GENERA LAS ECUACIONES   277 --   279
 EL EQUIPO      64 GENERA LAS ECUACIONES   280 --   282
 EL EQUIPO      65 GENERA LAS ECUACIONES   283 --   285
 EL EQUIPO      66 GENERA LAS ECUACIONES   286 --   288
 EL EQUIPO      67 GENERA LAS ECUACIONES   289 --   291
 EL EQUIPO      68 GENERA LAS ECUACIONES   292 --   294
 EL EQUIPO      69 GENERA LAS ECUACIONES   295 --   297
 EL EQUIPO      70 GENERA LAS ECUACIONES   298 --   300
 EL EQUIPO      71 GENERA LAS ECUACIONES   301 --   303
 EL EQUIPO      72 GENERA LAS ECUACIONES   304 --   306
 EL EQUIPO      73 GENERA LAS ECUACIONES   307 --   309
 EL EQUIPO      74 GENERA LAS ECUACIONES   310 --   312
 EL EQUIPO      75 GENERA LAS ECUACIONES   313 --   315
 EL EQUIPO      76 GENERA LAS ECUACIONES   316 --   318
 EL EQUIPO      77 GENERA LAS ECUACIONES   319 --   321
 EL EQUIPO      78 GENERA LAS ECUACIONES   322 --   324
 EL EQUIPO      79 GENERA LAS ECUACIONES   325 --   330
 EL EQUIPO      80 GENERA LAS ECUACIONES   331 --   333
 EL EQUIPO      81 GENERA LAS ECUACIONES   334 --   336
 EL EQUIPO      82 GENERA LAS ECUACIONES   337 --   339
 EL EQUIPO      84 GENERA LAS ECUACIONES   340 --   342
 EL EQUIPO      85 GENERA LAS ECUACIONES   343 --   345
 EL EQUIPO      86 GENERA LAS ECUACIONES   346 --   351
 EL EQUIPO      87 GENERA LAS ECUACIONES   352 --   354
 EL EQUIPO      88 GENERA LAS ECUACIONES   355 --   357
 EL EQUIPO      89 GENERA LAS ECUACIONES   358 --   360
     EMPRESARIOS AGRUPADOS, A.I.E.                                                                             PAGINA    11
                                                      **********************                           FECHA Mon Dec  6 2010
  GHESA INGENIERIA Y TECNOLOGIA, S.A                  *      HBAL-05       *
                                                      * ================== *
  DEPARTAMENTO DE ANALISIS MECANICOS                  **********************
  ==================================


              Balance original de CERNAVODA(CNN RUMANIA) 700 mw - Pcondensador = 4.23 kPA     


 CORRIENTE NUMERO     1 --------  1.04400000E+03 4.69000000E+01 2.79320000E+03
 CORRIENTE NUMERO     2 --------  1.04410001E+03 4.69000000E+01 2.79320000E+03
 CORRIENTE NUMERO     3 --------  1.04410000E+03 4.55100000E+01 2.79320000E+03
 CORRIENTE NUMERO     4 --------  9.67884960E+02 4.55100000E+01 2.79320000E+03
 CORRIENTE NUMERO     5 --------  9.66961360E+02 4.55100000E+01 2.79320000E+03
 CORRIENTE NUMERO     6 --------  9.66468300E+02 4.55100000E+01 2.79320000E+03
 CORRIENTE NUMERO     7 --------  9.66468300E+02 4.34973200E+01 2.79320000E+03
 CORRIENTE NUMERO     8 --------  9.66468245E+02 1.33623800E+01 2.60603500E+03
 CORRIENTE NUMERO     9 --------  9.66330870E+02 1.33623800E+01 2.60628900E+03
 CORRIENTE NUMERO    10 --------  8.85063800E+02 1.33623800E+01 2.60628900E+03
 CORRIENTE NUMERO    11 --------  8.85063812E+02 1.08607100E+01 2.57668400E+03
 CORRIENTE NUMERO    12 --------  8.84080756E+02 1.08607100E+01 2.57668500E+03
 CORRIENTE NUMERO    13 --------  8.83097700E+02 1.08607100E+01 2.57668200E+03
 CORRIENTE NUMERO    14 --------  8.83097680E+02 1.07407100E+01 2.57668200E+03
 CORRIENTE NUMERO    15 --------  8.00194900E+02 1.07407100E+01 2.76319200E+03
 CORRIENTE NUMERO    16 --------  8.00194900E+02 1.06007100E+01 2.90879000E+03
 CORRIENTE NUMERO    17 --------  8.00194900E+02 1.04807100E+01 2.90879000E+03
 CORRIENTE NUMERO    18 --------  8.00194960E+02 4.40016700E+00 2.75240700E+03
 CORRIENTE NUMERO    19 --------  7.59311600E+02 4.40016700E+00 2.75240700E+03
 CORRIENTE NUMERO    20 --------  7.59311626E+02 1.85076700E+00 2.62565900E+03
 CORRIENTE NUMERO    21 --------  7.59071620E+02 1.85076700E+00 2.62633300E+03
 CORRIENTE NUMERO    22 --------  7.22013400E+02 1.85076700E+00 2.62633300E+03
 CORRIENTE NUMERO    23 --------  7.22013422E+02 7.44358100E-01 2.50316500E+03
 CORRIENTE NUMERO    24 --------  7.19193480E+02 7.44358100E-01 2.51147600E+03
 CORRIENTE NUMERO    25 --------  6.85856800E+02 7.44358100E-01 2.51147600E+03
 CORRIENTE NUMERO    26 --------  6.85856740E+02 4.56226000E-01 2.45082400E+03
 CORRIENTE NUMERO    27 --------  6.78856510E+02 4.56226000E-01 2.46204300E+03
 CORRIENTE NUMERO    28 --------  6.78856500E+02 4.56226000E-01 2.46204300E+03
 CORRIENTE NUMERO    29 --------  6.78856502E+02 2.71137700E-01 2.40173700E+03
 CORRIENTE NUMERO    30 --------  6.74291740E+02 2.71137700E-01 2.41610300E+03
 CORRIENTE NUMERO    31 --------  6.37639300E+02 2.71137700E-01 2.41610300E+03
 CORRIENTE NUMERO    32 --------  6.37639358E+02 1.42199700E-01 2.34336600E+03
 CORRIENTE NUMERO    33 --------  6.30086910E+02 1.42199700E-01 2.35809700E+03
 CORRIENTE NUMERO    34 --------  6.30086900E+02 1.42199700E-01 2.35809700E+03
 CORRIENTE NUMERO    35 --------  6.30086900E+02 4.23000000E-02 2.24375600E+03
 CORRIENTE NUMERO    36 --------  7.62665800E+02 4.23000000E-02 1.25466100E+02
 CORRIENTE NUMERO    37 --------  7.62665800E+02 5.42300000E-01 1.25466100E+02
 CORRIENTE NUMERO    38 --------  7.62665800E+02 9.70337600E+00 1.26616200E+02
 CORRIENTE NUMERO    39 --------  7.62665800E+02 9.20337600E+00 1.26616200E+02
 CORRIENTE NUMERO    40 --------  7.62665800E+02 9.13916700E+00 1.29696000E+02
 CORRIENTE NUMERO    41 --------  7.62665800E+02 8.63916700E+00 1.29696000E+02
 CORRIENTE NUMERO    42 --------  7.62665800E+02 7.63916700E+00 2.63207200E+02
 CORRIENTE NUMERO    43 --------  7.62665800E+02 7.13916700E+00 2.63207200E+02
 CORRIENTE NUMERO    44 --------  7.62665800E+02 6.13916700E+00 3.65897600E+02
 CORRIENTE NUMERO    45 --------  7.62665800E+02 5.63916700E+00 3.65897600E+02
 CORRIENTE NUMERO    46 --------  7.62665800E+02 4.63916700E+00 4.74657200E+02
 CORRIENTE NUMERO    47 --------  7.62665800E+02 4.13916700E+00 4.74657200E+02
 CORRIENTE NUMERO    48 --------  9.74808000E+02 4.13916700E+00 6.09990500E+02
 CORRIENTE NUMERO    49 --------  9.74808000E+02 4.63916700E+00 6.09990500E+02
 CORRIENTE NUMERO    50 --------  9.74808000E+02 5.88100000E+01 6.17072800E+02
     EMPRESARIOS AGRUPADOS, A.I.E.                                                                             PAGINA    12
                                                      **********************                           FECHA Mon Dec  6 2010
  GHESA INGENIERIA Y TECNOLOGIA, S.A                  *      HBAL-05       *
                                                      * ================== *
  DEPARTAMENTO DE ANALISIS MECANICOS                  **********************
  ==================================


              Balance original de CERNAVODA(CNN RUMANIA) 700 mw - Pcondensador = 4.23 kPA     


 CORRIENTE NUMERO    51 --------  9.74808000E+02 5.83100000E+01 6.17072800E+02
 CORRIENTE NUMERO    52 --------  9.74808000E+02 5.73100000E+01 7.97241400E+02
 CORRIENTE NUMERO    53 --------  9.74808000E+02 5.68100000E+01 7.97241400E+02
 CORRIENTE NUMERO    54 --------  7.62150400E+01 4.55100000E+01 2.79320000E+03
 CORRIENTE NUMERO    55 --------  7.62150500E+01 4.41400000E+01 2.79320000E+03
 CORRIENTE NUMERO    56 --------  4.93060000E-01 4.55100000E+01 2.79320000E+03
 CORRIENTE NUMERO    57 --------  1.37375200E-01 1.33623800E+01 8.20368300E+02
 CORRIENTE NUMERO    58 --------  4.08833600E+01 4.40016700E+00 2.75240700E+03
 CORRIENTE NUMERO    59 --------  4.08833600E+01 4.13916700E+00 2.75240700E+03
 CORRIENTE NUMERO    60 --------  3.70582200E+01 1.85076700E+00 2.62633300E+03
 CORRIENTE NUMERO    61 --------  3.72982300E+01 1.85076700E+00 2.61261400E+03
 CORRIENTE NUMERO    62 --------  3.33366800E+01 7.44358100E-01 2.51147600E+03
 CORRIENTE NUMERO    63 --------  3.61566200E+01 7.44358100E-01 2.34551800E+03
 CORRIENTE NUMERO    64 --------  1.00000000E-05 4.56226000E-01 2.46204300E+03
 CORRIENTE NUMERO    65 --------  7.00024000E+00 4.56226000E-01 1.36287900E+03
 CORRIENTE NUMERO    66 --------  3.66524400E+01 2.71137700E-01 2.41610300E+03
 CORRIENTE NUMERO    67 --------  4.12172000E+01 2.71137700E-01 2.17949200E+03
 CORRIENTE NUMERO    68 --------  1.00000000E-05 1.42199700E-01 2.35809700E+03
 CORRIENTE NUMERO    69 --------  7.55245800E+00 1.42199700E-01 1.11434400E+03
 CORRIENTE NUMERO    70 --------  1.22743400E+02 2.55137700E-01 1.54660800E+02
 CORRIENTE NUMERO    71 --------  1.21672300E+02 2.55137700E-01 1.52333300E+02
 CORRIENTE NUMERO    72 --------  8.86758600E+01 1.25523800E+01 6.38265900E+02
 CORRIENTE NUMERO    73 --------  8.14044500E+01 1.29523800E+01 2.60327500E+03
 CORRIENTE NUMERO    74 --------  8.17527900E+01 1.29523800E+01 2.60408400E+03
 CORRIENTE NUMERO    75 --------  1.44720000E-01 4.55100000E+01 2.79320000E+03
 CORRIENTE NUMERO    76 --------  1.12777600E+00 1.08607100E+01 2.60395900E+03
 CORRIENTE NUMERO    77 --------  2.11083200E+00 1.08607100E+01 2.59219500E+03
 CORRIENTE NUMERO    78 --------  2.20173200E+00 1.08607100E+01 2.59881000E+03
 CORRIENTE NUMERO    79 --------  2.43066000E+00 1.08607100E+01 2.61202800E+03
 CORRIENTE NUMERO    80 --------  1.24102900E+02 2.55137700E-01 1.81581500E+02
 CORRIENTE NUMERO    81 --------  1.25026500E+02 2.55137700E-01 2.00874200E+02
 CORRIENTE NUMERO    82 --------  7.34548400E+01 7.00358000E-01 2.85702200E+02
 CORRIENTE NUMERO    83 --------  1.32579000E+02 2.55137700E-01 2.52910600E+02
 CORRIENTE NUMERO    84 --------  8.14044500E+01 1.33623800E+01 2.60327500E+03
 CORRIENTE NUMERO    85 --------  3.48340000E-01 4.55100000E+01 2.79320000E+03
 CORRIENTE NUMERO    86 --------  8.12670700E+01 1.33623800E+01 2.60628900E+03
 CORRIENTE NUMERO    87 --------  9.83056000E-01 1.08607100E+01 2.57610000E+03
 CORRIENTE NUMERO    88 --------  9.83056000E-01 1.08607100E+01 2.57870000E+03
 CORRIENTE NUMERO    89 --------  8.29027800E+01 1.07407100E+01 7.76447300E+02
 CORRIENTE NUMERO    90 --------  6.92920500E+01 4.41400000E+01 2.79320000E+03
 CORRIENTE NUMERO    91 --------  6.92300000E+00 4.41400000E+01 2.79320000E+03
 CORRIENTE NUMERO    92 --------  6.92920493E+01 4.34780000E+01 1.11182000E+03
 CORRIENTE NUMERO    93 --------  4.07924600E+01 4.13916700E+00 2.75240700E+03
 CORRIENTE NUMERO    94 --------  2.40006200E-01 1.85076700E+00 4.94365200E+02
 CORRIENTE NUMERO    95 --------  3.72982300E+01 1.74076700E+00 2.61261400E+03
 CORRIENTE NUMERO    96 --------  2.81994200E+00 7.44358100E-01 3.83605900E+02
 CORRIENTE NUMERO    97 --------  3.61566200E+01 7.00358000E-01 2.34551800E+03
 CORRIENTE NUMERO    98 --------  7.00023000E+00 4.56226000E-01 1.36287700E+03
 CORRIENTE NUMERO    99 --------  7.00024000E+00 4.26226000E-01 1.36287900E+03
 CORRIENTE NUMERO   100 --------  2.28927700E-01 4.13916700E+00 2.73915600E+03
     EMPRESARIOS AGRUPADOS, A.I.E.                                                                             PAGINA    13
                                                      **********************                           FECHA Mon Dec  6 2010
  GHESA INGENIERIA Y TECNOLOGIA, S.A                  *      HBAL-05       *
                                                      * ================== *
  DEPARTAMENTO DE ANALISIS MECANICOS                  **********************
  ==================================


              Balance original de CERNAVODA(CNN RUMANIA) 700 mw - Pcondensador = 4.23 kPA     


 CORRIENTE NUMERO   101 --------  4.56476200E+00 2.71137700E-01 2.79636200E+02
 CORRIENTE NUMERO   102 --------  4.12172000E+01 2.55137700E-01 2.17949200E+03
 CORRIENTE NUMERO   103 --------  7.55245800E+00 1.42199700E-01 1.11434400E+03
 CORRIENTE NUMERO   104 --------  7.55245800E+00 1.32199700E-01 1.11434400E+03
 CORRIENTE NUMERO   105 --------  1.07110000E+00 1.08607100E+01 2.61202800E+03
 CORRIENTE NUMERO   106 --------  1.07110000E+00 1.01320000E+00 4.19058600E+02
 CORRIENTE NUMERO   107 --------  8.04550900E+01 7.00358000E-01 3.79425200E+02
 CORRIENTE NUMERO   108 --------  3.72982300E+01 1.74076700E+00 3.88720700E+02
 CORRIENTE NUMERO   109 --------  1.71578600E+02 1.25523800E+01 7.05031900E+02
 CORRIENTE NUMERO   110 --------  8.86757900E+01 1.25523800E+01 2.61884800E+03
 CORRIENTE NUMERO   111 --------  1.35956000E+00 1.08607100E+01 2.61202800E+03
 CORRIENTE NUMERO   112 --------  9.09000000E-02 4.13916700E+00 2.75240700E+03
 CORRIENTE NUMERO   113 --------  9.23600000E-01 4.55100000E+01 2.79320000E+03
 CORRIENTE NUMERO   114 --------  1.04410000E+03 5.68100000E+01 8.18118500E+02
 CORRIENTE NUMERO   115 --------  1.00000000E-05 4.55100000E+01 2.79320000E+03
 CORRIENTE NUMERO   116 --------  6.92920400E-05 4.34780000E+01 1.11182000E+03
 CORRIENTE NUMERO   117 --------  8.86757900E+01 1.29523800E+01 2.61884800E+03
 CORRIENTE NUMERO   118 --------  6.92919800E+01 4.34780000E+01 1.11182000E+03
 CORRIENTE NUMERO   119 --------  1.12777600E+00 1.08607100E+01 2.60395900E+03
 CORRIENTE NUMERO   120 --------  1.04410004E+03 4.55100000E+01 2.79320000E+03
     EMPRESARIOS AGRUPADOS, A.I.E.                                                                             PAGINA    14
                                                      **********************                           FECHA Mon Dec  6 2010
  GHESA INGENIERIA Y TECNOLOGIA, S.A                  *      HBAL-05       *
                                                      * ================== *
  DEPARTAMENTO DE ANALISIS MECANICOS                  **********************
  ==================================


              Balance original de CERNAVODA(CNN RUMANIA) 700 mw - Pcondensador = 4.23 kPA     


 NUMERO DE NO CEROS EN LA MATRIZ=      1695

                         ITERACION NUMERO    1 ERROR MAXIMO   9.998670E-01 (RELATIVO Y EN VALOR ABSOLUTO)
                                LA VARIABLE CON ERRMAX ES W(  94)
 NUMERO DE NO CEROS EN LA MATRIZ=      1695

                         ITERACION NUMERO    2 ERROR MAXIMO   1.009234E-03 (RELATIVO Y EN VALOR ABSOLUTO)
                                LA VARIABLE CON ERRMAX ES H(  94)
 NUMERO DE NO CEROS EN LA MATRIZ=      1695

                         ITERACION NUMERO    3 ERROR MAXIMO   1.168180E-05 (RELATIVO Y EN VALOR ABSOLUTO)
                                LA VARIABLE CON ERRMAX ES W(  93)
 NUMERO DE NO CEROS EN LA MATRIZ=      1695

                         ITERACION NUMERO    4 ERROR MAXIMO   3.419020E-07 (RELATIVO Y EN VALOR ABSOLUTO)
                                LA VARIABLE CON ERRMAX ES W(  93)
 NUMERO DE NO CEROS EN LA MATRIZ=      1695

                         ITERACION NUMERO    5 ERROR MAXIMO   9.213489E-09 (RELATIVO Y EN VALOR ABSOLUTO)
                                LA VARIABLE CON ERRMAX ES W(  93)
 NUMERO DE NO CEROS EN LA MATRIZ=      1695

                         ITERACION NUMERO    6 ERROR MAXIMO   2.424383E-10 (RELATIVO Y EN VALOR ABSOLUTO)
                                LA VARIABLE CON ERRMAX ES W(  93)
     EMPRESARIOS AGRUPADOS, A.I.E.                                                                             PAGINA    15
                                                      **********************                           FECHA Mon Dec  6 2010
  GHESA INGENIERIA Y TECNOLOGIA, S.A                  *      HBAL-05       *
                                                      * ================== *
  DEPARTAMENTO DE ANALISIS MECANICOS                  **********************
  ==================================


              Balance original de CERNAVODA(CNN RUMANIA) 700 mw - Pcondensador = 4.23 kPA     


      CORR     CAUDAL         TEMPERATURA        PRESION       VOL ESPECIFICO      ENTALPIA         ENTROPIA          TITULO
       NO     (KGS/SG)            (C)             (BARA)          (M**3/KG)        (KJ/KG)         (KJ/KG/C) 


        1     1044.0000          259.9           46.9000           0.042095         2793.2           5.99527          0.9980
        2     1044.0000          259.9           46.9000           0.042095         2793.2           5.99527          0.9980
        3     1044.0000          259.9           46.9000           0.042095         2793.2           5.99527          0.9980
        4      967.8053          258.1           45.5000           0.043427         2793.2           6.00652          0.9975
        5      966.8817          258.1           45.5000           0.043427         2793.2           6.00652          0.9975
        6      966.3887          258.1           45.5000           0.043427         2793.2           6.00652          0.9975
        7      966.3887          255.3           43.4938           0.045483         2793.2           6.02335          0.9968
        8      966.3887          192.9           13.3610           0.133803         2606.0           6.09475          0.9083
        9      966.2513          192.9           13.3610           0.133822         2606.3           6.09529          0.9084
       10      884.9767          192.9           13.3610           0.133822         2606.3           6.09529          0.9084
       11      884.9767          183.5           10.8595           0.161513         2576.7           6.11070          0.8988
       12      883.9937          183.5           10.8595           0.161513         2576.7           6.11070          0.8988
       13      883.0106          183.5           10.8595           0.161513         2576.7           6.11069          0.8988
       14      883.0106          183.0           10.7395           0.163289         2576.7           6.11496          0.8991
       15      800.1168          183.0           10.7395           0.180089         2763.2           6.52384          0.9922
       16      800.1168          235.9           10.5995           0.212081         2908.8           6.83367          1.0000
       17      800.1168          235.7           10.4795           0.214515         2908.8           6.83870          1.0000
       18      800.1168          151.7            4.3987           0.428298         2752.3           6.88717          1.0000
       19      759.0825          151.7            4.3987           0.428298         2752.3           6.88717          1.0000
       20      759.0825          117.7            1.8438           0.916595         2612.6           6.92383          0.9593
       21      759.0825          117.7            1.8438           0.916595         2612.6           6.92383          0.9593
       22      721.6703          117.7            1.8438           0.916595         2612.6           6.92383          0.9593
       23      721.6703           91.5            0.7412           2.070110         2488.3           6.98308          0.9236
       24      719.1048           91.5            0.7412           2.077492         2495.8           7.00368          0.9268
       25      685.5793           91.5            0.7412           2.077492         2495.8           7.00368          0.9268
       26      685.5793           79.0            0.4545           3.229268         2437.1           7.04530          0.9113
       27      678.4646           79.0            0.4545           3.246533         2448.4           7.07730          0.9162
       28      678.4646           79.0            0.4545           3.246533         2448.4           7.07730          0.9162
       29      678.4646           66.7            0.2701           5.193122         2387.1           7.11637          0.9000
       30      674.2109           66.7            0.2701           5.225880         2400.4           7.15550          0.9057
       31      637.6199           66.7            0.2701           5.225880         2400.4           7.15550          0.9057
       32      637.6199           52.8            0.1417           9.382880         2330.0           7.20948          0.8876
       33      630.0404           52.8            0.1417           9.447942         2344.6           7.25434          0.8937
       34      630.0404           52.8            0.1417           9.447942         2344.6           7.25434          0.8937
       35      630.0404           30.0            0.0423          28.769250         2243.8           7.42452          0.8714
       36      762.4366           30.0            0.0423           0.001004          125.5           0.43586          0.0000
       37      762.4366           29.9            0.5423           0.001004          125.5           0.43569          0.0000
       38      762.4366           30.0            9.7013           0.001004          126.6           0.43645          0.0000
       39      762.4366           30.0            9.2013           0.001004          126.6           0.43662          0.0000
       40      762.4366           30.8            9.1377           0.001004          129.7           0.44679          0.0000
       41      762.4366           30.8            8.6377           0.001004          129.7           0.44695          0.0000
       42      762.4366           62.6            7.6377           0.001018          262.4           0.86257          0.0000
       43      762.4366           62.6            7.1377           0.001018          262.4           0.86272          0.0000
       44      762.4366           87.1            6.1377           0.001034          365.0           1.15792          0.0000
       45      762.4366           87.1            5.6377           0.001034          365.0           1.15806          0.0000
       46      762.4366          113.0            4.6377           0.001054          474.1           1.45094          0.0000
       47      762.4366          113.0            4.1377           0.001054          474.1           1.45108          0.0000
       48      974.7284          144.8            4.1377           0.001085          609.9           1.78898          0.0000
       49      974.7284          144.8            4.6377           0.001085          609.9           1.78885          0.0000
       50      974.7284          145.7           58.8100           0.001082          617.0           1.79174          0.0000
       51      974.7284          145.7           58.3100           0.001082          617.0           1.79187          0.0000
     EMPRESARIOS AGRUPADOS, A.I.E.                                                                             PAGINA    16
                                                      **********************                           FECHA Mon Dec  6 2010
  GHESA INGENIERIA Y TECNOLOGIA, S.A                  *      HBAL-05       *
                                                      * ================== *
  DEPARTAMENTO DE ANALISIS MECANICOS                  **********************
  ==================================


              Balance original de CERNAVODA(CNN RUMANIA) 700 mw - Pcondensador = 4.23 kPA     


      CORR     CAUDAL         TEMPERATURA        PRESION       VOL ESPECIFICO      ENTALPIA         ENTROPIA          TITULO
       NO     (KGS/SG)            (C)             (BARA)          (M**3/KG)        (KJ/KG)         (KJ/KG/C) 


       52      974.7284          187.2           57.3100           0.001133          797.2           2.20226          0.0000
       53      974.7284          187.2           56.8100           0.001133          797.2           2.20238          0.0000
       54       76.1947          258.1           45.5000           0.043427         2793.2           6.00652          0.9975
       55       76.1947          256.2           44.1300           0.044811         2793.2           6.01792          0.9970
       56        0.4931          258.1           45.5000           0.043427         2793.2           6.00652          0.9975
       57        0.1374          192.9           13.3610           0.001146          820.3           2.26300          0.0000
       58       41.0343          151.7            4.3987           0.428298         2752.3           6.88717          1.0000
       59       41.0343          150.7            4.1377           0.455239         2752.3           6.91433          1.0000
       60       37.4122          117.7            1.8438           0.916595         2612.6           6.92383          0.9593
       61       37.4122          117.7            1.8438           0.916594         2612.6           6.92382          0.9593
       62       33.5255           91.5            0.7412           2.077492         2495.8           7.00368          0.9268
       63       36.0910           91.5            0.7412           1.929889         2345.6           6.59181          0.8610
       64        0.0000           79.0            0.4545           3.246533         2448.4           7.07730          0.9162
       65        7.1147           79.0            0.4545           1.582865         1362.8           3.99442          0.4466
       66       36.5910           66.7            0.2701           5.225880         2400.4           7.15550          0.9057
       67       40.8447           66.7            0.2701           4.681743         2179.5           6.50556          0.8113
       68        0.0000           52.8            0.1417           9.447942         2344.6           7.25434          0.8937
       69        7.5795           52.8            0.1417           3.974607         1114.3           3.48004          0.3759
       70      122.5337           36.9            0.2541           0.001007          154.7           0.53103          0.0000
       71      121.4626           36.4            0.2541           0.001006          152.3           0.52350          0.0000
       72       88.6834          151.3           12.5510           0.001092          638.2           1.85393          0.0000
       73       81.4120          191.4           12.9510           0.137777         2603.3           6.10078          0.9077
       74       81.7603          191.4           12.9510           0.137838         2604.1           6.10252          0.9081
       75        0.1447          258.1           45.5000           0.043427         2793.2           6.00652          0.9975
       76        1.1278          183.5           10.8595           0.163946         2604.0           6.17043          0.9124
       77        2.1108          183.5           10.8595           0.162897         2592.2           6.14467          0.9065
       78        2.2017          183.5           10.8595           0.163486         2598.8           6.15915          0.9098
       79        2.4305          183.5           10.8595           0.164665         2612.0           6.18808          0.9164
       80      123.8931           43.4            0.2541           0.001009          181.6           0.61709          0.0000
       81      124.8167           48.0            0.2541           0.001011          201.0           0.67770          0.0000
       82       73.5032           68.2            0.6972           0.001022          285.3           0.93235          0.0000
       83      132.3962           60.5            0.2541           0.001017          253.2           0.83742          0.0000
       84       81.4120          192.9           13.3610           0.133598         2603.3           6.08883          0.9069
       85        0.3483          258.1           45.5000           0.043427         2793.2           6.00652          0.9975
       86       81.2746          192.9           13.3610           0.133822         2606.3           6.09529          0.9084
       87        0.9831          183.5           10.8595           0.161461         2576.1           6.10943          0.8985
       88        0.9831          183.5           10.8595           0.161693         2578.7           6.11512          0.8998
       89       82.8938          183.0           10.7395           0.001132          776.4           2.16839          0.0000
       90       69.2717          256.2           44.1300           0.044811         2793.2           6.01792          0.9970
       91        6.9230          256.2           44.1300           0.044811         2793.2           6.01792          0.9970
       92       69.2717          255.3           43.4680           0.001264         1111.8           2.84199          0.0000
       93       40.9434          150.7            4.1377           0.455239         2752.3           6.91433          1.0000
       94        0.0000          117.7            1.8438           0.001059          493.9           1.50249          0.0000
       95       37.4122          115.8            1.7338           0.972278         2612.6           6.95045          0.9606
       96        2.5655           91.5            0.7412           0.001037          383.1           1.20955          0.0000
       97       36.0910           89.9            0.6972           2.046939         2345.6           6.61584          0.8624
       98        7.1147           79.0            0.4545           1.582863         1362.8           3.99441          0.4466
       99        7.1147           77.3            0.4245           1.695724         1362.8           4.00841          0.4488
      100        0.2288          144.8            4.1377           0.447751         2739.1           6.88295          1.0000
      101        4.2537           66.7            0.2701           0.001021          279.3           0.91472          0.0000
      102       40.8447           65.4            0.2541           4.965529         2179.5           6.52830          0.8126
     EMPRESARIOS AGRUPADOS, A.I.E.                                                                             PAGINA    17
                                                      **********************                           FECHA Mon Dec  6 2010
  GHESA INGENIERIA Y TECNOLOGIA, S.A                  *      HBAL-05       *
                                                      * ================== *
  DEPARTAMENTO DE ANALISIS MECANICOS                  **********************
  ==================================


              Balance original de CERNAVODA(CNN RUMANIA) 700 mw - Pcondensador = 4.23 kPA     


      CORR     CAUDAL         TEMPERATURA        PRESION       VOL ESPECIFICO      ENTALPIA         ENTROPIA          TITULO
       NO     (KGS/SG)            (C)             (BARA)          (M**3/KG)        (KJ/KG)         (KJ/KG/C) 


      103        7.5795           52.8            0.1417           3.974607         1114.3           3.48004          0.3759
      104        7.5795           51.3            0.1317           4.280832         1114.3           3.49272          0.3780
      105        1.0711          183.5           10.8595           0.164665         2612.0           6.18808          0.9164
      106        1.0711          100.0            1.0132           0.001044          419.1           1.30685          0.0000
      107       80.6179           89.9            0.6972           0.005279          380.4           1.20210          0.0018
      108       37.4122           92.7            1.7338           0.001038          388.2           1.22320          0.0000
      109      171.5772          166.7           12.5510           0.001110          705.0           2.00846          0.0000
      110       88.6833          190.0           12.5510           0.143333         2618.8           6.14647          0.9163
      111        1.3594          183.5           10.8595           0.164665         2612.0           6.18808          0.9164
      112        0.0909          150.7            4.1377           0.455239         2752.3           6.91433          1.0000
      113        0.9236          258.1           45.5000           0.043427         2793.2           6.00652          0.9975
      114     1044.0000          191.9           56.8100           0.001140          818.1           2.24748          0.0000
      115        0.0000          259.9           46.9000           0.042095         2793.2           5.99527          0.9980
      116        0.0001          255.3           43.4680           0.001264         1111.8           2.84199          0.0000
      117       88.6833          191.4           12.9510           0.138966         2618.8           6.13430          0.9156
      118       69.2716          255.3           43.4680           0.001264         1111.8           2.84199          0.0000
      119        1.1278          183.5           10.8595           0.163946         2604.0           6.17043          0.9124
      120     1044.0000          258.1           45.5000           0.043427         2793.2           6.00652          0.9975
     EMPRESARIOS AGRUPADOS, A.I.E.                                                                             PAGINA    18
                                                      **********************                           FECHA Mon Dec  6 2010
  GHESA INGENIERIA Y TECNOLOGIA, S.A                  *      HBAL-05       *
                                                      * ================== *
  DEPARTAMENTO DE ANALISIS MECANICOS                  **********************
  ==================================


              Balance original de CERNAVODA(CNN RUMANIA) 700 mw - Pcondensador = 4.23 kPA     





                                        INFORMACION GENERAL DE ELEMENTOS DIVISORES NORMALES


    EQUIPO        FLUJO DE        FLUJO DE        FLUJO DE        FACTOR DE        FACTOR DE        RELACION         RELACION 
                  ENTRADA         SALIDA 1        SALIDA 2
      NO          (KG/SG)         (KG/SG)         (KG/SG)          FLUJO 1          FLUJO 2         PRI/PRINC        SEC/PRINC
    ======       ==========      ==========      ==========      ===========      ===========      ===========      ===========
        2        1044.0000       1044.0000      0.10000000E-05    31.277185       0.29958989E-07    1.0000000       0.95785441E-09
        3        1044.0000       967.80534       76.194664        29.899382        2.3539582       0.92701661       0.72983395E-01
        4        967.80534       966.88174      0.92360000        29.870848       0.28533702E-01   0.99904568       0.95432415E-03
        5        966.88174       966.38868      0.49306000        29.855615       0.15232597E-01   0.99949005       0.50994861E-03
        9        966.25131       884.97671       81.274599        88.567800        8.1339004       0.91588669       0.84113313E-01
       18        800.11678       759.08252       41.034252        236.86500        12.804376       0.94871467       0.51285329E-01
       21        759.08249       721.67030       37.412190        508.82820        26.378219       0.95071393       0.49286067E-01
       24        719.10482       685.57932       33.525497        1147.7510        56.126142       0.95337885       0.46621155E-01
       27        678.46460       678.46459      0.10000000E-04    1813.3730       0.26727600E-04   0.99999999       0.14739162E-07
       30        674.21087       637.61991       36.590958        2804.6120        160.94767       0.94572772       0.54272275E-01
       33        630.04044       630.04044      0.10000000E-06    5144.0570       0.81646457E-06    1.0000000       0.15871997E-09
       55        76.194664       69.271664       6.9230000        2.2074043       0.22060767       0.90914062       0.90859381E-01
       56       0.49306000      0.34834000      0.14472000       0.10761617E-01   0.44709802E-02   0.70648603       0.29351397    
       59        41.034252       40.943352      0.90900000E-01    13.580783       0.30151248E-01   0.99778478       0.22152225E-02
       79        2.4305093       1.3594093       1.0711000       0.16739586       0.13189384       0.55931047       0.44068953    
       86        69.271664       69.271595      0.69271664E-04   0.37353479       0.37353516E-06   0.99999900       0.10000000E-05
     EMPRESARIOS AGRUPADOS, A.I.E.                                                                             PAGINA    19
                                                      **********************                           FECHA Mon Dec  6 2010
  GHESA INGENIERIA Y TECNOLOGIA, S.A                  *      HBAL-05       *
                                                      * ================== *
  DEPARTAMENTO DE ANALISIS MECANICOS                  **********************
  ==================================


              Balance original de CERNAVODA(CNN RUMANIA) 700 mw - Pcondensador = 4.23 kPA     





                                    INFORMACION GENERAL DE TURBINAS DE VAPOR


                                 ENTRADA                       SALIDA
                      ----------------------------  ----------------------------
   EQUIPO    FLUJO    PRESION  TEMPERAT  ENTALPIA   PRESION  TEMPERAT  ENTALPIA  RELACION  FACTOR DE  EFICIENCIA  POTENCIA
     NO     (KGS/SG)   (BARA)    (C)      (KJ/KG)    (BARA)    (C)      (KJ/KG)  PENT/PSAL  FLUJO       (0/0)       (KW)


      7     966.3887  43.4938    255.34   2793.20   13.3610    192.87   2606.03      3.255    31.2510    84.91     180877.0
     10     884.9767  13.3610    192.87   2606.29   10.8595    183.50   2576.68      1.230    88.5678    80.80      26200.4
     17     800.1168  10.4795    235.70   2908.76    4.3987    151.67   2752.35      2.382   114.4750    88.45     125151.0
     19     759.0825   4.3987    151.67   2752.35    1.8438    117.68   2612.62      2.386   236.8650    90.70     106060.9
     22     721.6703   1.8438    117.68   2612.62    0.7412     91.47   2488.25      2.487   508.8282    85.20      89757.5
     25     685.5793   0.7412     91.47   2495.76    0.4545     78.99   2437.13      1.631  1147.7510    80.00      40193.5
     28     678.4646   0.4545     78.99   2448.40    0.2701     66.73   2387.07      1.683  1813.3730    82.20      41610.2
     31     637.6199   0.2701     66.73   2400.37    0.1417     52.83   2329.98      1.906  2804.6120    80.00      44878.6
     34     630.0404   0.1417     52.83   2344.61    0.0423     29.95   2243.76      3.351  5144.0570    66.16      63536.1
                                                                                                                  ---------
                                                                                                                   718265.3
     EMPRESARIOS AGRUPADOS, A.I.E.                                                                             PAGINA    20
                                                      **********************                           FECHA Mon Dec  6 2010
  GHESA INGENIERIA Y TECNOLOGIA, S.A                  *      HBAL-05       *
                                                      * ================== *
  DEPARTAMENTO DE ANALISIS MECANICOS                  **********************
  ==================================


              Balance original de CERNAVODA(CNN RUMANIA) 700 mw - Pcondensador = 4.23 kPA     



                LINEAS DE EXTRACCION DE TURBINA.-DIAGRAMA H-S.
                ==============================================

  2940.    ...............................................................................................................
           .          .          .          .          .          .          .          .          .          .          .
           .          .          .          .          .          .          .          .          .          .          .
           .          .          .          .          .        * .          .          .          .          .          .
           .          .          .          .          .          .          .          .          .          .          .
  2870.    ...............................................................................................................
           .          .          .          .          .          .          .          .          .          .          .
           .          .          .          .          .          .          .          .          .          .          .
           .          .          .          .          .          .          .          .          .          .          .
           .          .          .          .          .          .          .          .          .          .          .
  2800.    ........................*......................................................................................
           .          .     +    .       *  .   *      .          .          .          .          .          .          .
           .          *          .          .         *.          .          .          .          .          .          .
           .          .          .          .          .          .          .          .          .          .          .
           .   *      .          .          .          .     *    +          .          .          .          .          .
  2730.    ........................................................*......................................................
           .          .          .          .          .          .          .          .          .          .          .
           .          .          .          .          .          .       *  .          .          .          .          .
           .          .          .          .          .          .          .  *       .          .          .          .
           .          .          .          .          .          .          .        * .          .          .          .
  2660.    ...............................................................................................................
           .          .          .          .          .          .          .          .    *     .          .          .
           .          .          .          .          .          .          .          .          .          .          .
           .          .          .          .          .          .          .          .          .          .          .
           .          .        + .          .          .          . +        .          .          .          .          .
  2590.    ...............................................................................................................
           .          .         *.          .          .          .          .          .          .          .          .
           .          .          .          .          .          .          .          .          .          .          .
           .          .          .          .          .          .          .          .          .          .          .
           .          .          .          .          .          .          .          .          .          .          .
  2520.    ...............................................................................................................
           .          .          .          .          .          .          .          .          .          .          .
           .          .          .          .          .          .    *     .          .          .          .          .
           .          .          .          .          .          .   *      .          .          .          .          .
           .          .          .          .          .          .          .          .          .          .          .
  2450.    ...............................................................................................................
           .          .          .          .          .          .      **  .          .          .          .          .
           .          .          .          .          .          .          .          .          .          .          .
           .          .          .          .          .          .          .          .          .          .          .
           .          .          .          .          .          .          .*         .          .          .          .
  2380.    .................................................................*.............................................
           .          .          .          .          .          .          .          .          .          .          .
           .          .          .          .          .          .          .          .          .          .          .
           .          .          .          .          .          .          .    *     .          .          .          .
           .          .          .          .          .          .          .  *       .          .          .          .
  2310.    ...............................................................................................................
           .          .          .          .          .          .          .          .          .          .          .
           .          .          .          .          .          .          .          .          .          .          .
           .          .          .          .          .          .          .          .          .          .          .
           .          .          .          .          .          .          .          .          .          .          .
  2240.    ...............................................................................*...............................

        5.62500    5.87500    6.12500    6.37500    6.62500    6.87500    7.12500    7.37500    7.62500    7.87500    8.12500
     EMPRESARIOS AGRUPADOS, A.I.E.                                                                             PAGINA    21
                                                      **********************                           FECHA Mon Dec  6 2010
  GHESA INGENIERIA Y TECNOLOGIA, S.A                  *      HBAL-05       *
                                                      * ================== *
  DEPARTAMENTO DE ANALISIS MECANICOS                  **********************
  ==================================


              Balance original de CERNAVODA(CNN RUMANIA) 700 mw - Pcondensador = 4.23 kPA     





                         INFORMACION GENERAL DE CALENTADORES DE AGUA DE ALIMENTACION

                                               AGUA DE ALIMENTACION
                                     ENTRADA                      SALIDA                             DRENAJE
                         ----------------------------  ---------------------------  -------------------------------------------
   EQUIPO    FLUJO       PRESION  TEMPERAT  ENTALPIA   PRESION  TEMPERAT  ENTALPIA     FLUJO     PRESION  TEMPERAT  ENTALPIA
     NO     (KGS/SG)      (BARA)    (C)     (KJ/KG)     (BARA)    (C)     (KJ/KG)     (KGS/SG)    (BARA)    (C)     (KJ/KG) 


     39     762.4366       9.2013   30.03     126.62     9.1377   30.77     129.70      1.0711     1.0132  100.00     419.06
     41     762.4366       8.6377   30.78     129.70     7.6377   62.56     262.41    121.4626     0.2541   36.38     152.33
     43     762.4366       7.1377   62.57     262.41     6.1377   87.06     364.98     73.5032     0.6972   68.17     285.32
     45     762.4366       5.6377   87.06     364.98     4.6377  112.98     474.13     37.4122     1.7338   92.66     388.23
     47     762.4366       4.1377  112.98     474.13     4.1377  144.85     609.93    974.7284     0.0000    0.00       0.00
     51     974.7284      58.3100  145.69     617.02    57.3100  187.20     797.22     88.6834    12.5510  151.29     638.21



                             VAPOR                                        CASCADA
           ------------------------------------------    ----------------------------------------
   EQUIPO    FLUJO       PRESION  TEMPERAT  ENTALPIA       FLUJO     PRESION  TEMPERAT  ENTALPIA       TTD      DCA
     NO     (KGS/SG)      (BARA)    (C)     (KJ/KG)       (KGS/SG)    (BARA)    (C)     (KJ/KG)        (C)      (C)


     39       1.0711      10.8595  183.50    2612.02        0.0000     0.0000    0.00       0.00      69.231   69.970
     41      40.8447       0.2541   65.36    2179.47       80.6179     0.6972   89.86     380.41       2.800    5.600
     43      36.0910       0.6972   89.86    2345.59       37.4122     1.7338   92.66     388.23       2.800    5.600
     45      37.4122       1.7338  115.78    2612.62        0.0000     0.0000    0.00       0.00       2.800    5.600
     47      40.9434       4.1377  150.68    2752.35      171.5772    12.5510  166.70     704.99       0.000    0.000
     51      88.6833      12.5510  190.00    2618.85        0.0001    43.4680  255.31    1111.75       2.800    5.600
     EMPRESARIOS AGRUPADOS, A.I.E.                                                                             PAGINA    22
                                                      **********************                           FECHA Mon Dec  6 2010
  GHESA INGENIERIA Y TECNOLOGIA, S.A                  *      HBAL-05       *
                                                      * ================== *
  DEPARTAMENTO DE ANALISIS MECANICOS                  **********************
  ==================================


              Balance original de CERNAVODA(CNN RUMANIA) 700 mw - Pcondensador = 4.23 kPA     





                                         INFORMACION GENERAL DE CONDENSADOR PRINCIPAL


                              AGUA DE CIRCULACION
             ------------------------------------------------
    EQUIPO      CAUDAL    VELOCIDAD      TEMP.       TEMP.      PRESION      CALOR    
      NO      (M**3/SG)    (M/SG)      ENT. (C)    SAL. (C)      (MMHG)     ( KW  ) 

      35   *********************** *********** ***********     31.7276    1.35153E+06
     EMPRESARIOS AGRUPADOS, A.I.E.                                                                             PAGINA    23
                                                      **********************                           FECHA Mon Dec  6 2010
  GHESA INGENIERIA Y TECNOLOGIA, S.A                  *      HBAL-05       *
                                                      * ================== *
  DEPARTAMENTO DE ANALISIS MECANICOS                  **********************
  ==================================


              Balance original de CERNAVODA(CNN RUMANIA) 700 mw - Pcondensador = 4.23 kPA     





                                         INFORMACION GENERAL DE BOMBAS


    EQUIPO       CAUDAL TOTAL       PRESION    PRESION   T.D.H.      REND.        POTENCIA         NO. BOMBAS
                   BOMBEADO         ENTRADA    SALIDA                             EN EL EJE        EN PARALELO
      NO      (KGS/SG)   (M**3/HR)  (BARA)     (BARA)      (M)       (0/0)     (KW)      (CV)

      37      762.4366  2756.4878    0.5423     9.7013     93.79     80.00     876.62   1191.87         3
      49      974.7284  3807.7404    4.6377    58.8100    599.43     83.00    6903.42   9386.04         2
     EMPRESARIOS AGRUPADOS, A.I.E.                                                                             PAGINA    24
                                                      **********************                           FECHA Mon Dec  6 2010
  GHESA INGENIERIA Y TECNOLOGIA, S.A                  *      HBAL-05       *
                                                      * ================== *
  DEPARTAMENTO DE ANALISIS MECANICOS                  **********************
  ==================================


              Balance original de CERNAVODA(CNN RUMANIA) 700 mw - Pcondensador = 4.23 kPA     





                                        INFORMACION GENERAL DE SEPARADORES DE HUMEDAD


                            ENTRADA                         SALIDA VAPOR SECO              SALIDA DRENAJE
          -------------------------------------------- ---------------------------- ---------------------------
  EQUIPO    FLUJO    PRESION  TEMPER  ENTALPIA  TITULO    FLUJO    ENTALPIA  TITULO   FLUJO    ENTALPIA  TITULO  EFIC.  ARR.
    NO      (KG/S)   (BAR A.)  (C)    (KJ/KG)             (KG/S)   (KJ/KG)            (KG/S)   (KJ/KG)           (0/0) (0/0)

     8     966.3887    13.36  192.87   2606.03   0.908   966.2513   2606.29   0.908    0.1374    820.35   0.000   0.15  0.00
    14     883.0106    10.74  183.01   2576.68   0.899   800.1168   2763.19   0.992   82.8938    776.43   0.000  93.00  0.00
    20     759.0825     1.84  117.68   2612.62   0.959   759.0825   2612.62   0.959    0.0000    493.87   0.000   0.00  0.00
    23     721.6703     0.74   91.47   2488.25   0.924   719.1048   2495.76   0.927    2.5655    383.14   0.000   4.65  0.00
    26     685.5793     0.45   78.99   2437.13   0.911   678.4646   2448.40   0.916    7.1147   1362.83   0.447   6.00  0.51
    29     678.4646     0.27   66.73   2387.07   0.900   674.2109   2400.37   0.906    4.2537    279.28   0.000   6.27  0.00
    32     637.6199     0.14   52.83   2329.98   0.888   630.0404   2344.61   0.894    7.5795   1114.28   0.376   6.13  0.50
     EMPRESARIOS AGRUPADOS, A.I.E.                                                                             PAGINA    25
                                                      **********************                           FECHA Mon Dec  6 2010
  GHESA INGENIERIA Y TECNOLOGIA, S.A                  *      HBAL-05       *
                                                      * ================== *
  DEPARTAMENTO DE ANALISIS MECANICOS                  **********************
  ==================================


              Balance original de CERNAVODA(CNN RUMANIA) 700 mw - Pcondensador = 4.23 kPA     





                                                INFORMACION GENERAL DE RECALENTADORES


                                                         VAPOR A RECALENTAR


                                ENTRADA                        SALIDA
                      ---------------------------   ---------------------------
   EQUIPO    FLUJO    PRESION  TEMPERAT  ENTALPIA   PRESION  TEMPERAT  ENTALPIA   CALOR ABSORBIDO   EFICIENCIA   LMTD   TTD
     NO     (KG/SG)    (BARA)    (C)      (KJ/KG)    (BARA)    (C)      (KJ/KG)         (KW)           (0/0)       C     C

     15    800.1168    10.740   183.01    2763.19    10.600   235.92    2908.76       116477.         100.00    40.94  20.30



                                                         VAPOR QUE RECALIENTA


                                ENTRADA                        SALIDA
                      ---------------------------   ---------------------------
   EQUIPO    FLUJO    PRESION  TEMPERAT  ENTALPIA   PRESION  TEMPERAT  ENTALPIA   CALOR CEDIDO  FACTORES DE TRANSFERENCIA
     NO     (KG/SG)    (BARA)    (C)      (KJ/KG)    (BARA)    (C)      (KJ/KG)       (KW)           UA          U

     15     69.2717    44.130   256.22    2793.20    43.468   255.31    1111.75    116477.       2845.        2845.    
     EMPRESARIOS AGRUPADOS, A.I.E.                                                                             PAGINA    26
                                                      **********************                           FECHA Mon Dec  6 2010
  GHESA INGENIERIA Y TECNOLOGIA, S.A                  *      HBAL-05       *
                                                      * ================== *
  DEPARTAMENTO DE ANALISIS MECANICOS                  **********************
  ==================================


              Balance original de CERNAVODA(CNN RUMANIA) 700 mw - Pcondensador = 4.23 kPA     


                                    INFORMACION GENERAL DE CALDERAS DE VAPOR


                                 ENTRADA                       SALIDA
                      ----------------------------  ----------------------------
   EQUIPO    FLUJO    PRESION  TEMPERAT  ENTALPIA   PRESION  TEMPERAT  ENTALPIA   EFICIENCIA  POTENCIA
     NO      (KG/S)   (BAR A.)   (C)      (KJ/KG)   (BAR A.)   (C)      (KJ/KG)     (0/0)       (KW)

     53    1044.0000  56.8100    191.92    818.09   46.9000    259.94   2793.20    100.000   2062015.0    
     EMPRESARIOS AGRUPADOS, A.I.E.                                                                             PAGINA    27
                                                      **********************                           FECHA Mon Dec  6 2010
  GHESA INGENIERIA Y TECNOLOGIA, S.A                  *      HBAL-05       *
                                                      * ================== *
  DEPARTAMENTO DE ANALISIS MECANICOS                  **********************
  ==================================


              Balance original de CERNAVODA(CNN RUMANIA) 700 mw - Pcondensador = 4.23 kPA     


