     EMPRESARIOS AGRUPADOS, A.I.E.                                                                             PAGINA     1
                                                      **********************                           FECHA Mon Dec  6 2010
  GHESA INGENIERIA Y TECNOLOGIA, S.A                  *      HBAL-05       *
                                                      * ================== *
  DEPARTAMENTO DE ANALISIS MECANICOS                  **********************
  ==================================


               ESTUDIO DE ESCALON DE TURBINA Y CALENTADOR AL QUE SUMINISTRA VAPOR             


         1         1         1         0         2         0    1        
  0.00000E+00  1.31376E+01  2.83060E+03  0.00000E+00  0.00000E+00  1.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00
         2        10         3         0        13         0    2        
  8.84600E-01  6.36000E+00  8.94887E+01  0.00000E+00  1.00000E+00  0.00000E+00  0.00000E+00  4.84000E-01  0.00000E+00
         3         2        13         0         5         4    3        
  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00
         4         1         8         0        11         0    7        
  1.20000E+03  3.17488E+01  5.15790E+02  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00
         5         3         5         0         6         0    0        
  0.00000E+00  0.00000E+00  0.00000E+00  5.00000E-02  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00
         6         7        11        15         9        12    5        
  0.00000E+00  0.00000E+00  8.56100E-07  6.59400E+00  4.16600E+00  1.00000E+00  0.00000E+00  0.00000E+00  1.00000E+01
         7         1         7         0        10         0    6        
  3.34664E+02  1.05800E+01  6.74070E+02  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00
         8        13         2         0         3        14    0        
  2.00000E-01  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00
         9         5         6        14        15         0    0        
  7.55160E+00  6.69000E+04  1.31376E+00  0.00000E+00  2.98560E+00  0.00000E+00  0.00000E+00  1.00000E+00  0.00000E+00
     EMPRESARIOS AGRUPADOS, A.I.E.                                                                             PAGINA     2
                                                      **********************                           FECHA Mon Dec  6 2010
  GHESA INGENIERIA Y TECNOLOGIA, S.A                  *      HBAL-05       *
                                                      * ================== *
  DEPARTAMENTO DE ANALISIS MECANICOS                  **********************
  ==================================


               ESTUDIO DE ESCALON DE TURBINA Y CALENTADOR AL QUE SUMINISTRA VAPOR             



          LA CORRIENTE     1 ENTRA AL EQUIPO     1,
          LA CORRIENTE     2 SALE DEL EQUIPO     1 Y ENTRA AL EQUIPO     8
          LA CORRIENTE     3 SALE DEL EQUIPO     8 Y ENTRA AL EQUIPO     2

          LA CORRIENTE     4 SALE DEL EQUIPO     3,
          LA CORRIENTE     5 SALE DEL EQUIPO     3 Y ENTRA AL EQUIPO     5
          LA CORRIENTE     6 SALE DEL EQUIPO     5 Y ENTRA AL EQUIPO     9

          LA CORRIENTE     7 ENTRA AL EQUIPO     7,

          LA CORRIENTE     8 ENTRA AL EQUIPO     4,

          LA CORRIENTE     9 SALE DEL EQUIPO     6,
          LA CORRIENTE    10 SALE DEL EQUIPO     7 Y ENTRA AL EQUIPO     6
          LA CORRIENTE    11 SALE DEL EQUIPO     4 Y ENTRA AL EQUIPO     6

          LA CORRIENTE    12 SALE DEL EQUIPO     6,
          LA CORRIENTE    13 SALE DEL EQUIPO     2 Y ENTRA AL EQUIPO     3
          LA CORRIENTE    14 SALE DEL EQUIPO     8 Y ENTRA AL EQUIPO     9
          LA CORRIENTE    15 SALE DEL EQUIPO     9 Y ENTRA AL EQUIPO     6
     EMPRESARIOS AGRUPADOS, A.I.E.                                                                             PAGINA     3
                                                      **********************                           FECHA Mon Dec  6 2010
  GHESA INGENIERIA Y TECNOLOGIA, S.A                  *      HBAL-05       *
                                                      * ================== *
  DEPARTAMENTO DE ANALISIS MECANICOS                  **********************
  ==================================


               ESTUDIO DE ESCALON DE TURBINA Y CALENTADOR AL QUE SUMINISTRA VAPOR             


          LA CORRIENTE     1 NO SALE DE NINGUN EQUIPO
            NO OBSTANTE LA CONFIGURACION PUEDE SER VALIDA

          LA CORRIENTE     4 NO ENTRA A NINGUN EQUIPO
            NO OBSTANTE LA CONFIGURACION PUEDE SER VALIDA

          LA CORRIENTE     7 NO SALE DE NINGUN EQUIPO
            NO OBSTANTE LA CONFIGURACION PUEDE SER VALIDA

          LA CORRIENTE     8 NO SALE DE NINGUN EQUIPO
            NO OBSTANTE LA CONFIGURACION PUEDE SER VALIDA

          LA CORRIENTE     9 NO ENTRA A NINGUN EQUIPO
            NO OBSTANTE LA CONFIGURACION PUEDE SER VALIDA

          LA CORRIENTE    12 NO ENTRA A NINGUN EQUIPO
            NO OBSTANTE LA CONFIGURACION PUEDE SER VALIDA

     EMPRESARIOS AGRUPADOS, A.I.E.                                                                             PAGINA     4
                                                      **********************                           FECHA Mon Dec  6 2010
  GHESA INGENIERIA Y TECNOLOGIA, S.A                  *      HBAL-05       *
                                                      * ================== *
  DEPARTAMENTO DE ANALISIS MECANICOS                  **********************
  ==================================


               ESTUDIO DE ESCALON DE TURBINA Y CALENTADOR AL QUE SUMINISTRA VAPOR             


 EL EQUIPO       1 GENERA LAS ECUACIONES     1 --     5
 EL EQUIPO       2 GENERA LAS ECUACIONES     6 --     9
 EL EQUIPO       3 GENERA LAS ECUACIONES    10 --    14
 EL EQUIPO       4 GENERA LAS ECUACIONES    15 --    20
 EL EQUIPO       5 GENERA LAS ECUACIONES    21 --    23
 EL EQUIPO       6 GENERA LAS ECUACIONES    24 --    30
 EL EQUIPO       7 GENERA LAS ECUACIONES    31 --    36
 EL EQUIPO       8 GENERA LAS ECUACIONES    37 --    42
 EL EQUIPO       9 GENERA LAS ECUACIONES    43 --    45
     EMPRESARIOS AGRUPADOS, A.I.E.                                                                             PAGINA     5
                                                      **********************                           FECHA Mon Dec  6 2010
  GHESA INGENIERIA Y TECNOLOGIA, S.A                  *      HBAL-05       *
                                                      * ================== *
  DEPARTAMENTO DE ANALISIS MECANICOS                  **********************
  ==================================


               ESTUDIO DE ESCALON DE TURBINA Y CALENTADOR AL QUE SUMINISTRA VAPOR             


 CORRIENTE NUMERO     1 --------  7.55166690E+02 1.31376000E+01 2.83060000E+03
 CORRIENTE NUMERO     2 --------  7.55166700E+02 1.31376000E+01 2.83060000E+03
 CORRIENTE NUMERO     3 --------  7.55166690E+02 6.36000000E+00 2.84228310E+03
 CORRIENTE NUMERO     4 --------  7.03255990E+02 6.36000000E+00 2.84228310E+03
 CORRIENTE NUMERO     5 --------  5.19107080E+01 6.36000000E+00 2.84228310E+03
 CORRIENTE NUMERO     6 --------  5.19107080E+01 6.04199992E+00 2.84228310E+03
 CORRIENTE NUMERO     7 --------  3.34664000E+02 1.05800000E+01 6.74070000E+02
 CORRIENTE NUMERO     8 --------  1.20000000E+03 3.17488000E+01 5.15790000E+02
 CORRIENTE NUMERO     9 --------  1.10542200E+03 3.07026820E+01 6.63771530E+02
 CORRIENTE NUMERO    10 --------  3.34664000E+02 1.05800000E+01 6.74070000E+02
 CORRIENTE NUMERO    11 --------  1.20000000E+03 3.17488000E+01 5.15790000E+02
 CORRIENTE NUMERO    12 --------  3.86574709E+02 6.04199992E+00 5.43949960E+02
 CORRIENTE NUMERO    13 --------  7.55166698E+02 6.36000000E+00 2.84228310E+03
 CORRIENTE NUMERO    14 --------  1.00000000E-05 1.31376000E+01 8.16865937E+02
 CORRIENTE NUMERO    15 --------  5.19107090E+01 6.04199992E+00 2.84228251E+03
     EMPRESARIOS AGRUPADOS, A.I.E.                                                                             PAGINA     6
                                                      **********************                           FECHA Mon Dec  6 2010
  GHESA INGENIERIA Y TECNOLOGIA, S.A                  *      HBAL-05       *
                                                      * ================== *
  DEPARTAMENTO DE ANALISIS MECANICOS                  **********************
  ==================================


               ESTUDIO DE ESCALON DE TURBINA Y CALENTADOR AL QUE SUMINISTRA VAPOR             


 NUMERO DE NO CEROS EN LA MATRIZ=       107

                         ITERACION NUMERO    1 ERROR MAXIMO   7.314418E+01 (RELATIVO Y EN VALOR ABSOLUTO)
                                LA VARIABLE CON ERRMAX ES W(  14)
 NUMERO DE NO CEROS EN LA MATRIZ=       107

                         ITERACION NUMERO    2 ERROR MAXIMO   2.842902E-02 (RELATIVO Y EN VALOR ABSOLUTO)
                                LA VARIABLE CON ERRMAX ES H(  15)
 NUMERO DE NO CEROS EN LA MATRIZ=       107

                         ITERACION NUMERO    3 ERROR MAXIMO   2.938297E-04 (RELATIVO Y EN VALOR ABSOLUTO)
                                LA VARIABLE CON ERRMAX ES W(   5)
 NUMERO DE NO CEROS EN LA MATRIZ=       107

                         ITERACION NUMERO    4 ERROR MAXIMO   2.926360E-11 (RELATIVO Y EN VALOR ABSOLUTO)
                                LA VARIABLE CON ERRMAX ES H(  15)
     EMPRESARIOS AGRUPADOS, A.I.E.                                                                             PAGINA     7
                                                      **********************                           FECHA Mon Dec  6 2010
  GHESA INGENIERIA Y TECNOLOGIA, S.A                  *      HBAL-05       *
                                                      * ================== *
  DEPARTAMENTO DE ANALISIS MECANICOS                  **********************
  ==================================


               ESTUDIO DE ESCALON DE TURBINA Y CALENTADOR AL QUE SUMINISTRA VAPOR             


      CORR     CAUDAL         TEMPERATURA        PRESION       VOL ESPECIFICO      ENTALPIA         ENTROPIA          TITULO
       NO     (KGS/SG)            (C)             (BARA)          (M**3/KG)        (KJ/KG)         (KJ/KG/C) 


        1      817.6270          209.0           13.1376           0.157387         2830.6           6.58222          1.0000
        2      817.6270          209.0           13.1376           0.157387         2830.6           6.58222          1.0000
        3      817.6262          209.0           13.1376           0.157387         2830.6           6.58222          1.0000
        4      739.4456          161.1            6.3600           0.291431         2708.1           6.62291          0.9760
        5       78.1805          161.1            6.3600           0.291431         2708.1           6.62291          0.9760
        6       78.1805          159.1            6.0420           0.306255         2708.1           6.64483          0.9771
        7      334.6640          159.6           10.5800           0.001101          674.1           1.93810          0.0000
        8     1200.0000          122.4           31.7488           0.001061          515.8           1.55019          0.0000
        9     1200.0000          163.9           30.5160           0.001105          693.7           1.97817          0.0000
       10      334.6640          159.6           10.5800           0.001101          674.1           1.93810          0.0000
       11     1200.0000          122.4           31.7488           0.001061          515.8           1.55019          0.0000
       12      412.8454          128.9            7.5516           0.001069          542.1           1.62275          0.0000
       13      817.6262          161.1            6.3600           0.291431         2708.1           6.62291          0.9760
       14        0.0008          209.0           13.1376           0.157387         2830.6           6.58222          1.0000
       15       78.1814          168.0            7.5516           0.246755         2708.1           6.54999          0.9722
     EMPRESARIOS AGRUPADOS, A.I.E.                                                                             PAGINA     8
                                                      **********************                           FECHA Mon Dec  6 2010
  GHESA INGENIERIA Y TECNOLOGIA, S.A                  *      HBAL-05       *
                                                      * ================== *
  DEPARTAMENTO DE ANALISIS MECANICOS                  **********************
  ==================================


               ESTUDIO DE ESCALON DE TURBINA Y CALENTADOR AL QUE SUMINISTRA VAPOR             





                                        INFORMACION GENERAL DE ELEMENTOS DIVISORES NORMALES


    EQUIPO        FLUJO DE        FLUJO DE        FLUJO DE        FACTOR DE        FACTOR DE        RELACION         RELACION 
                  ENTRADA         SALIDA 1        SALIDA 2
      NO          (KG/SG)         (KG/SG)         (KG/SG)          FLUJO 1          FLUJO 2         PRI/PRINC        SEC/PRINC
    ======       ==========      ==========      ==========      ===========      ===========      ===========      ===========
        3        817.62617       78.180542       739.44562        16.735464        158.28703       0.95618934E-01   0.90438107    
     EMPRESARIOS AGRUPADOS, A.I.E.                                                                             PAGINA     9
                                                      **********************                           FECHA Mon Dec  6 2010
  GHESA INGENIERIA Y TECNOLOGIA, S.A                  *      HBAL-05       *
                                                      * ================== *
  DEPARTAMENTO DE ANALISIS MECANICOS                  **********************
  ==================================


               ESTUDIO DE ESCALON DE TURBINA Y CALENTADOR AL QUE SUMINISTRA VAPOR             





                                    INFORMACION GENERAL DE TURBINAS DE VAPOR


                                 ENTRADA                       SALIDA
                      ----------------------------  ----------------------------
   EQUIPO    FLUJO    PRESION  TEMPERAT  ENTALPIA   PRESION  TEMPERAT  ENTALPIA  RELACION  FACTOR DE  EFICIENCIA  POTENCIA
     NO     (KGS/SG)   (BARA)    (C)      (KJ/KG)    (BARA)    (C)      (KJ/KG)  PENT/PSAL  FLUJO       (0/0)       (KW)


      2     817.6262  13.1376    208.97   2830.60    6.3600    161.13   2708.06      2.066    89.4914    87.40     100193.5
                                                                                                                  ---------
                                                                                                                   100193.5
     EMPRESARIOS AGRUPADOS, A.I.E.                                                                             PAGINA    10
                                                      **********************                           FECHA Mon Dec  6 2010
  GHESA INGENIERIA Y TECNOLOGIA, S.A                  *      HBAL-05       *
                                                      * ================== *
  DEPARTAMENTO DE ANALISIS MECANICOS                  **********************
  ==================================


               ESTUDIO DE ESCALON DE TURBINA Y CALENTADOR AL QUE SUMINISTRA VAPOR             



                LINEAS DE EXTRACCION DE TURBINA.-DIAGRAMA H-S.
                ==============================================

  2855.    ...............................................................................................................
           .          .          .          .          .          .          .          .          .          .          .
           .          .          .          .          .          .          .          .          .          .          .
           .          .          .          .          .          .          .          .          .          .          .
           .          .          .          .          .          .          .          .          .          .          .
  2840.    ...............................................................................................................
           .          .          .          .          .          .          .          .          .          .          .
           .          .          .          .          .          .          .          .          .          .          .
           .          .          .          .          .          .          .          .          .          .          .
           .          .          .          .          .          .          .   *      .          .          .          .
  2825.    ...............................................................................................................
           .          .          .          .          .          .          .          .          .          .          .
           .          .          .          .          .          .          .          .          .          .          .
           .          .          .          .          .          .          .          .          .          .          .
           .          .          .          .          .          .          .          .          .          .          .
  2810.    ...............................................................................................................
           .          .          .          .          .          .          .          .          .          .          .
           .          .          .          .          .          .          .          .          .          .          .
           .          .          .          .          .          .          .          .          .          .          .
           .*       * .          .          .          .          .          .          .          .          .          .
  2795.    ................*..............................................................................................
           .          .          . *       *.          .          .          .          .          .          .          .
           .          .          .          .     *    .          .          .          .          .          .          .
           .          .          .          .          .  *       .          .          .          .          .          .
           .          .          .          .          .          *          .          .          .          .          .
  2780.    ...............................................................................................................
           .          .          .          .          .          .       *  .          .          .          .          .
           .          .          .          .          .          .          .   *      .          .          .          .
           .          .          .          .          .          .          .          .*         .          .          .
           .          .          .          .          .          .          .          .        * .          .          .
  2765.    ...............................................................................................................
           .          .          .          .          .          .          .          .          .    *     .          .
           .          .          .          .          .          .          .          .          .          .          .
           .          .          .          .          .          .          .          .          .          .          .
           .          .          .          .          .          .          .          .          .          .          .
  2750.    ...............................................................................................................
           .          .          .          .          .          .          .          .          .          .          .
           .          .          .          .          .          .          .          .          .          .          .
           .          .          .          .          .          .          .          .          .          .          .
           .          .          .          .          .          .          .          .          .          .          .
  2735.    ...............................................................................................................
           .          .          .          .          .          .          .          .          .          .          .
           .          .          .          .          .          .          .          .          .          .          .
           .          .          .          .          .          .          .          .          .          .          .
           .          .          .          .          .          .          .          .          .          .          .
  2720.    ...............................................................................................................
           .          .          .          .          .          .          .          .          .          .          .
           .          .          .          .          .          .          .          .          .          .          .
           .          .          .          .          .          .          .          .          .          .          .
           .          .          .          .          .          .          .          . *        .          .          .
  2705.    ...............................................................................................................

        6.26250    6.31250    6.36250    6.41250    6.46250    6.51250    6.56250    6.61250    6.66250    6.71250    6.76250
     EMPRESARIOS AGRUPADOS, A.I.E.                                                                             PAGINA    11
                                                      **********************                           FECHA Mon Dec  6 2010
  GHESA INGENIERIA Y TECNOLOGIA, S.A                  *      HBAL-05       *
                                                      * ================== *
  DEPARTAMENTO DE ANALISIS MECANICOS                  **********************
  ==================================


               ESTUDIO DE ESCALON DE TURBINA Y CALENTADOR AL QUE SUMINISTRA VAPOR             





                         INFORMACION GENERAL DE CALENTADORES DE AGUA DE ALIMENTACION

                                               AGUA DE ALIMENTACION
                                     ENTRADA                      SALIDA                             DRENAJE
                         ----------------------------  ---------------------------  -------------------------------------------
   EQUIPO    FLUJO       PRESION  TEMPERAT  ENTALPIA   PRESION  TEMPERAT  ENTALPIA     FLUJO     PRESION  TEMPERAT  ENTALPIA
     NO     (KGS/SG)      (BARA)    (C)     (KJ/KG)     (BARA)    (C)     (KJ/KG)     (KGS/SG)    (BARA)    (C)     (KJ/KG) 


      6    1200.0000      31.7488  122.35     515.79    30.5160  163.87     693.69    412.8454     7.5516  128.95     542.15



                             VAPOR                                        CASCADA
           ------------------------------------------    ----------------------------------------
   EQUIPO    FLUJO       PRESION  TEMPERAT  ENTALPIA       FLUJO     PRESION  TEMPERAT  ENTALPIA       TTD      DCA
     NO     (KGS/SG)      (BARA)    (C)     (KJ/KG)       (KGS/SG)    (BARA)    (C)     (KJ/KG)        (C)      (C)


      6      78.1814       7.5516  168.04    2708.06      334.6640    10.5800  159.62     674.07       4.166    6.594
     EMPRESARIOS AGRUPADOS, A.I.E.                                                                             PAGINA    12
                                                      **********************                           FECHA Mon Dec  6 2010
  GHESA INGENIERIA Y TECNOLOGIA, S.A                  *      HBAL-05       *
                                                      * ================== *
  DEPARTAMENTO DE ANALISIS MECANICOS                  **********************
  ==================================


               ESTUDIO DE ESCALON DE TURBINA Y CALENTADOR AL QUE SUMINISTRA VAPOR             





                                        INFORMACION GENERAL DE SEPARADORES DE HUMEDAD


                            ENTRADA                         SALIDA VAPOR SECO              SALIDA DRENAJE
          -------------------------------------------- ---------------------------- ---------------------------
  EQUIPO    FLUJO    PRESION  TEMPER  ENTALPIA  TITULO    FLUJO    ENTALPIA  TITULO   FLUJO    ENTALPIA  TITULO  EFIC.  ARR.
    NO      (KG/S)   (BAR A.)  (C)    (KJ/KG)             (KG/S)   (KJ/KG)            (KG/S)   (KJ/KG)           (0/0) (0/0)

     8     817.6270    13.14  208.97   2830.60   1.000   817.6262   2830.60   1.000    0.0008   2830.60   1.000  20.00  0.00
     EMPRESARIOS AGRUPADOS, A.I.E.                                                                             PAGINA    13
                                                      **********************                           FECHA Mon Dec  6 2010
  GHESA INGENIERIA Y TECNOLOGIA, S.A                  *      HBAL-05       *
                                                      * ================== *
  DEPARTAMENTO DE ANALISIS MECANICOS                  **********************
  ==================================


               ESTUDIO DE ESCALON DE TURBINA Y CALENTADOR AL QUE SUMINISTRA VAPOR             


