     EMPRESARIOS AGRUPADOS, A.I.E.                                                                             PAGINA     1
                                                      **********************                           FECHA Mon Feb 14 2011
  GHESA INGENIERIA Y TECNOLOGIA, S.A                  * HBAL-06/ASME-1967  *
                                                      * ================== *
    DEPARTAMENTO MECANICA APLICADA                    **********************
  ==================================


              auxiliar                                                                        


         1         1         1         0         2         0    0        
  3.01944E+01  1.20000E+02  2.67400E+03  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00
         2         6         2         0         3         0    0        
  0.00000E+00  0.00000E+00  0.00000E+00 -1.15000E+02 -5.29700E+02  0.00000E+00  8.00000E-01  1.00000E+00  0.00000E+00
     EMPRESARIOS AGRUPADOS, A.I.E.                                                                             PAGINA     2
                                                      **********************                           FECHA Mon Feb 14 2011
  GHESA INGENIERIA Y TECNOLOGIA, S.A                  * HBAL-06/ASME-1967  *
                                                      * ================== *
    DEPARTAMENTO MECANICA APLICADA                    **********************
  ==================================


              auxiliar                                                                        



          LA CORRIENTE     1 ENTRA AL EQUIPO     1,
          LA CORRIENTE     2 SALE DEL EQUIPO     1 Y ENTRA AL EQUIPO     2

          LA CORRIENTE     3 SALE DEL EQUIPO     2,
     EMPRESARIOS AGRUPADOS, A.I.E.                                                                             PAGINA     3
                                                      **********************                           FECHA Mon Feb 14 2011
  GHESA INGENIERIA Y TECNOLOGIA, S.A                  * HBAL-06/ASME-1967  *
                                                      * ================== *
    DEPARTAMENTO MECANICA APLICADA                    **********************
  ==================================


              auxiliar                                                                        


          LA CORRIENTE     1 NO SALE DE NINGUN EQUIPO
            NO OBSTANTE LA CONFIGURACION PUEDE SER VALIDA

          LA CORRIENTE     3 NO ENTRA A NINGUN EQUIPO
            NO OBSTANTE LA CONFIGURACION PUEDE SER VALIDA

     EMPRESARIOS AGRUPADOS, A.I.E.                                                                             PAGINA     4
                                                      **********************                           FECHA Mon Feb 14 2011
  GHESA INGENIERIA Y TECNOLOGIA, S.A                  * HBAL-06/ASME-1967  *
                                                      * ================== *
    DEPARTAMENTO MECANICA APLICADA                    **********************
  ==================================


              auxiliar                                                                        


 EL EQUIPO       1 GENERA LAS ECUACIONES     1 --     6
 EL EQUIPO       2 GENERA LAS ECUACIONES     7 --     9
     EMPRESARIOS AGRUPADOS, A.I.E.                                                                             PAGINA     5
                                                      **********************                           FECHA Mon Feb 14 2011
  GHESA INGENIERIA Y TECNOLOGIA, S.A                  * HBAL-06/ASME-1967  *
                                                      * ================== *
    DEPARTAMENTO MECANICA APLICADA                    **********************
  ==================================


              auxiliar                                                                        


 CORRIENTE NUMERO     1 --------  3.32500000E+01 1.20000000E+02 5.66000000E+02
 CORRIENTE NUMERO     2 --------  3.32500000E+01 1.20000000E+02 5.66000000E+02
 CORRIENTE NUMERO     3 --------  3.32500000E+01 1.15000000E+02 3.43300000E+03
     EMPRESARIOS AGRUPADOS, A.I.E.                                                                             PAGINA     6
                                                      **********************                           FECHA Mon Feb 14 2011
  GHESA INGENIERIA Y TECNOLOGIA, S.A                  * HBAL-06/ASME-1967  *
                                                      * ================== *
    DEPARTAMENTO MECANICA APLICADA                    **********************
  ==================================


              auxiliar                                                                        


 NUMERO DE NO CEROS EN LA MATRIZ=        14

                         ITERACION NUMERO    1 ERROR MAXIMO   3.724382E+00 (RELATIVO Y EN VALOR ABSOLUTO)
                                LA VARIABLE CON ERRMAX ES H(   1)
 NUMERO DE NO CEROS EN LA MATRIZ=        14

                         ITERACION NUMERO    2 ERROR MAXIMO   1.573561E+00 (RELATIVO Y EN VALOR ABSOLUTO)
                                LA VARIABLE CON ERRMAX ES H(   1)
 NUMERO DE NO CEROS EN LA MATRIZ=        14

                         ITERACION NUMERO    3 ERROR MAXIMO   4.217571E-01 (RELATIVO Y EN VALOR ABSOLUTO)
                                LA VARIABLE CON ERRMAX ES H(   1)
 NUMERO DE NO CEROS EN LA MATRIZ=        14

                         ITERACION NUMERO    4 ERROR MAXIMO   2.857294E-02 (RELATIVO Y EN VALOR ABSOLUTO)
                                LA VARIABLE CON ERRMAX ES H(   1)
 NUMERO DE NO CEROS EN LA MATRIZ=        14

                         ITERACION NUMERO    5 ERROR MAXIMO   2.231592E-03 (RELATIVO Y EN VALOR ABSOLUTO)
                                LA VARIABLE CON ERRMAX ES H(   1)
 NUMERO DE NO CEROS EN LA MATRIZ=        14

                         ITERACION NUMERO    6 ERROR MAXIMO   3.116130E-04 (RELATIVO Y EN VALOR ABSOLUTO)
                                LA VARIABLE CON ERRMAX ES H(   1)
 NUMERO DE NO CEROS EN LA MATRIZ=        14

                         ITERACION NUMERO    7 ERROR MAXIMO   1.487907E-05 (RELATIVO Y EN VALOR ABSOLUTO)
                                LA VARIABLE CON ERRMAX ES H(   1)
 NUMERO DE NO CEROS EN LA MATRIZ=        14

                         ITERACION NUMERO    8 ERROR MAXIMO   2.401349E-06 (RELATIVO Y EN VALOR ABSOLUTO)
                                LA VARIABLE CON ERRMAX ES H(   1)
 NUMERO DE NO CEROS EN LA MATRIZ=        14

                         ITERACION NUMERO    9 ERROR MAXIMO   4.730574E-08 (RELATIVO Y EN VALOR ABSOLUTO)
                                LA VARIABLE CON ERRMAX ES H(   1)
     EMPRESARIOS AGRUPADOS, A.I.E.                                                                             PAGINA     7
                                                      **********************                           FECHA Mon Feb 14 2011
  GHESA INGENIERIA Y TECNOLOGIA, S.A                  * HBAL-06/ASME-1967  *
                                                      * ================== *
    DEPARTAMENTO MECANICA APLICADA                    **********************
  ==================================


              auxiliar                                                                        


      CORR     CAUDAL         TEMPERATURA        PRESION       VOL ESPECIFICO      ENTALPIA         ENTROPIA          TITULO
       NO     (KGS/SG)            (C)             (BARA)          (M**3/KG)        (KJ/KG)         (KJ/KG/C) 


        1       30.1944          324.6          120.0000           0.014122         2674.0           5.47485          0.9873
        2       30.1944          324.6          120.0000           0.014122         2674.0           5.47485          0.9873
        3       30.1944          529.7          115.0000           0.029618         3433.0           6.61430          1.0000
     EMPRESARIOS AGRUPADOS, A.I.E.                                                                             PAGINA     8
                                                      **********************                           FECHA Mon Feb 14 2011
  GHESA INGENIERIA Y TECNOLOGIA, S.A                  * HBAL-06/ASME-1967  *
                                                      * ================== *
    DEPARTAMENTO MECANICA APLICADA                    **********************
  ==================================


              auxiliar                                                                        







