     EMPRESARIOS AGRUPADOS, A.I.E.                                                                             PAGINA     1
                                                      **********************                           FECHA Sun Oct 23 2011
  GHESA INGENIERIA Y TECNOLOGIA, S.A                  * HBAL-06/ASME-1967  *
                                                      * ================== *
    DEPARTAMENTO MECANICA APLICADA                    **********************
  ==================================


              auxiliar                                                                        


         1         1         1         0         2         0    0        
  3.01944E+01  1.20000E+02  2.67400E+03  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00
         2         6         2         0         3         0    0        
  0.00000E+00  0.00000E+00  0.00000E+00 -1.15000E+02  3.43300E+03  0.00000E+00  8.00000E-01  0.00000E+00  0.00000E+00
     EMPRESARIOS AGRUPADOS, A.I.E.                                                                             PAGINA     2
                                                      **********************                           FECHA Sun Oct 23 2011
  GHESA INGENIERIA Y TECNOLOGIA, S.A                  * HBAL-06/ASME-1967  *
                                                      * ================== *
    DEPARTAMENTO MECANICA APLICADA                    **********************
  ==================================


              auxiliar                                                                        



          LA CORRIENTE     1 ENTRA AL EQUIPO     1,
          LA CORRIENTE     2 SALE DEL EQUIPO     1 Y ENTRA AL EQUIPO     2

          LA CORRIENTE     3 SALE DEL EQUIPO     2,
     EMPRESARIOS AGRUPADOS, A.I.E.                                                                             PAGINA     3
                                                      **********************                           FECHA Sun Oct 23 2011
  GHESA INGENIERIA Y TECNOLOGIA, S.A                  * HBAL-06/ASME-1967  *
                                                      * ================== *
    DEPARTAMENTO MECANICA APLICADA                    **********************
  ==================================


              auxiliar                                                                        


          LA CORRIENTE     1 NO SALE DE NINGUN EQUIPO
            NO OBSTANTE LA CONFIGURACION PUEDE SER VALIDA

          LA CORRIENTE     3 NO ENTRA A NINGUN EQUIPO
            NO OBSTANTE LA CONFIGURACION PUEDE SER VALIDA

     EMPRESARIOS AGRUPADOS, A.I.E.                                                                             PAGINA     4
                                                      **********************                           FECHA Sun Oct 23 2011
  GHESA INGENIERIA Y TECNOLOGIA, S.A                  * HBAL-06/ASME-1967  *
                                                      * ================== *
    DEPARTAMENTO MECANICA APLICADA                    **********************
  ==================================


              auxiliar                                                                        


 EL EQUIPO       1 GENERA LAS ECUACIONES     1 --     6
 EL EQUIPO       2 GENERA LAS ECUACIONES     7 --     9
     EMPRESARIOS AGRUPADOS, A.I.E.                                                                             PAGINA     5
                                                      **********************                           FECHA Sun Oct 23 2011
  GHESA INGENIERIA Y TECNOLOGIA, S.A                  * HBAL-06/ASME-1967  *
                                                      * ================== *
    DEPARTAMENTO MECANICA APLICADA                    **********************
  ==================================


              auxiliar                                                                        


 CORRIENTE NUMERO     1 --------  3.01944400E+01 1.20000000E+02 2.67400000E+03
 CORRIENTE NUMERO     2 --------  3.01944400E+01 1.20000000E+02 2.67400000E+03
 CORRIENTE NUMERO     3 --------  3.01944400E+01 1.15000000E+02 3.43299310E+03
     EMPRESARIOS AGRUPADOS, A.I.E.                                                                             PAGINA     6
                                                      **********************                           FECHA Sun Oct 23 2011
  GHESA INGENIERIA Y TECNOLOGIA, S.A                  * HBAL-06/ASME-1967  *
                                                      * ================== *
    DEPARTAMENTO MECANICA APLICADA                    **********************
  ==================================


              auxiliar                                                                        


 NUMERO DE NO CEROS EN LA MATRIZ=        13

                         ITERACION NUMERO    1 ERROR MAXIMO   2.009908E-06 (RELATIVO Y EN VALOR ABSOLUTO)
                                LA VARIABLE CON ERRMAX ES H(   3)
 NUMERO DE NO CEROS EN LA MATRIZ=        13

                         ITERACION NUMERO    2 ERROR MAXIMO   0.000000E+00 (RELATIVO Y EN VALOR ABSOLUTO)
                                LA VARIABLE CON ERRMAX ES W(   3)
     EMPRESARIOS AGRUPADOS, A.I.E.                                                                             PAGINA     7
                                                      **********************                           FECHA Sun Oct 23 2011
  GHESA INGENIERIA Y TECNOLOGIA, S.A                  * HBAL-06/ASME-1967  *
                                                      * ================== *
    DEPARTAMENTO MECANICA APLICADA                    **********************
  ==================================


              auxiliar                                                                        


      CORR     CAUDAL         TEMPERATURA        PRESION       VOL ESPECIFICO      ENTALPIA         ENTROPIA          TITULO
       NO     (KGS/SG)            (C)             (BARA)          (M**3/KG)        (KJ/KG)         (KJ/KG/C) 


        1       30.1944          324.6          120.0000           0.014122         2674.0           5.47485          0.9873
        2       30.1944          324.6          120.0000           0.014122         2674.0           5.47485          0.9873
        3       30.1944          529.7          115.0000           0.029618         3433.0           6.61431          1.0000
     EMPRESARIOS AGRUPADOS, A.I.E.                                                                             PAGINA     8
                                                      **********************                           FECHA Sun Oct 23 2011
  GHESA INGENIERIA Y TECNOLOGIA, S.A                  * HBAL-06/ASME-1967  *
                                                      * ================== *
    DEPARTAMENTO MECANICA APLICADA                    **********************
  ==================================


              auxiliar                                                                        







