     EMPRESARIOS AGRUPADOS, A.I.E.                                                                             PAGINA     1
                                                      **********************                           FECHA Wed Nov  3 2010
  GHESA INGENIERIA Y TECNOLOGIA, S.A                  *      HBAL-05       *
                                                      * ================== *
  DEPARTAMENTO DE ANALISIS MECANICOS                  **********************
  ==================================


               C.N.LAGUNA VERDE  120% carga  T.A CIRC 28低 incluye hasta msr                  


         1         1         1         0         2         0    1        
  1.26013E+03  7.03300E+01  2.77144E+03  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00
         2         3         2         0         3         0    1        
  0.00000E+00  0.00000E+00  2.82100E-06  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00
         3         2         3         0         4         5    1        
  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00
         4         2         4         0         6         7    2        
  3.93000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00
         5         5         6         8         9         0    0        
  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00
         6        20         9         0        10        11    3        
  2.10000E-01  2.79380E+03  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00
         7        19        10         0        12         0    0        
  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00
         8         2        12         0        13        14    1        
  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00
         9         9        14         0        15         0    2        
  8.81190E-01  0.00000E+00  1.34200E+01  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00
        10         9        13         0        16         0    2        
  8.82486E-01  0.00000E+00  1.34046E+01  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00
        11         1        19         0         8         0    1        
  2.00000E-01  2.74029E+01  2.79380E+03  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00
        12        13        15         0        21        20    1        
  2.55000E-02  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00
        13        13        16         0        23        22    5        
  2.49880E-02  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00
        14         2        21         0        24        25    1        
  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00
        15         2        23         0        26        27    1        
  6.86435E+01  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00
        16         9        26         0        28         0    3        
  8.66480E-01  0.00000E+00  2.81002E+01  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00
        17         9        24         0        29         0    3        
  8.67185E-01  0.00000E+00  2.48953E+01  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00
        18         5        28        29        30         0    3        
  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  1.00000E+00
        19         5        30        31        32         0    1        
  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00
        20         2        32         0        33        34    1        
  1.31000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00
        21         2        33         0        35        36    1        
  8.55731E+01  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00
        22         3        35         0        37         0    0        
  0.00000E+00  0.00000E+00  0.00000E+00  1.46630E-02  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00
        23         3        37         0        38         0    3        
  9.00000E-02  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00
        24        13        38         0        40        39    0        
  9.80000E-01  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00
        25         5        25        20        50         0    0        
  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00
     EMPRESARIOS AGRUPADOS, A.I.E.                                                                             PAGINA     2
                                                      **********************                           FECHA Wed Nov  3 2010
  GHESA INGENIERIA Y TECNOLOGIA, S.A                  *      HBAL-05       *
                                                      * ================== *
  DEPARTAMENTO DE ANALISIS MECANICOS                  **********************
  ==================================


               C.N.LAGUNA VERDE  120% carga  T.A CIRC 28低 incluye hasta msr                  


        26         3        50         0        51         0    0        
  0.00000E+00  0.00000E+00  0.00000E+00  6.60000E-03  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00
        27         2        51         0        52        53    0        
  0.00000E+00  2.50000E-02  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00
        28         2         5         0        45        46    0        
  2.52000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00
        29         3        45         0        47         0    0        
  0.00000E+00  0.00000E+00  0.00000E+00  8.70000E-03  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00
        30         2        47         0        48        49    0        
  0.00000E+00  2.50000E-02  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00
        31        14        40        52        41        42    1        
  9.20700E-02  0.00000E+00  0.00000E+00  0.00000E+00  8.40000E+00  1.00000E+00  1.18866E+00  0.00000E+00  0.00000E+00
        32        14        41        48        43        44    2        
  2.17240E-01  0.00000E+00  0.00000E+00  0.00000E+00  9.30000E+00  1.00000E+00  9.95600E-01  0.00000E+00  0.00000E+00
        33         1        54         0        31         0    0        
  2.22000E+00  2.74029E+01  2.79380E+03  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00
        34         3        43         0        55         0    1        
  0.00000E+00  0.00000E+00  0.00000E+00  5.00000E-03  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00
        35         2        55         0        56        57    0        
  1.63216E+01  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00
        36         3        56         0        58         0    0        
  0.00000E+00  0.00000E+00  0.00000E+00  2.69000E-02  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00
        37         9        58         0        59         0    4        
  9.39000E-01  0.00000E+00  1.04139E+02  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00
        38         2        59         0        60        61    9        
  4.64623E+01  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00
        39         9        60         0        62         0    5        
  9.30600E-01  0.00000E+00  2.08627E+02  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00
        40        13        62         0        64        63    6        
  1.02060E-02  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00
        41         2        64         0        65        66   10        
  4.75026E+01  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00
        42         9        65         0        67         0    6        
  9.09834E-01  0.00000E+00  3.97506E+02  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00
        43         1        67         0        68         0    0        
  0.00000E+00  9.09400E-01  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00
     EMPRESARIOS AGRUPADOS, A.I.E.                                                                             PAGINA     3
                                                      **********************                           FECHA Wed Nov  3 2010
  GHESA INGENIERIA Y TECNOLOGIA, S.A                  *      HBAL-05       *
                                                      * ================== *
  DEPARTAMENTO DE ANALISIS MECANICOS                  **********************
  ==================================


               C.N.LAGUNA VERDE  120% carga  T.A CIRC 28低 incluye hasta msr                  



          LA CORRIENTE     1 ENTRA AL EQUIPO     1,
          LA CORRIENTE     2 SALE DEL EQUIPO     1 Y ENTRA AL EQUIPO     2
          LA CORRIENTE     3 SALE DEL EQUIPO     2 Y ENTRA AL EQUIPO     3
          LA CORRIENTE     4 SALE DEL EQUIPO     3 Y ENTRA AL EQUIPO     4
          LA CORRIENTE     5 SALE DEL EQUIPO     3 Y ENTRA AL EQUIPO    28
          LA CORRIENTE     6 SALE DEL EQUIPO     4 Y ENTRA AL EQUIPO     5

          LA CORRIENTE     7 SALE DEL EQUIPO     4,
          LA CORRIENTE     8 SALE DEL EQUIPO    11 Y ENTRA AL EQUIPO     5
          LA CORRIENTE     9 SALE DEL EQUIPO     5 Y ENTRA AL EQUIPO     6
          LA CORRIENTE    10 SALE DEL EQUIPO     6 Y ENTRA AL EQUIPO     7

          LA CORRIENTE    11 SALE DEL EQUIPO     6,
          LA CORRIENTE    12 SALE DEL EQUIPO     7 Y ENTRA AL EQUIPO     8
          LA CORRIENTE    13 SALE DEL EQUIPO     8 Y ENTRA AL EQUIPO    10
          LA CORRIENTE    14 SALE DEL EQUIPO     8 Y ENTRA AL EQUIPO     9
          LA CORRIENTE    15 SALE DEL EQUIPO     9 Y ENTRA AL EQUIPO    12
          LA CORRIENTE    16 SALE DEL EQUIPO    10 Y ENTRA AL EQUIPO    13

          LA CORRIENTE    19 ENTRA AL EQUIPO    11,
          LA CORRIENTE    20 SALE DEL EQUIPO    12 Y ENTRA AL EQUIPO    25
          LA CORRIENTE    21 SALE DEL EQUIPO    12 Y ENTRA AL EQUIPO    14

          LA CORRIENTE    22 SALE DEL EQUIPO    13,
          LA CORRIENTE    23 SALE DEL EQUIPO    13 Y ENTRA AL EQUIPO    15
          LA CORRIENTE    24 SALE DEL EQUIPO    14 Y ENTRA AL EQUIPO    17
          LA CORRIENTE    25 SALE DEL EQUIPO    14 Y ENTRA AL EQUIPO    25
          LA CORRIENTE    26 SALE DEL EQUIPO    15 Y ENTRA AL EQUIPO    16

          LA CORRIENTE    27 SALE DEL EQUIPO    15,
          LA CORRIENTE    28 SALE DEL EQUIPO    16 Y ENTRA AL EQUIPO    18
          LA CORRIENTE    29 SALE DEL EQUIPO    17 Y ENTRA AL EQUIPO    18
          LA CORRIENTE    30 SALE DEL EQUIPO    18 Y ENTRA AL EQUIPO    19
          LA CORRIENTE    31 SALE DEL EQUIPO    33 Y ENTRA AL EQUIPO    19
          LA CORRIENTE    32 SALE DEL EQUIPO    19 Y ENTRA AL EQUIPO    20
          LA CORRIENTE    33 SALE DEL EQUIPO    20 Y ENTRA AL EQUIPO    21

          LA CORRIENTE    34 SALE DEL EQUIPO    20,
          LA CORRIENTE    35 SALE DEL EQUIPO    21 Y ENTRA AL EQUIPO    22

          LA CORRIENTE    36 SALE DEL EQUIPO    21,
          LA CORRIENTE    37 SALE DEL EQUIPO    22 Y ENTRA AL EQUIPO    23
          LA CORRIENTE    38 SALE DEL EQUIPO    23 Y ENTRA AL EQUIPO    24

          LA CORRIENTE    39 SALE DEL EQUIPO    24,
          LA CORRIENTE    40 SALE DEL EQUIPO    24 Y ENTRA AL EQUIPO    31
          LA CORRIENTE    41 SALE DEL EQUIPO    31 Y ENTRA AL EQUIPO    32

          LA CORRIENTE    42 SALE DEL EQUIPO    31,
     EMPRESARIOS AGRUPADOS, A.I.E.                                                                             PAGINA     4
                                                      **********************                           FECHA Wed Nov  3 2010
  GHESA INGENIERIA Y TECNOLOGIA, S.A                  *      HBAL-05       *
                                                      * ================== *
  DEPARTAMENTO DE ANALISIS MECANICOS                  **********************
  ==================================


               C.N.LAGUNA VERDE  120% carga  T.A CIRC 28低 incluye hasta msr                  


          LA CORRIENTE    43 SALE DEL EQUIPO    32 Y ENTRA AL EQUIPO    34

          LA CORRIENTE    44 SALE DEL EQUIPO    32,
          LA CORRIENTE    45 SALE DEL EQUIPO    28 Y ENTRA AL EQUIPO    29

          LA CORRIENTE    46 SALE DEL EQUIPO    28,
          LA CORRIENTE    47 SALE DEL EQUIPO    29 Y ENTRA AL EQUIPO    30
          LA CORRIENTE    48 SALE DEL EQUIPO    30 Y ENTRA AL EQUIPO    32

          LA CORRIENTE    49 SALE DEL EQUIPO    30,
          LA CORRIENTE    50 SALE DEL EQUIPO    25 Y ENTRA AL EQUIPO    26
          LA CORRIENTE    51 SALE DEL EQUIPO    26 Y ENTRA AL EQUIPO    27
          LA CORRIENTE    52 SALE DEL EQUIPO    27 Y ENTRA AL EQUIPO    31

          LA CORRIENTE    53 SALE DEL EQUIPO    27,

          LA CORRIENTE    54 ENTRA AL EQUIPO    33,
          LA CORRIENTE    55 SALE DEL EQUIPO    34 Y ENTRA AL EQUIPO    35
          LA CORRIENTE    56 SALE DEL EQUIPO    35 Y ENTRA AL EQUIPO    36

          LA CORRIENTE    57 SALE DEL EQUIPO    35,
          LA CORRIENTE    58 SALE DEL EQUIPO    36 Y ENTRA AL EQUIPO    37
          LA CORRIENTE    59 SALE DEL EQUIPO    37 Y ENTRA AL EQUIPO    38
          LA CORRIENTE    60 SALE DEL EQUIPO    38 Y ENTRA AL EQUIPO    39

          LA CORRIENTE    61 SALE DEL EQUIPO    38,
          LA CORRIENTE    62 SALE DEL EQUIPO    39 Y ENTRA AL EQUIPO    40

          LA CORRIENTE    63 SALE DEL EQUIPO    40,
          LA CORRIENTE    64 SALE DEL EQUIPO    40 Y ENTRA AL EQUIPO    41
          LA CORRIENTE    65 SALE DEL EQUIPO    41 Y ENTRA AL EQUIPO    42

          LA CORRIENTE    66 SALE DEL EQUIPO    41,
          LA CORRIENTE    67 SALE DEL EQUIPO    42 Y ENTRA AL EQUIPO    43

          LA CORRIENTE    68 SALE DEL EQUIPO    43,
     EMPRESARIOS AGRUPADOS, A.I.E.                                                                             PAGINA     5
                                                      **********************                           FECHA Wed Nov  3 2010
  GHESA INGENIERIA Y TECNOLOGIA, S.A                  *      HBAL-05       *
                                                      * ================== *
  DEPARTAMENTO DE ANALISIS MECANICOS                  **********************
  ==================================


               C.N.LAGUNA VERDE  120% carga  T.A CIRC 28低 incluye hasta msr                  


          LA CORRIENTE     1 NO SALE DE NINGUN EQUIPO
            NO OBSTANTE LA CONFIGURACION PUEDE SER VALIDA

          LA CORRIENTE     7 NO ENTRA A NINGUN EQUIPO
            NO OBSTANTE LA CONFIGURACION PUEDE SER VALIDA

          LA CORRIENTE    11 NO ENTRA A NINGUN EQUIPO
            NO OBSTANTE LA CONFIGURACION PUEDE SER VALIDA

          LA CORRIENTE    68 NO ENTRA A NINGUN EQUIPO
            NO OBSTANTE LA CONFIGURACION PUEDE SER VALIDA

          LA CORRIENTE    19 NO SALE DE NINGUN EQUIPO
            NO OBSTANTE LA CONFIGURACION PUEDE SER VALIDA

          LA CORRIENTE    22 NO ENTRA A NINGUN EQUIPO
            NO OBSTANTE LA CONFIGURACION PUEDE SER VALIDA

          LA CORRIENTE    27 NO ENTRA A NINGUN EQUIPO
            NO OBSTANTE LA CONFIGURACION PUEDE SER VALIDA

          LA CORRIENTE    34 NO ENTRA A NINGUN EQUIPO
            NO OBSTANTE LA CONFIGURACION PUEDE SER VALIDA

          LA CORRIENTE    36 NO ENTRA A NINGUN EQUIPO
            NO OBSTANTE LA CONFIGURACION PUEDE SER VALIDA

          LA CORRIENTE    39 NO ENTRA A NINGUN EQUIPO
            NO OBSTANTE LA CONFIGURACION PUEDE SER VALIDA

          LA CORRIENTE    42 NO ENTRA A NINGUN EQUIPO
            NO OBSTANTE LA CONFIGURACION PUEDE SER VALIDA

          LA CORRIENTE    44 NO ENTRA A NINGUN EQUIPO
            NO OBSTANTE LA CONFIGURACION PUEDE SER VALIDA

          LA CORRIENTE    46 NO ENTRA A NINGUN EQUIPO
            NO OBSTANTE LA CONFIGURACION PUEDE SER VALIDA

          LA CORRIENTE    49 NO ENTRA A NINGUN EQUIPO
            NO OBSTANTE LA CONFIGURACION PUEDE SER VALIDA

          LA CORRIENTE    53 NO ENTRA A NINGUN EQUIPO
            NO OBSTANTE LA CONFIGURACION PUEDE SER VALIDA

          LA CORRIENTE    54 NO SALE DE NINGUN EQUIPO
            NO OBSTANTE LA CONFIGURACION PUEDE SER VALIDA

          LA CORRIENTE    57 NO ENTRA A NINGUN EQUIPO
            NO OBSTANTE LA CONFIGURACION PUEDE SER VALIDA

          LA CORRIENTE    61 NO ENTRA A NINGUN EQUIPO
            NO OBSTANTE LA CONFIGURACION PUEDE SER VALIDA

          LA CORRIENTE    63 NO ENTRA A NINGUN EQUIPO
            NO OBSTANTE LA CONFIGURACION PUEDE SER VALIDA

          LA CORRIENTE    66 NO ENTRA A NINGUN EQUIPO
            NO OBSTANTE LA CONFIGURACION PUEDE SER VALIDA

     EMPRESARIOS AGRUPADOS, A.I.E.                                                                             PAGINA     6
                                                      **********************                           FECHA Wed Nov  3 2010
  GHESA INGENIERIA Y TECNOLOGIA, S.A                  *      HBAL-05       *
                                                      * ================== *
  DEPARTAMENTO DE ANALISIS MECANICOS                  **********************
  ==================================


               C.N.LAGUNA VERDE  120% carga  T.A CIRC 28低 incluye hasta msr                  


 EL EQUIPO       1 GENERA LAS ECUACIONES     1 --     6
 EL EQUIPO       2 GENERA LAS ECUACIONES     7 --     9
 EL EQUIPO       3 GENERA LAS ECUACIONES    10 --    14
 EL EQUIPO       4 GENERA LAS ECUACIONES    15 --    20
 EL EQUIPO       5 GENERA LAS ECUACIONES    21 --    23
 EL EQUIPO       6 GENERA LAS ECUACIONES    24 --    29
 EL EQUIPO       7 GENERA LAS ECUACIONES    30 --    31
 EL EQUIPO       8 GENERA LAS ECUACIONES    32 --    36
 EL EQUIPO       9 GENERA LAS ECUACIONES    37 --    39
 EL EQUIPO      10 GENERA LAS ECUACIONES    40 --    42
 EL EQUIPO      11 GENERA LAS ECUACIONES    43 --    48
 EL EQUIPO      12 GENERA LAS ECUACIONES    49 --    54
 EL EQUIPO      13 GENERA LAS ECUACIONES    55 --    60
 EL EQUIPO      14 GENERA LAS ECUACIONES    61 --    65
 EL EQUIPO      15 GENERA LAS ECUACIONES    66 --    71
 EL EQUIPO      16 GENERA LAS ECUACIONES    72 --    74
 EL EQUIPO      17 GENERA LAS ECUACIONES    75 --    77
 EL EQUIPO      18 GENERA LAS ECUACIONES    78 --    81
 EL EQUIPO      19 GENERA LAS ECUACIONES    82 --    84
 EL EQUIPO      20 GENERA LAS ECUACIONES    85 --    90
 EL EQUIPO      21 GENERA LAS ECUACIONES    91 --    96
 EL EQUIPO      22 GENERA LAS ECUACIONES    97 --    99
 EL EQUIPO      23 GENERA LAS ECUACIONES   100 --   102
 EL EQUIPO      24 GENERA LAS ECUACIONES   103 --   108
 EL EQUIPO      25 GENERA LAS ECUACIONES   109 --   111
 EL EQUIPO      26 GENERA LAS ECUACIONES   112 --   114
 EL EQUIPO      27 GENERA LAS ECUACIONES   115 --   120
 EL EQUIPO      28 GENERA LAS ECUACIONES   121 --   126
 EL EQUIPO      29 GENERA LAS ECUACIONES   127 --   129
 EL EQUIPO      30 GENERA LAS ECUACIONES   130 --   135
 EL EQUIPO      31 GENERA LAS ECUACIONES   136 --   142
 EL EQUIPO      32 GENERA LAS ECUACIONES   143 --   149
 EL EQUIPO      33 GENERA LAS ECUACIONES   150 --   155
 EL EQUIPO      34 GENERA LAS ECUACIONES   156 --   158
 EL EQUIPO      35 GENERA LAS ECUACIONES   159 --   164
 EL EQUIPO      36 GENERA LAS ECUACIONES   165 --   167
 EL EQUIPO      37 GENERA LAS ECUACIONES   168 --   170
 EL EQUIPO      38 GENERA LAS ECUACIONES   171 --   176
 EL EQUIPO      39 GENERA LAS ECUACIONES   177 --   179
 EL EQUIPO      40 GENERA LAS ECUACIONES   180 --   185
 EL EQUIPO      41 GENERA LAS ECUACIONES   186 --   191
 EL EQUIPO      42 GENERA LAS ECUACIONES   192 --   194
 EL EQUIPO      43 GENERA LAS ECUACIONES   195 --   198
     EMPRESARIOS AGRUPADOS, A.I.E.                                                                             PAGINA     7
                                                      **********************                           FECHA Wed Nov  3 2010
  GHESA INGENIERIA Y TECNOLOGIA, S.A                  *      HBAL-05       *
                                                      * ================== *
  DEPARTAMENTO DE ANALISIS MECANICOS                  **********************
  ==================================


               C.N.LAGUNA VERDE  120% carga  T.A CIRC 28低 incluye hasta msr                  


 CORRIENTE NUMERO     1 --------  1.26013400E+03 7.03300000E+01 2.77144000E+03
 CORRIENTE NUMERO     2 --------  1.26013400E+03 7.03300000E+01 2.77144000E+03
 CORRIENTE NUMERO     3 --------  1.26013404E+03 6.58504280E+01 2.77144000E+03
 CORRIENTE NUMERO     4 --------  1.19304640E+03 6.58504280E+01 2.77144000E+03
 CORRIENTE NUMERO     5 --------  6.70876380E+01 6.58504280E+01 2.77144000E+03
 CORRIENTE NUMERO     6 --------  1.18911640E+03 6.58504280E+01 2.77144000E+03
 CORRIENTE NUMERO     7 --------  3.93000000E+00 6.58504280E+01 2.77144000E+03
 CORRIENTE NUMERO     8 --------  2.00000000E-01 2.74029000E+01 2.79380000E+03
 CORRIENTE NUMERO     9 --------  1.18931640E+03 6.58504280E+01 2.77144380E+03
 CORRIENTE NUMERO    10 --------  1.18910640E+03 6.58504280E+01 2.77143980E+03
 CORRIENTE NUMERO    11 --------  2.10000000E-01 6.58504280E+01 2.79380000E+03
 CORRIENTE NUMERO    12 --------  1.18910636E+03 6.15468020E+01 2.77143980E+03
 CORRIENTE NUMERO    13 --------  5.94210740E+02 6.15468020E+01 2.77143980E+03
 CORRIENTE NUMERO    14 --------  5.94895620E+02 6.15468020E+01 2.77143980E+03
 CORRIENTE NUMERO    15 --------  5.94895620E+02 2.97479510E+01 2.65136300E+03
 CORRIENTE NUMERO    16 --------  5.94210742E+02 2.51137610E+01 2.62425660E+03
 CORRIENTE NUMERO    19 --------  2.00000000E-01 2.74029000E+01 2.79380000E+03
 CORRIENTE NUMERO    20 --------  1.27450810E+00 2.97479510E+01 1.00614760E+03
 CORRIENTE NUMERO    21 --------  5.93621112E+02 2.97479510E+01 2.65489530E+03
 CORRIENTE NUMERO    22 --------  1.42780190E+00 2.51137610E+01 9.63085400E+02
 CORRIENTE NUMERO    23 --------  5.92782940E+02 2.51137610E+01 2.62825780E+03
 CORRIENTE NUMERO    24 --------  5.46293010E+02 2.97479510E+01 2.65489530E+03
 CORRIENTE NUMERO    25 --------  4.73281020E+01 2.97479510E+01 2.65489530E+03
 CORRIENTE NUMERO    26 --------  5.24139440E+02 2.51137610E+01 2.62825780E+03
 CORRIENTE NUMERO    27 --------  6.86435000E+01 2.51137610E+01 2.62825780E+03
 CORRIENTE NUMERO    28 --------  5.24139440E+02 1.36425370E+01 2.53528820E+03
 CORRIENTE NUMERO    29 --------  5.46293010E+02 1.36425370E+01 2.53530100E+03
 CORRIENTE NUMERO    30 --------  1.07043250E+03 1.36425370E+01 2.53529480E+03
 CORRIENTE NUMERO    31 --------  2.22000000E+00 2.74029000E+01 2.79380000E+03
 CORRIENTE NUMERO    32 --------  1.07265245E+03 1.36425370E+01 2.53582980E+03
 CORRIENTE NUMERO    33 --------  1.07134245E+03 1.36425370E+01 2.53582980E+03
 CORRIENTE NUMERO    34 --------  1.31000000E+00 1.36425370E+01 2.53582980E+03
 CORRIENTE NUMERO    35 --------  9.85769350E+02 1.36425370E+01 2.53582980E+03
 CORRIENTE NUMERO    36 --------  8.55731000E+01 1.36425370E+01 2.53582980E+03
 CORRIENTE NUMERO    37 --------  9.85769350E+02 1.34424960E+01 2.53582980E+03
 CORRIENTE NUMERO    38 --------  9.85769350E+02 1.33524960E+01 2.53582980E+03
 CORRIENTE NUMERO    39 --------  1.23069550E+02 1.33524960E+01 8.20215240E+02
 CORRIENTE NUMERO    40 --------  8.62699800E+02 1.33524960E+01 2.78057300E+03
 CORRIENTE NUMERO    41 --------  8.62699800E+02 1.32604260E+01 2.86944150E+03
 CORRIENTE NUMERO    42 --------  4.73875450E+01 2.83629550E+01 9.93790980E+02
 CORRIENTE NUMERO    43 --------  8.62699800E+02 1.30431860E+01 2.98139370E+03
 CORRIENTE NUMERO    44 --------  6.29534470E+01 6.42819290E+01 1.23727200E+03
 CORRIENTE NUMERO    45 --------  6.45676380E+01 6.58504280E+01 2.77144000E+03
 CORRIENTE NUMERO    46 --------  2.52000000E+00 6.58504280E+01 2.77144000E+03
 CORRIENTE NUMERO    47 --------  6.45676379E+01 6.52775290E+01 2.77144000E+03
 CORRIENTE NUMERO    48 --------  6.29534470E+01 6.52775290E+01 2.77144000E+03
 CORRIENTE NUMERO    49 --------  1.61419090E+00 6.52775290E+01 2.77144000E+03
 CORRIENTE NUMERO    50 --------  4.86026100E+01 2.97479510E+01 2.61166010E+03
 CORRIENTE NUMERO    51 --------  4.86026102E+01 2.95516150E+01 2.61166010E+03
 CORRIENTE NUMERO    52 --------  4.73875450E+01 2.95516150E+01 2.61166010E+03
     EMPRESARIOS AGRUPADOS, A.I.E.                                                                             PAGINA     8
                                                      **********************                           FECHA Wed Nov  3 2010
  GHESA INGENIERIA Y TECNOLOGIA, S.A                  *      HBAL-05       *
                                                      * ================== *
  DEPARTAMENTO DE ANALISIS MECANICOS                  **********************
  ==================================


               C.N.LAGUNA VERDE  120% carga  T.A CIRC 28低 incluye hasta msr                  


 CORRIENTE NUMERO    53 --------  1.21506520E+00 2.95516150E+01 2.61166010E+03
 CORRIENTE NUMERO    54 --------  2.22000000E+00 2.74029000E+01 2.79380000E+03
 CORRIENTE NUMERO    55 --------  8.62699800E+02 1.29779700E+01 2.98139370E+03
 CORRIENTE NUMERO    56 --------  8.46378200E+02 1.29779700E+01 2.98139370E+03
 CORRIENTE NUMERO    57 --------  1.63216000E+01 1.29779700E+01 2.98139370E+03
 CORRIENTE NUMERO    58 --------  8.46378200E+02 1.26288630E+01 2.98139370E+03
 CORRIENTE NUMERO    59 --------  8.46378200E+02 5.44189130E+00 2.80783540E+03
 CORRIENTE NUMERO    60 --------  7.99915900E+02 5.44189130E+00 2.80783540E+03
 CORRIENTE NUMERO    61 --------  4.64623000E+01 5.44189130E+00 2.80783540E+03
 CORRIENTE NUMERO    62 --------  1.59967225E+03 2.51230000E+00 2.67399910E+03
 CORRIENTE NUMERO    63 --------  7.99915900E+02 2.51230000E+00 2.67399910E+03
 CORRIENTE NUMERO    64 --------  7.99756347E+02 2.51230000E+00 2.71661584E+03
 CORRIENTE NUMERO    65 --------  7.52253747E+02 2.51230000E+00 2.71661584E+03
 CORRIENTE NUMERO    66 --------  4.75026000E+01 2.51230000E+00 2.71661584E+03
 CORRIENTE NUMERO    67 --------  7.52253747E+02 9.09400000E-01 2.57491466E+03
 CORRIENTE NUMERO    68 --------  7.52253747E+02 9.09400000E-01 2.57491466E+03
     EMPRESARIOS AGRUPADOS, A.I.E.                                                                             PAGINA     9
                                                      **********************                           FECHA Wed Nov  3 2010
  GHESA INGENIERIA Y TECNOLOGIA, S.A                  *      HBAL-05       *
                                                      * ================== *
  DEPARTAMENTO DE ANALISIS MECANICOS                  **********************
  ==================================


               C.N.LAGUNA VERDE  120% carga  T.A CIRC 28低 incluye hasta msr                  


 NUMERO DE NO CEROS EN LA MATRIZ=       713

                         ITERACION NUMERO    1 ERROR MAXIMO   9.997747E-01 (RELATIVO Y EN VALOR ABSOLUTO)
                                LA VARIABLE CON ERRMAX ES W(  63)
 NUMERO DE NO CEROS EN LA MATRIZ=       713

                         ITERACION NUMERO    2 ERROR MAXIMO   7.076037E-01 (RELATIVO Y EN VALOR ABSOLUTO)
                                LA VARIABLE CON ERRMAX ES H(  63)
 NUMERO DE NO CEROS EN LA MATRIZ=       713

                         ITERACION NUMERO    3 ERROR MAXIMO   3.144743E-01 (RELATIVO Y EN VALOR ABSOLUTO)
                                LA VARIABLE CON ERRMAX ES H(  63)
 NUMERO DE NO CEROS EN LA MATRIZ=       713

                         ITERACION NUMERO    4 ERROR MAXIMO   2.253134E-04 (RELATIVO Y EN VALOR ABSOLUTO)
                                LA VARIABLE CON ERRMAX ES H(  63)
 NUMERO DE NO CEROS EN LA MATRIZ=       713

                         ITERACION NUMERO    5 ERROR MAXIMO   3.543985E-11 (RELATIVO Y EN VALOR ABSOLUTO)
                                LA VARIABLE CON ERRMAX ES H(  63)
     EMPRESARIOS AGRUPADOS, A.I.E.                                                                             PAGINA    10
                                                      **********************                           FECHA Wed Nov  3 2010
  GHESA INGENIERIA Y TECNOLOGIA, S.A                  *      HBAL-05       *
                                                      * ================== *
  DEPARTAMENTO DE ANALISIS MECANICOS                  **********************
  ==================================


               C.N.LAGUNA VERDE  120% carga  T.A CIRC 28低 incluye hasta msr                  


      CORR     CAUDAL         TEMPERATURA        PRESION       VOL ESPECIFICO      ENTALPIA         ENTROPIA          TITULO
       NO     (KGS/SG)            (C)             (BARA)          (M**3/KG)        (KJ/KG)         (KJ/KG/C) 


        1     1260.1340          286.1           70.3300           0.027202         2771.4           5.81095          0.9989
        2     1260.1340          286.1           70.3300           0.027202         2771.4           5.81095          0.9989
        3     1260.1340          281.7           65.8504           0.029167         2771.4           5.83360          0.9954
        4     1193.0464          281.7           65.8504           0.029167         2771.4           5.83360          0.9954
        5       67.0876          281.7           65.8504           0.029167         2771.4           5.83360          0.9954
        6     1189.1164          281.7           65.8504           0.029167         2771.4           5.83360          0.9954
        7        3.9300          281.7           65.8504           0.029167         2771.4           5.83360          0.9954
        8        0.2000          228.9           27.4029           0.072623         2793.8           6.20269          0.9956
        9     1189.3164          281.7           65.8504           0.029167         2771.4           5.83361          0.9954
       10     1189.1064          281.7           65.8504           0.029167         2771.4           5.83360          0.9954
       11        0.2100          284.9           65.8504           0.029809         2793.8           5.87382          1.0000
       12     1189.1064          277.2           61.5468           0.031321         2771.4           5.85714          0.9924
       13      594.2107          277.2           61.5468           0.031321         2771.4           5.85714          0.9924
       14      594.8956          277.2           61.5468           0.031321         2771.4           5.85714          0.9924
       15      594.8956          233.4           29.7480           0.061649         2651.4           5.88910          0.9160
       16      594.2107          224.2           25.1138           0.072013         2624.3           5.89654          0.9038
       19        0.2000          228.9           27.4029           0.072623         2793.8           6.20269          0.9956
       20        1.2745          233.4           29.7480           0.001215         1006.1           2.64120          0.0000
       21      593.6211          233.4           29.7480           0.061779         2654.9           5.89607          0.9180
       22        1.4278          224.2           25.1138           0.001198          963.1           2.55652          0.0000
       23      592.7829          224.2           25.1138           0.072183         2628.3           5.90459          0.9060
       24      546.2930          233.4           29.7480           0.061779         2654.9           5.89607          0.9180
       25       47.3281          233.4           29.7480           0.061779         2654.9           5.89607          0.9180
       26      524.1394          224.2           25.1138           0.072183         2628.3           5.90459          0.9060
       27       68.6435          224.2           25.1138           0.072183         2628.3           5.90459          0.9060
       28      524.1394          193.8           13.6425           0.125914         2535.3           5.93527          0.8717
       29      546.2930          193.8           13.6425           0.125915         2535.3           5.93529          0.8717
       30     1070.4325          193.8           13.6425           0.125914         2535.3           5.93528          0.8717
       31        2.2200          228.9           27.4029           0.072623         2793.8           6.20269          0.9956
       32     1072.6525          193.8           13.6425           0.125953         2535.8           5.93643          0.8720
       33     1071.3425          193.8           13.6425           0.125953         2535.8           5.93643          0.8720
       34        1.3100          193.8           13.6425           0.125953         2535.8           5.93643          0.8720
       35      985.7694          193.8           13.6425           0.125953         2535.8           5.93643          0.8720
       36       85.5731          193.8           13.6425           0.125953         2535.8           5.93643          0.8720
       37      985.7694          193.2           13.4425           0.127815         2535.8           5.94187          0.8724
       38      985.7694          192.8           13.3525           0.128670         2535.8           5.94434          0.8726
       39      123.0696          192.8           13.3525           0.001146          820.2           2.26272          0.0000
       40      862.6998          192.8           13.3525           0.146862         2780.6           6.46955          0.9971
       41      862.6998          224.6           13.2604           0.162630         2869.4           6.65750          1.0000
       42       47.3875          230.8           28.3630           0.001210          993.8           2.61708          0.0000
       43      862.6998          271.8           13.0432           0.185095         2981.4           6.87978          1.0000
       44       62.9534          280.1           64.2819           0.001333         1237.3           3.06906          0.0000
       45       64.5676          281.7           65.8504           0.029167         2771.4           5.83360          0.9954
       46        2.5200          281.7           65.8504           0.029167         2771.4           5.83360          0.9954
       47       64.5676          281.1           65.2775           0.029438         2771.4           5.83663          0.9950
       48       62.9534          281.1           65.2775           0.029438         2771.4           5.83663          0.9950
       49        1.6142          281.1           65.2775           0.029438         2771.4           5.83663          0.9950
       50       48.6026          233.4           29.7480           0.060191         2611.7           5.81072          0.8939
       51       48.6026          233.0           29.5516           0.060598         2611.7           5.81306          0.8940
       52       47.3875          233.0           29.5516           0.060598         2611.7           5.81306          0.8940
       53        1.2151          233.0           29.5516           0.060598         2611.7           5.81306          0.8940
     EMPRESARIOS AGRUPADOS, A.I.E.                                                                             PAGINA    11
                                                      **********************                           FECHA Wed Nov  3 2010
  GHESA INGENIERIA Y TECNOLOGIA, S.A                  *      HBAL-05       *
                                                      * ================== *
  DEPARTAMENTO DE ANALISIS MECANICOS                  **********************
  ==================================


               C.N.LAGUNA VERDE  120% carga  T.A CIRC 28低 incluye hasta msr                  


      CORR     CAUDAL         TEMPERATURA        PRESION       VOL ESPECIFICO      ENTALPIA         ENTROPIA          TITULO
       NO     (KGS/SG)            (C)             (BARA)          (M**3/KG)        (KJ/KG)         (KJ/KG/C) 


       54        2.2200          228.9           27.4029           0.072623         2793.8           6.20269          0.9956
       55      862.6998          271.7           12.9780           0.186028         2981.4           6.88200          1.0000
       56      846.3782          271.7           12.9780           0.186028         2981.4           6.88200          1.0000
       57       16.3216          271.7           12.9780           0.186028         2981.4           6.88200          1.0000
       58      846.3782          271.2           12.6289           0.191189         2981.4           6.89409          1.0000
       59      846.3782          179.7            5.4419           0.370171         2807.8           6.91912          1.0000
       60      799.9159          179.7            5.4419           0.370171         2807.8           6.91912          1.0000
       61       46.4623          179.7            5.4419           0.370171         2807.8           6.91912          1.0000
       62      799.9159          127.6            2.5120           0.701270         2674.0           6.94403          0.9804
       63        0.1596          127.6            2.5120           0.001068          536.0           1.60881          0.0000
       64      799.7563          127.6            2.5120           0.701410         2674.4           6.94510          0.9806
       65      752.2537          127.6            2.5120           0.701410         2674.4           6.94510          0.9806
       66       47.5026          127.6            2.5120           0.701410         2674.4           6.94510          0.9806
       67      752.2537           97.0            0.9094           1.728438         2521.1           6.98614          0.9337
       68      752.2537           97.0            0.9094           1.728438         2521.1           6.98614          0.9337
     EMPRESARIOS AGRUPADOS, A.I.E.                                                                             PAGINA    12
                                                      **********************                           FECHA Wed Nov  3 2010
  GHESA INGENIERIA Y TECNOLOGIA, S.A                  *      HBAL-05       *
                                                      * ================== *
  DEPARTAMENTO DE ANALISIS MECANICOS                  **********************
  ==================================


               C.N.LAGUNA VERDE  120% carga  T.A CIRC 28低 incluye hasta msr                  





                                        INFORMACION GENERAL DE ELEMENTOS DIVISORES NORMALES


    EQUIPO        FLUJO DE        FLUJO DE        FLUJO DE        FACTOR DE        FACTOR DE        RELACION         RELACION 
                  ENTRADA         SALIDA 1        SALIDA 2
      NO          (KG/SG)         (KG/SG)         (KG/SG)          FLUJO 1          FLUJO 2         PRI/PRINC        SEC/PRINC
    ======       ==========      ==========      ==========      ===========      ===========      ===========      ===========
        3        1260.1340       1193.0464       67.087638        25.108801        1.4119235       0.94676151       0.53238495E-01
        4        1193.0464       1189.1164       3.9300000        25.026091       0.82710608E-01   0.99670591       0.32940882E-02
        8        1189.1064       594.21074       594.89562        13.404600        13.420050       0.49971202       0.50028798    
       14        593.62111       546.29301       47.328102        24.895310        2.1568055       0.92027221       0.79727794E-01
       15        592.78294       524.13944       68.643500        28.100170        3.6801162       0.88420129       0.11579871    
       20        1072.6525       1071.3425       1.3100000        102.94037       0.12587187       0.99877873       0.12212716E-02
       21        1071.3425       985.76935       85.573100        94.718042        8.2223256       0.92012535       0.79874647E-01
       27        48.602610       47.387545       1.2150652        2.1458708       0.55022328E-01   0.97500000       0.25000000E-01
       28        67.087638       64.567638       2.5200000        1.3588877       0.53035809E-01   0.96243719       0.37562807E-01
       30        64.567638       62.953447       1.6141909        1.3368732       0.34278799E-01   0.97500000       0.25000000E-01
       35        862.69980       846.37820       16.321600        101.33290        1.9541088       0.98108079       0.18919212E-01
       38        846.37820       799.91590       46.462300        208.62700        12.117887       0.94510456       0.54895436E-01
       41        799.75629       752.25369       47.502600        397.50600        25.101331       0.94060366       0.59396344E-01
     EMPRESARIOS AGRUPADOS, A.I.E.                                                                             PAGINA    13
                                                      **********************                           FECHA Wed Nov  3 2010
  GHESA INGENIERIA Y TECNOLOGIA, S.A                  *      HBAL-05       *
                                                      * ================== *
  DEPARTAMENTO DE ANALISIS MECANICOS                  **********************
  ==================================


               C.N.LAGUNA VERDE  120% carga  T.A CIRC 28低 incluye hasta msr                  





                                    INFORMACION GENERAL DE TURBINAS DE VAPOR


                                 ENTRADA                       SALIDA
                      ----------------------------  ----------------------------
   EQUIPO    FLUJO    PRESION  TEMPERAT  ENTALPIA   PRESION  TEMPERAT  ENTALPIA  RELACION  FACTOR DE  EFICIENCIA  POTENCIA
     NO     (KGS/SG)   (BARA)    (C)      (KJ/KG)    (BARA)    (C)      (KJ/KG)  PENT/PSAL  FLUJO       (0/0)       (KW)


      9     594.8956  61.5468    277.21   2771.44   29.7480    233.37   2651.36      2.069    13.4200    88.12      71433.2
     10     594.2107  61.5468    277.21   2771.44   25.1138    224.18   2624.26      2.451    13.4046    88.25      87457.8
     16     524.1394  25.1138    224.18   2628.26   13.6425    193.84   2535.29      1.841    28.1002    86.65      48729.0
     17     546.2930  29.7480    233.37   2654.90   13.6425    193.84   2535.30      2.181    24.8953    86.72      65333.5
     37     846.3782  12.6289    271.20   2981.39    5.4419    179.70   2807.84      2.321   104.1390    93.90     146896.0
     39     799.9159   5.4419    179.70   2807.84    2.5120    127.59   2673.98      2.166   208.6270    93.06     107075.3
     42     752.2537   2.5120    127.59   2674.40    0.9094     97.00   2521.13      2.762   397.5060    90.98     115304.0
                                                                                                                  ---------
                                                                                                                   642228.8
     EMPRESARIOS AGRUPADOS, A.I.E.                                                                             PAGINA    14
                                                      **********************                           FECHA Wed Nov  3 2010
  GHESA INGENIERIA Y TECNOLOGIA, S.A                  *      HBAL-05       *
                                                      * ================== *
  DEPARTAMENTO DE ANALISIS MECANICOS                  **********************
  ==================================


               C.N.LAGUNA VERDE  120% carga  T.A CIRC 28低 incluye hasta msr                  



                LINEAS DE EXTRACCION DE TURBINA.-DIAGRAMA H-S.
                ==============================================

  3020.    ...............................................................................................................
           .          .          .          .          .          .          .          .          .          .          .
           .          .          .          .          .          .          .          .          .          .          .
           .          .          .          .          .          .          .          .          .          .          .
           .          .          .          .          .          .     *    .          .          .          .          .
  2970.    ...............................................................................................................
           .          .          .          .          .          .          .          .          .          .          .
           .          .          .          .          .          .          .          .          .          .          .
           .          .          .          .          .          .          .          .          .          .          .
           .          .          .          .          .          .          .          .          .          .          .
  2920.    ...............................................................................................................
           .          .          .          .          .          .          .          .          .          .          .
           .          .          .          .          .          .          .          .          .          .          .
           .          .          .          .          .          .          .          .          .          .          .
           .          .          .          .          .          .          .          .          .          .          .
  2870.    ...............................................................................................................
           .          .          .          .          .          .          .          .          .          .          .
           .          .          .          .          .          .          .          .          .          .          .
           .          .          .          .          .          .          .          .          .          .          .
           .          .          .          .          .          .          .          .          .          .          .
  2820.    ...............................................................................................................
           .          .          .          .          .          .          .          .          .          .          .
           .          .          .  *    *  .          .          .      +   .          .          .          .          .
           .          .       *  .          . *     *  .          .          .          .          .          .          .
           .          .          .          .          .          .          .          .          .          .          .
  2770.    ..............*+..............................*................................................................
           .          .          .          .          .       *  .          .          .          .          .          .
           .          .          .          .          .          .          .          .          .          .          .
           .       *  .          .          .          .          . *        .          .          .          .          .
           .          .          .          .          .          .       *  .          .          .          .          .
  2720.    ...............................................................................................................
           .  *       .          .          .          .          .          . *        .          .          .          .
           .          .          .          .          .          .          .          .          .          .          .
           .          .          .          .          .          .          .          .          .          .          .
           .          .          .          .          .          .          .          .          .          .          .
  2670.    ...............................................................+...............................................
           .          .          .          .          .          .          .          .          .          .          .
           .          .     +    .          .          .          .          .          .          .          .          .
           .          .          .          .          .          .          .          .          .          .          .
           .          .          .          .          .          .          .          .          .          .          .
  2620.    .................+.............................................................................................
           .          .          .          .          .          .          .          .          .          .          .
           .          .          .          .          .          .          .          .          .          .          .
           .          .          .          .          .          .          .          .          .          .          .
           .          .          .          .          .          .          .          .          .          .          .
  2570.    ...............................................................................................................
           .          .          .          .          .          .          .          .          .          .          .
           .          .          .          .          .          .          .          .          .          .          .
           .          .          .          .          .          .          .          .          .          .          .
           .          .       +  .          .          .          .          .          .          .          .          .
  2520.    .................................................................*.............................................

        5.50000    5.75000    6.00000    6.25000    6.50000    6.75000    7.00000    7.25000    7.50000    7.75000    8.00000
     EMPRESARIOS AGRUPADOS, A.I.E.                                                                             PAGINA    15
                                                      **********************                           FECHA Wed Nov  3 2010
  GHESA INGENIERIA Y TECNOLOGIA, S.A                  *      HBAL-05       *
                                                      * ================== *
  DEPARTAMENTO DE ANALISIS MECANICOS                  **********************
  ==================================


               C.N.LAGUNA VERDE  120% carga  T.A CIRC 28低 incluye hasta msr                  





                                        INFORMACION GENERAL DE SEPARADORES DE HUMEDAD


                            ENTRADA                         SALIDA VAPOR SECO              SALIDA DRENAJE
          -------------------------------------------- ---------------------------- ---------------------------
  EQUIPO    FLUJO    PRESION  TEMPER  ENTALPIA  TITULO    FLUJO    ENTALPIA  TITULO   FLUJO    ENTALPIA  TITULO  EFIC.  ARR.
    NO      (KG/S)   (BAR A.)  (C)    (KJ/KG)             (KG/S)   (KJ/KG)            (KG/S)   (KJ/KG)           (0/0) (0/0)

    12     594.8956    29.75  233.37   2651.36   0.916   593.6211   2654.90   0.918    1.2745   1006.15   0.000   2.55  0.00
    13     594.2107    25.11  224.18   2624.26   0.904   592.7829   2628.26   0.906    1.4278    963.09   0.000   2.50  0.00
    24     985.7694    13.35  192.84   2535.83   0.873   862.6998   2780.57   0.997  123.0696    820.22   0.000  98.00  0.00
    40     799.9159     2.51  127.59   2673.98   0.980   799.7563   2674.40   0.981    0.1596    536.01   0.000   1.02  0.00
     EMPRESARIOS AGRUPADOS, A.I.E.                                                                             PAGINA    16
                                                      **********************                           FECHA Wed Nov  3 2010
  GHESA INGENIERIA Y TECNOLOGIA, S.A                  *      HBAL-05       *
                                                      * ================== *
  DEPARTAMENTO DE ANALISIS MECANICOS                  **********************
  ==================================


               C.N.LAGUNA VERDE  120% carga  T.A CIRC 28低 incluye hasta msr                  





                                                INFORMACION GENERAL DE RECALENTADORES


                                                         VAPOR A RECALENTAR


                                ENTRADA                        SALIDA
                      ---------------------------   ---------------------------
   EQUIPO    FLUJO    PRESION  TEMPERAT  ENTALPIA   PRESION  TEMPERAT  ENTALPIA   CALOR ABSORBIDO   EFICIENCIA   LMTD   TTD
     NO     (KG/SG)    (BARA)    (C)      (KJ/KG)    (BARA)    (C)      (KJ/KG)         (KW)           (0/0)       C     C

     31    862.6998    13.352   192.84    2780.57    13.260   224.61    2869.44       76666.8         100.00    19.58   8.40
     32    862.6998    13.260   224.61    2869.44    13.043   271.80    2981.39       96581.2         100.00    25.86   9.30



                                                         VAPOR QUE RECALIENTA


                                ENTRADA                        SALIDA
                      ---------------------------   ---------------------------
   EQUIPO    FLUJO    PRESION  TEMPERAT  ENTALPIA   PRESION  TEMPERAT  ENTALPIA   CALOR CEDIDO  FACTORES DE TRANSFERENCIA
     NO     (KG/SG)    (BARA)    (C)      (KJ/KG)    (BARA)    (C)      (KJ/KG)       (KW)           UA          U

     31     47.3875    29.552   233.01    2611.66    28.363   230.75     993.79    76666.8       3915.        3915.    
     32     62.9534    65.278   281.10    2771.44    64.282   280.08    1237.27    96581.2       3735.        3735.    
     EMPRESARIOS AGRUPADOS, A.I.E.                                                                             PAGINA    17
                                                      **********************                           FECHA Wed Nov  3 2010
  GHESA INGENIERIA Y TECNOLOGIA, S.A                  *      HBAL-05       *
                                                      * ================== *
  DEPARTAMENTO DE ANALISIS MECANICOS                  **********************
  ==================================


               C.N.LAGUNA VERDE  120% carga  T.A CIRC 28低 incluye hasta msr                  


