     EMPRESARIOS AGRUPADOS, A.I.E.                                                                             PAGINA     1
                                                      **********************                           FECHA Fri Mar 11 2011
  GHESA INGENIERIA Y TECNOLOGIA, S.A                  * HBAL-06/ASME-1967  *
                                                      * ================== *
    DEPARTAMENTO MECANICA APLICADA                    **********************
  ==================================


               C.N.LAGUNA VERDE  120% carga  T.A CIRC 28低 incluye hasta msr                  


         1         1         1         0         2         0    1        
  1.26013E+03  7.03300E+01  2.77144E+03  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00
         2         3         2         0         3         0    1        
  0.00000E+00  0.00000E+00  2.82100E-06  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00
         3         2         3         0         4         5    1        
  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00
         4         2         4         0         6         7    2        
  3.93000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00
         5         5         6         8         9         0    0        
  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00
         6        20         9         0        10        11    3        
  2.10000E-01  2.79380E+03  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00
         7        19        10         0        12         0    0        
  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00
         8         2        12         0        13        14    1        
  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00
         9         9        14         0        15         0    2        
  8.81190E-01  0.00000E+00  1.34200E+01  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00
        10         9        13         0        16         0    2        
  8.82486E-01  0.00000E+00  1.34046E+01  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00
        11         1        16         0        18         0    1        
  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00
        12         1        15         0        17         0    1        
  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00
        13         1        19         0         8         0    1        
  2.00000E-01  2.74029E+01  2.79380E+03  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00
        14        13        17         0        21        20    1        
  2.55000E-02  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00
        15        13        18         0        23        22    5        
  2.49880E-02  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00
        16         2        21         0        24        25    1        
  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00
        17         2        23         0        26        27    1        
  6.86435E+01  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00
        18         9        26         0        28         0    3        
  8.66480E-01  0.00000E+00  2.81002E+01  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00
        19         9        24         0        29         0    3        
  8.67185E-01  0.00000E+00  2.48953E+01  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00
        20         5        28        29        30         0    3        
  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  1.00000E+00
        21         5        30        31        32         0    1        
  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00
        22         2        32         0        33        34    1        
  1.31000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00
        23         2        33         0        35        36    1        
  8.55731E+01  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00
        24         3        35         0        37         0    0        
  0.00000E+00  0.00000E+00  0.00000E+00  1.46630E-02  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00
        25         3        37         0        38         0    3        
  9.00000E-02  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00
     EMPRESARIOS AGRUPADOS, A.I.E.                                                                             PAGINA     2
                                                      **********************                           FECHA Fri Mar 11 2011
  GHESA INGENIERIA Y TECNOLOGIA, S.A                  * HBAL-06/ASME-1967  *
                                                      * ================== *
    DEPARTAMENTO MECANICA APLICADA                    **********************
  ==================================


               C.N.LAGUNA VERDE  120% carga  T.A CIRC 28低 incluye hasta msr                  


        26        13        38         0        40        39    0        
  9.80000E-01  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00
        27        14        40        52        41        42    1        
  9.20700E-02  0.00000E+00  0.00000E+00  0.00000E+00  8.40000E+00  1.00000E+00  1.18866E+00  0.00000E+00  0.00000E+00
        28        14        41        48        43        44    2        
  2.17240E-01  0.00000E+00  0.00000E+00  0.00000E+00  9.30000E+00  1.00000E+00  9.95600E-01  0.00000E+00  0.00000E+00
        29         2         5         0        45        46    0        
  2.52000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00
        30         3        45         0        47         0    0        
  0.00000E+00  0.00000E+00  0.00000E+00  8.70000E-03  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00
        31         2        47         0        48        49    0        
  0.00000E+00  2.50000E-02  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00
        32         5        25        20        50         0    0        
  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00
        33         3        50         0        51         0    0        
  0.00000E+00  0.00000E+00  0.00000E+00  6.60000E-03  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00
        34         2        51         0        52        53    0        
  0.00000E+00  2.50000E-02  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00
        35         1        54         0        31         0    0        
  2.22000E+00  2.74029E+01  2.79380E+03  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00
        36         3        43         0        55         0    1        
  0.00000E+00  0.00000E+00  0.00000E+00  5.00000E-03  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00
        37         2        55         0        56        57    0        
  1.63216E+01  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00
        38         3        56         0        58         0    0        
  0.00000E+00  0.00000E+00  0.00000E+00  2.69000E-02  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00
        39         9        58         0        59         0    4        
  9.39000E-01  0.00000E+00  1.04139E+02  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00
        40         2        59         0        60        61    9        
  4.64623E+01  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00
        41         9        60         0        62         0    5        
  9.30600E-01  0.00000E+00  2.08627E+02  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00
        42         1        62         1        63         0    0        
  0.00000E+00  2.51230E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00
     EMPRESARIOS AGRUPADOS, A.I.E.                                                                             PAGINA     3
                                                      **********************                           FECHA Fri Mar 11 2011
  GHESA INGENIERIA Y TECNOLOGIA, S.A                  * HBAL-06/ASME-1967  *
                                                      * ================== *
    DEPARTAMENTO MECANICA APLICADA                    **********************
  ==================================


               C.N.LAGUNA VERDE  120% carga  T.A CIRC 28低 incluye hasta msr                  



          LA CORRIENTE     1 ENTRA AL EQUIPO     1,   42,
          LA CORRIENTE     2 SALE DEL EQUIPO     1 Y ENTRA AL EQUIPO     2
          LA CORRIENTE     3 SALE DEL EQUIPO     2 Y ENTRA AL EQUIPO     3
          LA CORRIENTE     4 SALE DEL EQUIPO     3 Y ENTRA AL EQUIPO     4
          LA CORRIENTE     5 SALE DEL EQUIPO     3 Y ENTRA AL EQUIPO    29
          LA CORRIENTE     6 SALE DEL EQUIPO     4 Y ENTRA AL EQUIPO     5

          LA CORRIENTE     7 SALE DEL EQUIPO     4,
          LA CORRIENTE     8 SALE DEL EQUIPO    13 Y ENTRA AL EQUIPO     5
          LA CORRIENTE     9 SALE DEL EQUIPO     5 Y ENTRA AL EQUIPO     6
          LA CORRIENTE    10 SALE DEL EQUIPO     6 Y ENTRA AL EQUIPO     7

          LA CORRIENTE    11 SALE DEL EQUIPO     6,
          LA CORRIENTE    12 SALE DEL EQUIPO     7 Y ENTRA AL EQUIPO     8
          LA CORRIENTE    13 SALE DEL EQUIPO     8 Y ENTRA AL EQUIPO    10
          LA CORRIENTE    14 SALE DEL EQUIPO     8 Y ENTRA AL EQUIPO     9
          LA CORRIENTE    15 SALE DEL EQUIPO     9 Y ENTRA AL EQUIPO    12
          LA CORRIENTE    16 SALE DEL EQUIPO    10 Y ENTRA AL EQUIPO    11
          LA CORRIENTE    17 SALE DEL EQUIPO    12 Y ENTRA AL EQUIPO    14
          LA CORRIENTE    18 SALE DEL EQUIPO    11 Y ENTRA AL EQUIPO    15

          LA CORRIENTE    19 ENTRA AL EQUIPO    13,
          LA CORRIENTE    20 SALE DEL EQUIPO    14 Y ENTRA AL EQUIPO    32
          LA CORRIENTE    21 SALE DEL EQUIPO    14 Y ENTRA AL EQUIPO    16

          LA CORRIENTE    22 SALE DEL EQUIPO    15,
          LA CORRIENTE    23 SALE DEL EQUIPO    15 Y ENTRA AL EQUIPO    17
          LA CORRIENTE    24 SALE DEL EQUIPO    16 Y ENTRA AL EQUIPO    19
          LA CORRIENTE    25 SALE DEL EQUIPO    16 Y ENTRA AL EQUIPO    32
          LA CORRIENTE    26 SALE DEL EQUIPO    17 Y ENTRA AL EQUIPO    18

          LA CORRIENTE    27 SALE DEL EQUIPO    17,
          LA CORRIENTE    28 SALE DEL EQUIPO    18 Y ENTRA AL EQUIPO    20
          LA CORRIENTE    29 SALE DEL EQUIPO    19 Y ENTRA AL EQUIPO    20
          LA CORRIENTE    30 SALE DEL EQUIPO    20 Y ENTRA AL EQUIPO    21
          LA CORRIENTE    31 SALE DEL EQUIPO    35 Y ENTRA AL EQUIPO    21
          LA CORRIENTE    32 SALE DEL EQUIPO    21 Y ENTRA AL EQUIPO    22
          LA CORRIENTE    33 SALE DEL EQUIPO    22 Y ENTRA AL EQUIPO    23

          LA CORRIENTE    34 SALE DEL EQUIPO    22,
          LA CORRIENTE    35 SALE DEL EQUIPO    23 Y ENTRA AL EQUIPO    24

          LA CORRIENTE    36 SALE DEL EQUIPO    23,
          LA CORRIENTE    37 SALE DEL EQUIPO    24 Y ENTRA AL EQUIPO    25
          LA CORRIENTE    38 SALE DEL EQUIPO    25 Y ENTRA AL EQUIPO    26

          LA CORRIENTE    39 SALE DEL EQUIPO    26,
          LA CORRIENTE    40 SALE DEL EQUIPO    26 Y ENTRA AL EQUIPO    27
          LA CORRIENTE    41 SALE DEL EQUIPO    27 Y ENTRA AL EQUIPO    28
     EMPRESARIOS AGRUPADOS, A.I.E.                                                                             PAGINA     4
                                                      **********************                           FECHA Fri Mar 11 2011
  GHESA INGENIERIA Y TECNOLOGIA, S.A                  * HBAL-06/ASME-1967  *
                                                      * ================== *
    DEPARTAMENTO MECANICA APLICADA                    **********************
  ==================================


               C.N.LAGUNA VERDE  120% carga  T.A CIRC 28低 incluye hasta msr                  



          LA CORRIENTE    42 SALE DEL EQUIPO    27,
          LA CORRIENTE    43 SALE DEL EQUIPO    28 Y ENTRA AL EQUIPO    36

          LA CORRIENTE    44 SALE DEL EQUIPO    28,
          LA CORRIENTE    45 SALE DEL EQUIPO    29 Y ENTRA AL EQUIPO    30

          LA CORRIENTE    46 SALE DEL EQUIPO    29,
          LA CORRIENTE    47 SALE DEL EQUIPO    30 Y ENTRA AL EQUIPO    31
          LA CORRIENTE    48 SALE DEL EQUIPO    31 Y ENTRA AL EQUIPO    28

          LA CORRIENTE    49 SALE DEL EQUIPO    31,
          LA CORRIENTE    50 SALE DEL EQUIPO    32 Y ENTRA AL EQUIPO    33
          LA CORRIENTE    51 SALE DEL EQUIPO    33 Y ENTRA AL EQUIPO    34
          LA CORRIENTE    52 SALE DEL EQUIPO    34 Y ENTRA AL EQUIPO    27

          LA CORRIENTE    53 SALE DEL EQUIPO    34,

          LA CORRIENTE    54 ENTRA AL EQUIPO    35,
          LA CORRIENTE    55 SALE DEL EQUIPO    36 Y ENTRA AL EQUIPO    37
          LA CORRIENTE    56 SALE DEL EQUIPO    37 Y ENTRA AL EQUIPO    38

          LA CORRIENTE    57 SALE DEL EQUIPO    37,
          LA CORRIENTE    58 SALE DEL EQUIPO    38 Y ENTRA AL EQUIPO    39
          LA CORRIENTE    59 SALE DEL EQUIPO    39 Y ENTRA AL EQUIPO    40
          LA CORRIENTE    60 SALE DEL EQUIPO    40 Y ENTRA AL EQUIPO    41

          LA CORRIENTE    61 SALE DEL EQUIPO    40,
          LA CORRIENTE    62 SALE DEL EQUIPO    41 Y ENTRA AL EQUIPO    42

          LA CORRIENTE    63 SALE DEL EQUIPO    42,
     EMPRESARIOS AGRUPADOS, A.I.E.                                                                             PAGINA     5
                                                      **********************                           FECHA Fri Mar 11 2011
  GHESA INGENIERIA Y TECNOLOGIA, S.A                  * HBAL-06/ASME-1967  *
                                                      * ================== *
    DEPARTAMENTO MECANICA APLICADA                    **********************
  ==================================


               C.N.LAGUNA VERDE  120% carga  T.A CIRC 28低 incluye hasta msr                  


          LA CORRIENTE     1 ENTRA DOS O MAS VECES

     EMPRESARIOS AGRUPADOS, A.I.E.                                                                             PAGINA     6
                                                      **********************                           FECHA Fri Mar 11 2011
  GHESA INGENIERIA Y TECNOLOGIA, S.A                  * HBAL-06/ASME-1967  *
                                                      * ================== *
    DEPARTAMENTO MECANICA APLICADA                    **********************
  ==================================


               C.N.LAGUNA VERDE  120% carga  T.A CIRC 28低 incluye hasta msr                  


 EL EQUIPO       1 GENERA LAS ECUACIONES     1 --     6
 EL EQUIPO       2 GENERA LAS ECUACIONES     7 --     9
 EL EQUIPO       3 GENERA LAS ECUACIONES    10 --    14
 EL EQUIPO       4 GENERA LAS ECUACIONES    15 --    20
 EL EQUIPO       5 GENERA LAS ECUACIONES    21 --    23
 EL EQUIPO       6 GENERA LAS ECUACIONES    24 --    29
 EL EQUIPO       7 GENERA LAS ECUACIONES    30 --    31
 EL EQUIPO       8 GENERA LAS ECUACIONES    32 --    36
 EL EQUIPO       9 GENERA LAS ECUACIONES    37 --    39
 EL EQUIPO      10 GENERA LAS ECUACIONES    40 --    42
 EL EQUIPO      11 GENERA LAS ECUACIONES    43 --    45
 EL EQUIPO      12 GENERA LAS ECUACIONES    46 --    48
 EL EQUIPO      13 GENERA LAS ECUACIONES    49 --    54
 EL EQUIPO      14 GENERA LAS ECUACIONES    55 --    60
 EL EQUIPO      15 GENERA LAS ECUACIONES    61 --    66
 EL EQUIPO      16 GENERA LAS ECUACIONES    67 --    71
 EL EQUIPO      17 GENERA LAS ECUACIONES    72 --    77
 EL EQUIPO      18 GENERA LAS ECUACIONES    78 --    80
 EL EQUIPO      19 GENERA LAS ECUACIONES    81 --    83
 EL EQUIPO      20 GENERA LAS ECUACIONES    84 --    87
 EL EQUIPO      21 GENERA LAS ECUACIONES    88 --    90
 EL EQUIPO      22 GENERA LAS ECUACIONES    91 --    96
 EL EQUIPO      23 GENERA LAS ECUACIONES    97 --   102
 EL EQUIPO      24 GENERA LAS ECUACIONES   103 --   105
 EL EQUIPO      25 GENERA LAS ECUACIONES   106 --   108
 EL EQUIPO      26 GENERA LAS ECUACIONES   109 --   114
 EL EQUIPO      27 GENERA LAS ECUACIONES   115 --   121
 EL EQUIPO      28 GENERA LAS ECUACIONES   122 --   128
 EL EQUIPO      29 GENERA LAS ECUACIONES   129 --   134
 EL EQUIPO      30 GENERA LAS ECUACIONES   135 --   137
 EL EQUIPO      31 GENERA LAS ECUACIONES   138 --   143
 EL EQUIPO      32 GENERA LAS ECUACIONES   144 --   146
 EL EQUIPO      33 GENERA LAS ECUACIONES   147 --   149
 EL EQUIPO      34 GENERA LAS ECUACIONES   150 --   155
 EL EQUIPO      35 GENERA LAS ECUACIONES   156 --   161
 EL EQUIPO      36 GENERA LAS ECUACIONES   162 --   164
 EL EQUIPO      37 GENERA LAS ECUACIONES   165 --   170
 EL EQUIPO      38 GENERA LAS ECUACIONES   171 --   173
 EL EQUIPO      39 GENERA LAS ECUACIONES   174 --   176
 EL EQUIPO      40 GENERA LAS ECUACIONES   177 --   182
 EL EQUIPO      41 GENERA LAS ECUACIONES   183 --   185
 EL EQUIPO      42 GENERA LAS ECUACIONES   186 --   189
     EMPRESARIOS AGRUPADOS, A.I.E.                                                                             PAGINA     7
                                                      **********************                           FECHA Fri Mar 11 2011
  GHESA INGENIERIA Y TECNOLOGIA, S.A                  * HBAL-06/ASME-1967  *
                                                      * ================== *
    DEPARTAMENTO MECANICA APLICADA                    **********************
  ==================================


               C.N.LAGUNA VERDE  120% carga  T.A CIRC 28低 incluye hasta msr                  


