     EMPRESARIOS AGRUPADOS, A.I.E.                                                                             PAGINA     1
                                                      **********************                           FECHA Sun Oct 31 2010
  GHESA INGENIERIA Y TECNOLOGIA, S.A                  *      HBAL-05       *
                                                      * ================== *
  DEPARTAMENTO DE ANALISIS MECANICOS                  **********************
  ==================================


               C.N.LAGUNA VERDE  120% carga  T.A CIRC 28低 incluye hasta msr                  


         1         1         1         0         2         0    1        
  1.26013E+03  7.03300E+01  2.77144E+03  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00
         2         3         2         0         3         0    1        
  0.00000E+00  0.00000E+00  2.82100E-06  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00
         3         2         3         0         4         5    1        
  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00
         4         2         4         0         6         7    2        
  3.93000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00
         5         5         6         8         9         0    0        
  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00
         6        20         9         0        10        11    3        
  2.10000E-01  2.79380E+03  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00
         7        19        10         0        12         0    0        
  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00
         8         2        12         0        13        14    1        
  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00
         9         9        14         0        15         0    2        
  8.81190E-01  0.00000E+00  1.34200E+01  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00
        10         9        13         0        16         0    2        
  8.82486E-01  0.00000E+00  1.34046E+01  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00
        11         1        16         0        18         0    1        
  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00
        12         1        15         0        17         0    1        
  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00
        13         1        19         0         8         0    1        
  2.00000E-01  2.74029E+01  2.79380E+03  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00
        14        13        17         0        21        20    1        
  2.55000E-02  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00
        15        13        18         0        23        22    5        
  2.49880E-02  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00
        16         2        21         0        24        25    1        
  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00
        17         2        23         0        26        27    1        
  6.86435E+01  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00
        18         9        26         0        28         0    3        
  8.66480E-01  0.00000E+00  2.81002E+01  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00
        19         9        24         0        29         0    3        
  8.67185E-01  0.00000E+00  2.48953E+01  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00
        20         5        28        29        30         0    3        
  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  1.00000E+00
        21         5        30        31        32         0    1        
  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00
        22         2        32         0        33        34    1        
  1.31000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00
        23         2        33         0        35        36    1        
  8.55731E+01  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00
        24         3        35         0        37         0    0        
  0.00000E+00  0.00000E+00  0.00000E+00  1.46630E-02  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00
        25         3        37         0        38         0    3        
  9.00000E-02  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00
     EMPRESARIOS AGRUPADOS, A.I.E.                                                                             PAGINA     2
                                                      **********************                           FECHA Sun Oct 31 2010
  GHESA INGENIERIA Y TECNOLOGIA, S.A                  *      HBAL-05       *
                                                      * ================== *
  DEPARTAMENTO DE ANALISIS MECANICOS                  **********************
  ==================================


               C.N.LAGUNA VERDE  120% carga  T.A CIRC 28低 incluye hasta msr                  


        26        13        38         0        40        39    0        
  9.80000E-01  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00
        27        14        40        52        41        42    1        
  9.20700E-02  0.00000E+00  0.00000E+00  0.00000E+00  8.40000E+00  1.00000E+00  1.18866E+00  0.00000E+00  0.00000E+00
        28        14        41        48        43        44    2        
  2.17240E-01  0.00000E+00  0.00000E+00  0.00000E+00  9.30000E+00  1.00000E+00  9.95600E-01  0.00000E+00  0.00000E+00
        29         2         5         0        45        46    0        
  2.52000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00
        30         3        45         0        47         0    0        
  0.00000E+00  0.00000E+00  0.00000E+00  8.70000E-03  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00
        31         2        47         0        48        49    0        
  0.00000E+00  2.50000E-02  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00
        32         5        25        20        50         0    0        
  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00
        33         3        50         0        51         0    0        
  0.00000E+00  0.00000E+00  0.00000E+00  6.60000E-03  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00
        34         2        51         0        52        53    0        
  0.00000E+00  2.50000E-02  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00
        35         1        54         0        31         0    0        
  2.22000E+00  2.74029E+01  2.79380E+03  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00
        36         1        43         0        55         0    0        
  0.00000E+00  1.30400E+01  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00
     EMPRESARIOS AGRUPADOS, A.I.E.                                                                             PAGINA     3
                                                      **********************                           FECHA Sun Oct 31 2010
  GHESA INGENIERIA Y TECNOLOGIA, S.A                  *      HBAL-05       *
                                                      * ================== *
  DEPARTAMENTO DE ANALISIS MECANICOS                  **********************
  ==================================


               C.N.LAGUNA VERDE  120% carga  T.A CIRC 28低 incluye hasta msr                  



          LA CORRIENTE     1 ENTRA AL EQUIPO     1,
          LA CORRIENTE     2 SALE DEL EQUIPO     1 Y ENTRA AL EQUIPO     2
          LA CORRIENTE     3 SALE DEL EQUIPO     2 Y ENTRA AL EQUIPO     3
          LA CORRIENTE     4 SALE DEL EQUIPO     3 Y ENTRA AL EQUIPO     4
          LA CORRIENTE     5 SALE DEL EQUIPO     3 Y ENTRA AL EQUIPO    29
          LA CORRIENTE     6 SALE DEL EQUIPO     4 Y ENTRA AL EQUIPO     5

          LA CORRIENTE     7 SALE DEL EQUIPO     4,
          LA CORRIENTE     8 SALE DEL EQUIPO    13 Y ENTRA AL EQUIPO     5
          LA CORRIENTE     9 SALE DEL EQUIPO     5 Y ENTRA AL EQUIPO     6
          LA CORRIENTE    10 SALE DEL EQUIPO     6 Y ENTRA AL EQUIPO     7

          LA CORRIENTE    11 SALE DEL EQUIPO     6,
          LA CORRIENTE    12 SALE DEL EQUIPO     7 Y ENTRA AL EQUIPO     8
          LA CORRIENTE    13 SALE DEL EQUIPO     8 Y ENTRA AL EQUIPO    10
          LA CORRIENTE    14 SALE DEL EQUIPO     8 Y ENTRA AL EQUIPO     9
          LA CORRIENTE    15 SALE DEL EQUIPO     9 Y ENTRA AL EQUIPO    12
          LA CORRIENTE    16 SALE DEL EQUIPO    10 Y ENTRA AL EQUIPO    11
          LA CORRIENTE    17 SALE DEL EQUIPO    12 Y ENTRA AL EQUIPO    14
          LA CORRIENTE    18 SALE DEL EQUIPO    11 Y ENTRA AL EQUIPO    15

          LA CORRIENTE    19 ENTRA AL EQUIPO    13,
          LA CORRIENTE    20 SALE DEL EQUIPO    14 Y ENTRA AL EQUIPO    32
          LA CORRIENTE    21 SALE DEL EQUIPO    14 Y ENTRA AL EQUIPO    16

          LA CORRIENTE    22 SALE DEL EQUIPO    15,
          LA CORRIENTE    23 SALE DEL EQUIPO    15 Y ENTRA AL EQUIPO    17
          LA CORRIENTE    24 SALE DEL EQUIPO    16 Y ENTRA AL EQUIPO    19
          LA CORRIENTE    25 SALE DEL EQUIPO    16 Y ENTRA AL EQUIPO    32
          LA CORRIENTE    26 SALE DEL EQUIPO    17 Y ENTRA AL EQUIPO    18

          LA CORRIENTE    27 SALE DEL EQUIPO    17,
          LA CORRIENTE    28 SALE DEL EQUIPO    18 Y ENTRA AL EQUIPO    20
          LA CORRIENTE    29 SALE DEL EQUIPO    19 Y ENTRA AL EQUIPO    20
          LA CORRIENTE    30 SALE DEL EQUIPO    20 Y ENTRA AL EQUIPO    21
          LA CORRIENTE    31 SALE DEL EQUIPO    35 Y ENTRA AL EQUIPO    21
          LA CORRIENTE    32 SALE DEL EQUIPO    21 Y ENTRA AL EQUIPO    22
          LA CORRIENTE    33 SALE DEL EQUIPO    22 Y ENTRA AL EQUIPO    23

          LA CORRIENTE    34 SALE DEL EQUIPO    22,
          LA CORRIENTE    35 SALE DEL EQUIPO    23 Y ENTRA AL EQUIPO    24

          LA CORRIENTE    36 SALE DEL EQUIPO    23,
          LA CORRIENTE    37 SALE DEL EQUIPO    24 Y ENTRA AL EQUIPO    25
          LA CORRIENTE    38 SALE DEL EQUIPO    25 Y ENTRA AL EQUIPO    26

          LA CORRIENTE    39 SALE DEL EQUIPO    26,
          LA CORRIENTE    40 SALE DEL EQUIPO    26 Y ENTRA AL EQUIPO    27
          LA CORRIENTE    41 SALE DEL EQUIPO    27 Y ENTRA AL EQUIPO    28
     EMPRESARIOS AGRUPADOS, A.I.E.                                                                             PAGINA     4
                                                      **********************                           FECHA Sun Oct 31 2010
  GHESA INGENIERIA Y TECNOLOGIA, S.A                  *      HBAL-05       *
                                                      * ================== *
  DEPARTAMENTO DE ANALISIS MECANICOS                  **********************
  ==================================


               C.N.LAGUNA VERDE  120% carga  T.A CIRC 28低 incluye hasta msr                  



          LA CORRIENTE    42 SALE DEL EQUIPO    27,
          LA CORRIENTE    43 SALE DEL EQUIPO    28 Y ENTRA AL EQUIPO    36

          LA CORRIENTE    44 SALE DEL EQUIPO    28,
          LA CORRIENTE    45 SALE DEL EQUIPO    29 Y ENTRA AL EQUIPO    30

          LA CORRIENTE    46 SALE DEL EQUIPO    29,
          LA CORRIENTE    47 SALE DEL EQUIPO    30 Y ENTRA AL EQUIPO    31
          LA CORRIENTE    48 SALE DEL EQUIPO    31 Y ENTRA AL EQUIPO    28

          LA CORRIENTE    49 SALE DEL EQUIPO    31,
          LA CORRIENTE    50 SALE DEL EQUIPO    32 Y ENTRA AL EQUIPO    33
          LA CORRIENTE    51 SALE DEL EQUIPO    33 Y ENTRA AL EQUIPO    34
          LA CORRIENTE    52 SALE DEL EQUIPO    34 Y ENTRA AL EQUIPO    27

          LA CORRIENTE    53 SALE DEL EQUIPO    34,

          LA CORRIENTE    54 ENTRA AL EQUIPO    35,

          LA CORRIENTE    55 SALE DEL EQUIPO    36,
     EMPRESARIOS AGRUPADOS, A.I.E.                                                                             PAGINA     5
                                                      **********************                           FECHA Sun Oct 31 2010
  GHESA INGENIERIA Y TECNOLOGIA, S.A                  *      HBAL-05       *
                                                      * ================== *
  DEPARTAMENTO DE ANALISIS MECANICOS                  **********************
  ==================================


               C.N.LAGUNA VERDE  120% carga  T.A CIRC 28低 incluye hasta msr                  


          LA CORRIENTE     1 NO SALE DE NINGUN EQUIPO
            NO OBSTANTE LA CONFIGURACION PUEDE SER VALIDA

          LA CORRIENTE     7 NO ENTRA A NINGUN EQUIPO
            NO OBSTANTE LA CONFIGURACION PUEDE SER VALIDA

          LA CORRIENTE    11 NO ENTRA A NINGUN EQUIPO
            NO OBSTANTE LA CONFIGURACION PUEDE SER VALIDA

          LA CORRIENTE    19 NO SALE DE NINGUN EQUIPO
            NO OBSTANTE LA CONFIGURACION PUEDE SER VALIDA

          LA CORRIENTE    22 NO ENTRA A NINGUN EQUIPO
            NO OBSTANTE LA CONFIGURACION PUEDE SER VALIDA

          LA CORRIENTE    27 NO ENTRA A NINGUN EQUIPO
            NO OBSTANTE LA CONFIGURACION PUEDE SER VALIDA

          LA CORRIENTE    34 NO ENTRA A NINGUN EQUIPO
            NO OBSTANTE LA CONFIGURACION PUEDE SER VALIDA

          LA CORRIENTE    36 NO ENTRA A NINGUN EQUIPO
            NO OBSTANTE LA CONFIGURACION PUEDE SER VALIDA

          LA CORRIENTE    39 NO ENTRA A NINGUN EQUIPO
            NO OBSTANTE LA CONFIGURACION PUEDE SER VALIDA

          LA CORRIENTE    42 NO ENTRA A NINGUN EQUIPO
            NO OBSTANTE LA CONFIGURACION PUEDE SER VALIDA

          LA CORRIENTE    44 NO ENTRA A NINGUN EQUIPO
            NO OBSTANTE LA CONFIGURACION PUEDE SER VALIDA

          LA CORRIENTE    46 NO ENTRA A NINGUN EQUIPO
            NO OBSTANTE LA CONFIGURACION PUEDE SER VALIDA

          LA CORRIENTE    49 NO ENTRA A NINGUN EQUIPO
            NO OBSTANTE LA CONFIGURACION PUEDE SER VALIDA

          LA CORRIENTE    53 NO ENTRA A NINGUN EQUIPO
            NO OBSTANTE LA CONFIGURACION PUEDE SER VALIDA

          LA CORRIENTE    54 NO SALE DE NINGUN EQUIPO
            NO OBSTANTE LA CONFIGURACION PUEDE SER VALIDA

          LA CORRIENTE    55 NO ENTRA A NINGUN EQUIPO
            NO OBSTANTE LA CONFIGURACION PUEDE SER VALIDA

     EMPRESARIOS AGRUPADOS, A.I.E.                                                                             PAGINA     6
                                                      **********************                           FECHA Sun Oct 31 2010
  GHESA INGENIERIA Y TECNOLOGIA, S.A                  *      HBAL-05       *
                                                      * ================== *
  DEPARTAMENTO DE ANALISIS MECANICOS                  **********************
  ==================================


               C.N.LAGUNA VERDE  120% carga  T.A CIRC 28低 incluye hasta msr                  


 EL EQUIPO       1 GENERA LAS ECUACIONES     1 --     6
 EL EQUIPO       2 GENERA LAS ECUACIONES     7 --     9
 EL EQUIPO       3 GENERA LAS ECUACIONES    10 --    14
 EL EQUIPO       4 GENERA LAS ECUACIONES    15 --    20
 EL EQUIPO       5 GENERA LAS ECUACIONES    21 --    23
 EL EQUIPO       6 GENERA LAS ECUACIONES    24 --    29
 EL EQUIPO       7 GENERA LAS ECUACIONES    30 --    31
 EL EQUIPO       8 GENERA LAS ECUACIONES    32 --    36
 EL EQUIPO       9 GENERA LAS ECUACIONES    37 --    39
 EL EQUIPO      10 GENERA LAS ECUACIONES    40 --    42
 EL EQUIPO      11 GENERA LAS ECUACIONES    43 --    45
 EL EQUIPO      12 GENERA LAS ECUACIONES    46 --    48
 EL EQUIPO      13 GENERA LAS ECUACIONES    49 --    54
 EL EQUIPO      14 GENERA LAS ECUACIONES    55 --    60
 EL EQUIPO      15 GENERA LAS ECUACIONES    61 --    66
 EL EQUIPO      16 GENERA LAS ECUACIONES    67 --    71
 EL EQUIPO      17 GENERA LAS ECUACIONES    72 --    77
 EL EQUIPO      18 GENERA LAS ECUACIONES    78 --    80
 EL EQUIPO      19 GENERA LAS ECUACIONES    81 --    83
 EL EQUIPO      20 GENERA LAS ECUACIONES    84 --    87
 EL EQUIPO      21 GENERA LAS ECUACIONES    88 --    90
 EL EQUIPO      22 GENERA LAS ECUACIONES    91 --    96
 EL EQUIPO      23 GENERA LAS ECUACIONES    97 --   102
 EL EQUIPO      24 GENERA LAS ECUACIONES   103 --   105
 EL EQUIPO      25 GENERA LAS ECUACIONES   106 --   108
 EL EQUIPO      26 GENERA LAS ECUACIONES   109 --   114
 EL EQUIPO      27 GENERA LAS ECUACIONES   115 --   121
 EL EQUIPO      28 GENERA LAS ECUACIONES   122 --   128
 EL EQUIPO      29 GENERA LAS ECUACIONES   129 --   134
 EL EQUIPO      30 GENERA LAS ECUACIONES   135 --   137
 EL EQUIPO      31 GENERA LAS ECUACIONES   138 --   143
 EL EQUIPO      32 GENERA LAS ECUACIONES   144 --   146
 EL EQUIPO      33 GENERA LAS ECUACIONES   147 --   149
 EL EQUIPO      34 GENERA LAS ECUACIONES   150 --   155
 EL EQUIPO      35 GENERA LAS ECUACIONES   156 --   161
 EL EQUIPO      36 GENERA LAS ECUACIONES   162 --   165
     EMPRESARIOS AGRUPADOS, A.I.E.                                                                             PAGINA     7
                                                      **********************                           FECHA Sun Oct 31 2010
  GHESA INGENIERIA Y TECNOLOGIA, S.A                  *      HBAL-05       *
                                                      * ================== *
  DEPARTAMENTO DE ANALISIS MECANICOS                  **********************
  ==================================


               C.N.LAGUNA VERDE  120% carga  T.A CIRC 28低 incluye hasta msr                  


 CORRIENTE NUMERO     1 --------  1.26013400E+03 7.03300000E+01 2.77144000E+03
 CORRIENTE NUMERO     2 --------  1.26013400E+03 7.03300000E+01 2.77144000E+03
 CORRIENTE NUMERO     3 --------  1.26013400E+03 6.58504280E+01 2.77144000E+03
 CORRIENTE NUMERO     4 --------  1.19306400E+03 6.58504280E+01 2.77144000E+03
 CORRIENTE NUMERO     5 --------  6.70700000E+01 6.58504280E+01 2.77144000E+03
 CORRIENTE NUMERO     6 --------  1.18913400E+03 6.58504280E+01 2.77144000E+03
 CORRIENTE NUMERO     7 --------  3.93000000E+00 6.58504280E+01 2.77144000E+03
 CORRIENTE NUMERO     8 --------  2.00000000E-01 2.74029000E+01 2.79380000E+03
 CORRIENTE NUMERO     9 --------  1.18933400E+03 6.58504280E+01 2.77144380E+03
 CORRIENTE NUMERO    10 --------  1.18912400E+03 6.58504280E+01 2.77143980E+03
 CORRIENTE NUMERO    11 --------  2.10000000E-01 6.58504280E+01 2.79380000E+03
 CORRIENTE NUMERO    12 --------  1.18912400E+03 6.15476920E+01 2.77143980E+03
 CORRIENTE NUMERO    13 --------  5.94219550E+02 6.15476920E+01 2.77143980E+03
 CORRIENTE NUMERO    14 --------  5.94904450E+02 6.15476920E+01 2.77143980E+03
 CORRIENTE NUMERO    15 --------  5.94904450E+02 2.97484420E+01 2.65139400E+03
 CORRIENTE NUMERO    16 --------  5.94219550E+02 2.51141510E+01 2.62425290E+03
 CORRIENTE NUMERO    17 --------  5.94904449E+02 2.97484420E+01 2.65139400E+03
 CORRIENTE NUMERO    18 --------  5.94219558E+02 2.51141510E+01 2.62425290E+03
 CORRIENTE NUMERO    19 --------  2.00000000E-01 2.74029000E+01 2.79380000E+03
 CORRIENTE NUMERO    20 --------  1.27426900E+00 2.97484420E+01 1.00615190E+03
 CORRIENTE NUMERO    21 --------  5.93630180E+02 2.97484420E+01 2.65492560E+03
 CORRIENTE NUMERO    22 --------  1.42785800E+00 2.51141510E+01 9.63089250E+02
 CORRIENTE NUMERO    23 --------  5.92791700E+02 2.51141510E+01 2.62825410E+03
 CORRIENTE NUMERO    24 --------  5.46297180E+02 2.97484420E+01 2.65492560E+03
 CORRIENTE NUMERO    25 --------  4.73330000E+01 2.97484420E+01 2.65492560E+03
 CORRIENTE NUMERO    26 --------  5.24148200E+02 2.51141510E+01 2.62825410E+03
 CORRIENTE NUMERO    27 --------  6.86435000E+01 2.51141510E+01 2.62825410E+03
 CORRIENTE NUMERO    28 --------  5.24148200E+02 1.36404000E+01 2.53526810E+03
 CORRIENTE NUMERO    29 --------  5.46297180E+02 1.36404000E+01 2.53534730E+03
 CORRIENTE NUMERO    30 --------  1.07044540E+03 1.36404000E+01 2.53530850E+03
 CORRIENTE NUMERO    31 --------  2.22000000E+00 2.74029000E+01 2.79380000E+03
 CORRIENTE NUMERO    32 --------  2.14089080E+03 1.36404000E+01 2.53530849E+03
 CORRIENTE NUMERO    33 --------  2.13958080E+03 1.36404000E+01 2.53530849E+03
 CORRIENTE NUMERO    34 --------  1.31000000E+00 1.36404000E+01 2.53530849E+03
 CORRIENTE NUMERO    35 --------  2.05400770E+03 1.36404000E+01 2.53530849E+03
 CORRIENTE NUMERO    36 --------  8.55731000E+01 1.36404000E+01 2.53530849E+03
 CORRIENTE NUMERO    37 --------  2.05400770E+03 1.29583798E+01 2.53530849E+03
 CORRIENTE NUMERO    38 --------  2.05400770E+03 1.23104607E+01 2.53530849E+03
 CORRIENTE NUMERO    39 --------  2.52425184E+02 1.23104607E+01 8.03585245E+02
 CORRIENTE NUMERO    40 --------  1.80158252E+03 1.23104607E+01 2.78360725E+03
 CORRIENTE NUMERO    41 --------  1.80158252E+03 1.22183907E+01 2.86866619E+03
 CORRIENTE NUMERO    42 --------  4.73920873E+01 2.82610195E+01 1.04760391E+03
 CORRIENTE NUMERO    43 --------  1.80158252E+03 1.30400000E+01 2.97502492E+03
 CORRIENTE NUMERO    44 --------  6.29362500E+01 6.25579058E+01 1.22789047E+03
 CORRIENTE NUMERO    45 --------  6.45500000E+01 6.58504280E+01 2.77144000E+03
 CORRIENTE NUMERO    46 --------  2.52000000E+00 6.58504280E+01 2.77144000E+03
 CORRIENTE NUMERO    47 --------  6.45500000E+01 6.25579058E+01 2.77144000E+03
 CORRIENTE NUMERO    48 --------  6.29362500E+01 6.25579058E+01 2.77144000E+03
 CORRIENTE NUMERO    49 --------  1.61375000E+00 6.25579058E+01 2.77144000E+03
 CORRIENTE NUMERO    50 --------  4.86072690E+01 2.97484420E+01 2.61170146E+03
     EMPRESARIOS AGRUPADOS, A.I.E.                                                                             PAGINA     8
                                                      **********************                           FECHA Sun Oct 31 2010
  GHESA INGENIERIA Y TECNOLOGIA, S.A                  *      HBAL-05       *
                                                      * ================== *
  DEPARTAMENTO DE ANALISIS MECANICOS                  **********************
  ==================================


               C.N.LAGUNA VERDE  120% carga  T.A CIRC 28低 incluye hasta msr                  


 CORRIENTE NUMERO    51 --------  4.86072690E+01 2.82610195E+01 2.61170146E+03
 CORRIENTE NUMERO    52 --------  4.73920873E+01 2.82610195E+01 2.61170146E+03
 CORRIENTE NUMERO    53 --------  1.21518172E+00 2.82610195E+01 2.61170146E+03
 CORRIENTE NUMERO    54 --------  2.22000000E+00 2.74029000E+01 2.79380000E+03
 CORRIENTE NUMERO    55 --------  1.80158252E+03 1.30400000E+01 2.97502492E+03
     EMPRESARIOS AGRUPADOS, A.I.E.                                                                             PAGINA     9
                                                      **********************                           FECHA Sun Oct 31 2010
  GHESA INGENIERIA Y TECNOLOGIA, S.A                  *      HBAL-05       *
                                                      * ================== *
  DEPARTAMENTO DE ANALISIS MECANICOS                  **********************
  ==================================


               C.N.LAGUNA VERDE  120% carga  T.A CIRC 28低 incluye hasta msr                  


 NUMERO DE NO CEROS EN LA MATRIZ=       570

                         ITERACION NUMERO    1 ERROR MAXIMO   5.233336E-01 (RELATIVO Y EN VALOR ABSOLUTO)
                                LA VARIABLE CON ERRMAX ES W(  40)
 NUMERO DE NO CEROS EN LA MATRIZ=       570

                         ITERACION NUMERO    2 ERROR MAXIMO   4.885881E-02 (RELATIVO Y EN VALOR ABSOLUTO)
                                LA VARIABLE CON ERRMAX ES W(  45)
 NUMERO DE NO CEROS EN LA MATRIZ=       570

                         ITERACION NUMERO    3 ERROR MAXIMO   1.334263E-05 (RELATIVO Y EN VALOR ABSOLUTO)
                                LA VARIABLE CON ERRMAX ES H(  50)
 NUMERO DE NO CEROS EN LA MATRIZ=       570

                         ITERACION NUMERO    4 ERROR MAXIMO   1.282969E-09 (RELATIVO Y EN VALOR ABSOLUTO)
                                LA VARIABLE CON ERRMAX ES W(  25)
 NUMERO DE NO CEROS EN LA MATRIZ=       570

                         ITERACION NUMERO    5 ERROR MAXIMO   1.757174E-12 (RELATIVO Y EN VALOR ABSOLUTO)
                                LA VARIABLE CON ERRMAX ES W(  20)
     EMPRESARIOS AGRUPADOS, A.I.E.                                                                             PAGINA    10
                                                      **********************                           FECHA Sun Oct 31 2010
  GHESA INGENIERIA Y TECNOLOGIA, S.A                  *      HBAL-05       *
                                                      * ================== *
  DEPARTAMENTO DE ANALISIS MECANICOS                  **********************
  ==================================


               C.N.LAGUNA VERDE  120% carga  T.A CIRC 28低 incluye hasta msr                  


      CORR     CAUDAL         TEMPERATURA        PRESION       VOL ESPECIFICO      ENTALPIA         ENTROPIA          TITULO
       NO     (KGS/SG)            (C)             (BARA)          (M**3/KG)        (KJ/KG)         (KJ/KG/C) 


        1     1260.1340          286.1           70.3300           0.027202         2771.4           5.81095          0.9989
        2     1260.1340          286.1           70.3300           0.027202         2771.4           5.81095          0.9989
        3     1260.1340          281.7           65.8504           0.029167         2771.4           5.83360          0.9954
        4     1193.0495          281.7           65.8504           0.029167         2771.4           5.83360          0.9954
        5       67.0845          281.7           65.8504           0.029167         2771.4           5.83360          0.9954
        6     1189.1195          281.7           65.8504           0.029167         2771.4           5.83360          0.9954
        7        3.9300          281.7           65.8504           0.029167         2771.4           5.83360          0.9954
        8        0.2000          228.9           27.4029           0.072623         2793.8           6.20269          0.9956
        9     1189.3195          281.7           65.8504           0.029167         2771.4           5.83361          0.9954
       10     1189.1095          281.7           65.8504           0.029167         2771.4           5.83360          0.9954
       11        0.2100          284.9           65.8504           0.029809         2793.8           5.87382          1.0000
       12     1189.1095          277.2           61.5470           0.031321         2771.4           5.85714          0.9924
       13      594.2123          277.2           61.5470           0.031321         2771.4           5.85714          0.9924
       14      594.8972          277.2           61.5470           0.031321         2771.4           5.85714          0.9924
       15      594.8972          233.4           29.7474           0.061650         2651.4           5.88910          0.9160
       16      594.2123          224.2           25.1138           0.072012         2624.3           5.89654          0.9038
       17      594.8972          233.4           29.7474           0.061650         2651.4           5.88910          0.9160
       18      594.2123          224.2           25.1138           0.072012         2624.3           5.89654          0.9038
       19        0.2000          228.9           27.4029           0.072623         2793.8           6.20269          0.9956
       20        1.2745          233.4           29.7474           0.001215         1006.1           2.64119          0.0000
       21      593.6227          233.4           29.7474           0.061780         2654.9           5.89607          0.9179
       22        1.4278          224.2           25.1138           0.001198          963.1           2.55652          0.0000
       23      592.7845          224.2           25.1138           0.072183         2628.3           5.90459          0.9060
       24      546.2838          233.4           29.7474           0.061780         2654.9           5.89607          0.9179
       25       47.3388          233.4           29.7474           0.061780         2654.9           5.89607          0.9179
       26      524.1410          224.2           25.1138           0.072183         2628.3           5.90459          0.9060
       27       68.6435          224.2           25.1138           0.072183         2628.3           5.90459          0.9060
       28      524.1410          193.8           13.6393           0.125941         2535.3           5.93528          0.8717
       29      546.2838          193.8           13.6393           0.125942         2535.3           5.93531          0.8717
       30     1070.4249          193.8           13.6393           0.125941         2535.3           5.93529          0.8717
       31        2.2200          228.9           27.4029           0.072623         2793.8           6.20269          0.9956
       32     1072.6449          193.8           13.6393           0.125981         2535.8           5.93644          0.8720
       33     1071.3349          193.8           13.6393           0.125981         2535.8           5.93644          0.8720
       34        1.3100          193.8           13.6393           0.125981         2535.8           5.93644          0.8720
       35      985.7618          193.8           13.6393           0.125981         2535.8           5.93644          0.8720
       36       85.5731          193.8           13.6393           0.125981         2535.8           5.93644          0.8720
       37      985.7618          193.1           13.4393           0.127842         2535.8           5.94188          0.8724
       38      985.7618          192.8           13.3493           0.128698         2535.8           5.94435          0.8726
       39      123.0795          192.8           13.3493           0.001146          820.2           2.26261          0.0000
       40      862.6822          192.8           13.3493           0.146896         2780.6           6.46963          0.9971
       41      862.6822          224.6           13.2572           0.162672         2869.5           6.65763          1.0000
       42       47.3980          230.7           28.3624           0.001210          993.8           2.61707          0.0000
       43      862.6822          271.8           13.0400           0.185142         2981.4           6.87991          1.0000
       44       62.9504          280.1           64.2819           0.001333         1237.3           3.06906          0.0000
       45       64.5645          281.7           65.8504           0.029167         2771.4           5.83360          0.9954
       46        2.5200          281.7           65.8504           0.029167         2771.4           5.83360          0.9954
       47       64.5645          281.1           65.2775           0.029438         2771.4           5.83663          0.9950
       48       62.9504          281.1           65.2775           0.029438         2771.4           5.83663          0.9950
       49        1.6141          281.1           65.2775           0.029438         2771.4           5.83663          0.9950
       50       48.6134          233.4           29.7474           0.060192         2611.7           5.81074          0.8939
       51       48.6134          233.0           29.5511           0.060600         2611.7           5.81308          0.8940
     EMPRESARIOS AGRUPADOS, A.I.E.                                                                             PAGINA    11
                                                      **********************                           FECHA Sun Oct 31 2010
  GHESA INGENIERIA Y TECNOLOGIA, S.A                  *      HBAL-05       *
                                                      * ================== *
  DEPARTAMENTO DE ANALISIS MECANICOS                  **********************
  ==================================


               C.N.LAGUNA VERDE  120% carga  T.A CIRC 28低 incluye hasta msr                  


      CORR     CAUDAL         TEMPERATURA        PRESION       VOL ESPECIFICO      ENTALPIA         ENTROPIA          TITULO
       NO     (KGS/SG)            (C)             (BARA)          (M**3/KG)        (KJ/KG)         (KJ/KG/C) 


       52       47.3980          233.0           29.5511           0.060600         2611.7           5.81308          0.8940
       53        1.2153          233.0           29.5511           0.060600         2611.7           5.81308          0.8940
       54        2.2200          228.9           27.4029           0.072623         2793.8           6.20269          0.9956
       55      862.6822          271.8           13.0400           0.185142         2981.4           6.87991          1.0000
     EMPRESARIOS AGRUPADOS, A.I.E.                                                                             PAGINA    12
                                                      **********************                           FECHA Sun Oct 31 2010
  GHESA INGENIERIA Y TECNOLOGIA, S.A                  *      HBAL-05       *
                                                      * ================== *
  DEPARTAMENTO DE ANALISIS MECANICOS                  **********************
  ==================================


               C.N.LAGUNA VERDE  120% carga  T.A CIRC 28低 incluye hasta msr                  





                                        INFORMACION GENERAL DE ELEMENTOS DIVISORES NORMALES


    EQUIPO        FLUJO DE        FLUJO DE        FLUJO DE        FACTOR DE        FACTOR DE        RELACION         RELACION 
                  ENTRADA         SALIDA 1        SALIDA 2
      NO          (KG/SG)         (KG/SG)         (KG/SG)          FLUJO 1          FLUJO 2         PRI/PRINC        SEC/PRINC
    ======       ==========      ==========      ==========      ===========      ===========      ===========      ===========
        3        1260.1340       1193.0495       67.084480        25.108868        1.4118570       0.94676401       0.53235989E-01
        4        1193.0495       1189.1195       3.9300000        25.026157       0.82710608E-01   0.99670592       0.32940795E-02
        8        1189.1095       594.21232       594.89720        13.404600        13.420050       0.49971202       0.50028798    
       16        593.62267       546.28384       47.338826        24.895310        2.1573304       0.92025435       0.79745651E-01
       17        592.78451       524.14101       68.643500        28.100170        3.6801051       0.88420160       0.11579840    
       22        1072.6449       1071.3349       1.3100000        102.96291       0.12590033       0.99877872       0.12212803E-02
       23        1071.3349       985.76175       85.573100        94.738726        8.2241845       0.92012479       0.79875213E-01
       29        67.084480       64.564480       2.5200000        1.3588212       0.53035809E-01   0.96243542       0.37564575E-01
       31        64.564480       62.950368       1.6141120        1.3368078       0.34277123E-01   0.97500000       0.25000000E-01
       34        48.613361       47.398027       1.2153340        2.1463871       0.55035568E-01   0.97500000       0.25000000E-01
     EMPRESARIOS AGRUPADOS, A.I.E.                                                                             PAGINA    13
                                                      **********************                           FECHA Sun Oct 31 2010
  GHESA INGENIERIA Y TECNOLOGIA, S.A                  *      HBAL-05       *
                                                      * ================== *
  DEPARTAMENTO DE ANALISIS MECANICOS                  **********************
  ==================================


               C.N.LAGUNA VERDE  120% carga  T.A CIRC 28低 incluye hasta msr                  





                                    INFORMACION GENERAL DE TURBINAS DE VAPOR


                                 ENTRADA                       SALIDA
                      ----------------------------  ----------------------------
   EQUIPO    FLUJO    PRESION  TEMPERAT  ENTALPIA   PRESION  TEMPERAT  ENTALPIA  RELACION  FACTOR DE  EFICIENCIA  POTENCIA
     NO     (KGS/SG)   (BARA)    (C)      (KJ/KG)    (BARA)    (C)      (KJ/KG)  PENT/PSAL  FLUJO       (0/0)       (KW)


      9     594.8972  61.5470    277.21   2771.44   29.7474    233.37   2651.36      2.069    13.4201    88.12      71435.3
     10     594.2123  61.5470    277.21   2771.44   25.1138    224.18   2624.26      2.451    13.4046    88.25      87458.0
     18     524.1410  25.1138    224.18   2628.26   13.6393    193.83   2535.25      1.841    28.1002    86.65      48747.8
     19     546.2838  29.7474    233.37   2654.89   13.6393    193.83   2535.27      2.181    24.8953    86.72      65350.0
                                                                                                                  ---------
                                                                                                                   272991.0
     EMPRESARIOS AGRUPADOS, A.I.E.                                                                             PAGINA    14
                                                      **********************                           FECHA Sun Oct 31 2010
  GHESA INGENIERIA Y TECNOLOGIA, S.A                  *      HBAL-05       *
                                                      * ================== *
  DEPARTAMENTO DE ANALISIS MECANICOS                  **********************
  ==================================


               C.N.LAGUNA VERDE  120% carga  T.A CIRC 28低 incluye hasta msr                  



                LINEAS DE EXTRACCION DE TURBINA.-DIAGRAMA H-S.
                ==============================================

  2835.    ...............................................................................................................
           .          .          .          .          .          .          .          .          .          .          .
           .          .          .          .          .          .          .          .          .          .          .
           .          .          .          .          .          .          .          .          .          .          .
           .          .          .          .          .          .          .          .          .          .          .
  2805.    ...............................................................................................................
           .          .          .          .          .          .          .          .          .          .          .
           .          .          .          .          .          .          .          .      *   .   *      .          .
           .          .          .          .          .          .          .          *          .          .          .
           .          .          .          .          .          .          .  *       .          .          .          .
  2775.    .............................................................*.................................................
           .          .          .          .          .         *.      +   .          .          .          .          .
           .          .          .          .          . *        .          .          .          .          .          .
           .          .          .          .    *     .          .          .          .          .          .          .
           .          .          .        * .          .          .          .          .          .          .          .
  2745.    ...............................................................................................................
           .          .          .*         .          .          .          .          .          .          .          .
           .          .   *      .          .          .          .          .          .          .          .          .
           .          .          .          .          .          .          .          .          .          .          .
           .       *  .          .          .          .          .          .          .          .          .          .
  2715.    *..............................................................................................................
           .          .          .          .          .          .          .          .          .          .          .
           .          .          .          .          .          .          .          .          .          .          .
           .          .          .          .          .          .          .          .          .          .          .
           .          .          .          .          .          .          .          .          .          .          .
  2685.    ...............................................................................................................
           .          .          .          .          .          .          .          .          .          .          .
           .          .          .          .          .          .          .          .          .          .          .
           .          .          .          .          .          .          .          .          .          .          .
           .          .          .          .          .          .          .          .          .          .          .
  2655.    ......................................................................*........................................
           .          .          .          .          .          .          .  *       .          .          .          .
           .          .          .          .          .          .          .          .          .          .          .
           .          .          .          .          .          .          .          .          .          .          .
           .          .          .          .          .          .          .          .          .          .          .
  2625.    ........................................................................*......................................
           .          .          .          .          .          .          .   *      .          .          .          .
           .          .          .          .          .          .          .          .          .          .          .
           .          .          .          .          .          .          .          .          .          .          .
           .          .          .          .          .          .          .          .          .          .          .
  2595.    ...............................................................................................................
           .          .          .          .          .          .          .          .          .          .          .
           .          .          .          .          .          .          .          .          .          .          .
           .          .          .          .          .          .          .          .          .          .          .
           .          .          .          .          .          .          .          .          .          .          .
  2565.    ...............................................................................................................
           .          .          .          .          .          .          .          .          .          .          .
           .          .          .          .          .          .          .          .          .          .          .
           .          .          .          .          .          .          .          .          .          .          .
           .          .          .          .          .          .          .          .          .          .          .
  2535.    ...............................................................................+...............................

        5.57500    5.62500    5.67500    5.72500    5.77500    5.82500    5.87500    5.92500    5.97500    6.02500    6.07500
     EMPRESARIOS AGRUPADOS, A.I.E.                                                                             PAGINA    15
                                                      **********************                           FECHA Sun Oct 31 2010
  GHESA INGENIERIA Y TECNOLOGIA, S.A                  *      HBAL-05       *
                                                      * ================== *
  DEPARTAMENTO DE ANALISIS MECANICOS                  **********************
  ==================================


               C.N.LAGUNA VERDE  120% carga  T.A CIRC 28低 incluye hasta msr                  





                                        INFORMACION GENERAL DE SEPARADORES DE HUMEDAD


                            ENTRADA                         SALIDA VAPOR SECO              SALIDA DRENAJE
          -------------------------------------------- ---------------------------- ---------------------------
  EQUIPO    FLUJO    PRESION  TEMPER  ENTALPIA  TITULO    FLUJO    ENTALPIA  TITULO   FLUJO    ENTALPIA  TITULO  EFIC.  ARR.
    NO      (KG/S)   (BAR A.)  (C)    (KJ/KG)             (KG/S)   (KJ/KG)            (KG/S)   (KJ/KG)           (0/0) (0/0)

    14     594.8972    29.75  233.37   2651.36   0.916   593.6227   2654.89   0.918    1.2745   1006.14   0.000   2.55  0.00
    15     594.2123    25.11  224.18   2624.26   0.904   592.7845   2628.26   0.906    1.4278    963.09   0.000   2.50  0.00
    26     985.7618    13.35  192.83   2535.79   0.873   862.6822   2780.56   0.997  123.0795    820.17   0.000  98.00  0.00
     EMPRESARIOS AGRUPADOS, A.I.E.                                                                             PAGINA    16
                                                      **********************                           FECHA Sun Oct 31 2010
  GHESA INGENIERIA Y TECNOLOGIA, S.A                  *      HBAL-05       *
                                                      * ================== *
  DEPARTAMENTO DE ANALISIS MECANICOS                  **********************
  ==================================


               C.N.LAGUNA VERDE  120% carga  T.A CIRC 28低 incluye hasta msr                  





                                                INFORMACION GENERAL DE RECALENTADORES


                                                         VAPOR A RECALENTAR


                                ENTRADA                        SALIDA
                      ---------------------------   ---------------------------
   EQUIPO    FLUJO    PRESION  TEMPERAT  ENTALPIA   PRESION  TEMPERAT  ENTALPIA   CALOR ABSORBIDO   EFICIENCIA   LMTD   TTD
     NO     (KG/SG)    (BARA)    (C)      (KJ/KG)    (BARA)    (C)      (KJ/KG)         (KW)           (0/0)       C     C

     27    862.6822    13.349   192.83    2780.56    13.257   224.61    2869.46       76684.3         100.00    19.58   8.40
     28    862.6822    13.257   224.61    2869.46    13.040   271.80    2981.40       96576.4         100.00    25.86   9.30



                                                         VAPOR QUE RECALIENTA


                                ENTRADA                        SALIDA
                      ---------------------------   ---------------------------
   EQUIPO    FLUJO    PRESION  TEMPERAT  ENTALPIA   PRESION  TEMPERAT  ENTALPIA   CALOR CEDIDO  FACTORES DE TRANSFERENCIA
     NO     (KG/SG)    (BARA)    (C)      (KJ/KG)    (BARA)    (C)      (KJ/KG)       (KW)           UA          U

     27     47.3980    29.551   233.01    2611.67    28.362   230.75     993.79    76684.3       3915.        3915.    
     28     62.9504    65.278   281.10    2771.44    64.282   280.08    1237.27    96576.4       3735.        3735.    
     EMPRESARIOS AGRUPADOS, A.I.E.                                                                             PAGINA    17
                                                      **********************                           FECHA Sun Oct 31 2010
  GHESA INGENIERIA Y TECNOLOGIA, S.A                  *      HBAL-05       *
                                                      * ================== *
  DEPARTAMENTO DE ANALISIS MECANICOS                  **********************
  ==================================


               C.N.LAGUNA VERDE  120% carga  T.A CIRC 28低 incluye hasta msr                  


