     EMPRESARIOS AGRUPADOS, A.I.E.                                                                             PAGINA     1
                                                      **********************                           FECHA Thu Mar 10 2011
  GHESA INGENIERIA Y TECNOLOGIA, S.A                  * HBAL-06/ASME-1967  *
                                                      * ================== *
    DEPARTAMENTO MECANICA APLICADA                    **********************
  ==================================


              candu3                                                                          


         1         1         1         0         2         0    0        
  1.04366E+03  4.55100E+01  2.79320E+03  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00
         2         2         2         0         3        67    0        
  9.70280E-01  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00
         3         2         3         0         4        21    0        
  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00
         4         2         4         0         5        68    0        
  3.33330E-01  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00
         5         2         5         0         6        53    0        
  5.08056E-01  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00
         6         3         6         0         7         0    0        
  3.48000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00
         7         9         7         0         8         0    0        
  8.83500E-01  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00
         8         2         8         0         9        54    0        
  1.00000E-05  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00
         9         2         9         0        10        22    0        
  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00
        10         9        10         0        11         0    0        
  8.41000E-01  0.00000E+00  6.54700E+01  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00
        11         2        11         0        12        55    0        
  1.00000E-06  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00
        12         2        12         0        13        56    0        
  2.91943E+01  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00
        13         9        13         0        14         0    0        
  8.26000E-01  0.00000E+00  9.40689E+01  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00
        14         2        14         0        15        57    0        
  5.64578E+01  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00
        15         2        15         0        16        58    0        
  1.95777E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00
        16         3        16         0        17         0    0        
  9.56000E-02  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00
        17        13        17         0        18        59    0        
  9.50000E-01  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00
        18        14        18        61        19        60    0        
  9.46000E-02  0.00000E+00  0.00000E+00  0.00000E+00  1.39000E+01  1.00000E+00  2.91000E-01  0.00000E+00  0.00000E+00
        19        14        19        64        20        63    0        
  7.92000E-02  0.00000E+00  0.00000E+00  0.00000E+00  1.39000E+01  1.00000E+00  6.62000E-01  0.00000E+00  0.00000E+00
        20         3        20         0        25         0    0        
  2.00000E-01  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00
        21         3        21         0        24         0    0        
  1.36500E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00
        22         3        22         0        23         0    0        
  6.01000E-01  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00
        23         2        23         0        61        62    0        
  1.31944E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00
        24         2        24         0        64        65    0        
  2.44444E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00
        25         9        25         0        26         0    0        
  9.30400E-01  0.00000E+00  1.30940E+02  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00
     EMPRESARIOS AGRUPADOS, A.I.E.                                                                             PAGINA     2
                                                      **********************                           FECHA Thu Mar 10 2011
  GHESA INGENIERIA Y TECNOLOGIA, S.A                  * HBAL-06/ASME-1967  *
                                                      * ================== *
    DEPARTAMENTO MECANICA APLICADA                    **********************
  ==================================


              candu3                                                                          


        26         2        26         0        27        43    0        
  4.03577E+01  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00
        27         9        27         0        28         0    0        
  9.13600E-01  0.00000E+00  2.36820E+02  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00
        28         2        28         0        29        44    0        
  3.63923E+01  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00
        29         9        29         0        30         0    0        
  8.83500E-01  0.00000E+00  5.00600E+02  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00
        30        13        30         0        31        45    0        
  1.79670E-01  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00
        31         2        31         0        32        46    0        
  3.28321E+01  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00
        32         9        32         0        33         0    0        
  8.66000E-01  0.00000E+00  1.12113E+03  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00
        33        13        33         0        34        47    0        
  2.28500E-01  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00
        34         2        34         0        35        48    0        
  3.34222E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00
        35         9        35         0        36         0    0        
  8.61600E-01  0.00000E+00  1.76093E+03  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00
        36        13        36         0        37        49    0        
  2.37140E-01  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00
        37         2        37         0        38        50    0        
  3.41010E+01  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00
        38         9        38         0        39         0    0        
  8.59500E-01  0.00000E+00  2.70598E+03  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00
        39        13        39         0        40        51    0        
  2.38200E-01  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00
        40         2        40         0        41        52    0        
  3.03972E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00
        41         9        41         0        42         0    0        
  8.48000E-01  0.00000E+00  4.76916E+03  2.00000E+01  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  1.00000E+00
        42         8        42        71        66         0    0        
  4.03300E-02  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00
        43         5        51        52        69         0    0        
  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00
        44         5        67        69        70         0    0        
  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00
        45         5        87        70        71         0    0        
  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00
        46         1        73         0        72         0    0        
  2.49460E+00  4.23610E+00  2.60300E+03  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00
        47         5        50        49        74         0    0        
  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00
        48         5        47        48        75         0    0        
  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00
        49         5        74        75        76         0    0        
  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00
        50         5        45        46        77         0    0        
  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00
     EMPRESARIOS AGRUPADOS, A.I.E.                                                                             PAGINA     3
                                                      **********************                           FECHA Thu Mar 10 2011
  GHESA INGENIERIA Y TECNOLOGIA, S.A                  * HBAL-06/ASME-1967  *
                                                      * ================== *
    DEPARTAMENTO MECANICA APLICADA                    **********************
  ==================================


              candu3                                                                          


        51         3        66         0        78         0    0        
 -5.00000E-01  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00
        52         4        78         0        79         0    0        
  0.00000E+00  0.00000E+00  0.00000E+00  9.00000E-01  1.45961E+01  0.00000E+00  3.00000E+00  0.00000E+00  0.00000E+00
        53        15        79        68        80        82    0        
  1.13000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  1.00000E+00  1.01320E+00  0.00000E+00  0.00000E+00
        54        15        80        81        84        83    0        
  1.13000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  1.00000E+00  1.01320E+00  0.00000E+00  0.00000E+00
        55         5        82        83        85         0    0        
  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00
        56         5        85        86        87         0    0        
  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00
        57         2        72         0        81        86    0        
  1.07110E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00  0.00000E+00
     EMPRESARIOS AGRUPADOS, A.I.E.                                                                             PAGINA     4
                                                      **********************                           FECHA Thu Mar 10 2011
  GHESA INGENIERIA Y TECNOLOGIA, S.A                  * HBAL-06/ASME-1967  *
                                                      * ================== *
    DEPARTAMENTO MECANICA APLICADA                    **********************
  ==================================


              candu3                                                                          


PERDIDA EN ESCAPE EN FUNCION DE C.V (CURVAS DE ALSTOM)                          
   20   13    1
          0.00      17000.00      18000.00      19000.00      20000.00      21000.00      22000.00      23000.00      24000.00
      25000.00      26000.00      27000.00      28000.00      29000.00
          0.00         45.30         43.40         42.20         42.70         43.30         45.50         49.60         54.00
         60.20         68.30         76.30         86.00         98.50
     EMPRESARIOS AGRUPADOS, A.I.E.                                                                             PAGINA     5
                                                      **********************                           FECHA Thu Mar 10 2011
  GHESA INGENIERIA Y TECNOLOGIA, S.A                  * HBAL-06/ASME-1967  *
                                                      * ================== *
    DEPARTAMENTO MECANICA APLICADA                    **********************
  ==================================


              candu3                                                                          



                PERDIDA EN ESCAPE EN FUNCION DE C.V (CURVAS DE ALSTOM)                          


  102.0    ...............................................................................................................
           .          .          .          .          .          .          .          .          .          .          .
           .          .          .          .          .          .          .          .          .          .          .
           .          .          .          .          .          .          .          .          *          .          .
           .          .          .          .          .          .          .          .          .          .          .
  96.00    ...............................................................................................................
           .          .          .          .          .          .          .          .          .          .          .
           .          .          .          .          .          .          .          .          .          .          .
           .          .          .          .          .          .          .          .          .          .          .
           .          .          .          .          .          .          .          .          .          .          .
  90.00    ...............................................................................................................
           .          .          .          .          .          .          .          .          .          .          .
           .          .          .          .          .          .          .          .          .          .          .
           .          .          .          .          .          .          .          .          .          .          .
           .          .          .          .          .          .          .          .  *       .          .          .
  84.00    ...............................................................................................................
           .          .          .          .          .          .          .          .          .          .          .
           .          .          .          .          .          .          .          .          .          .          .
           .          .          .          .          .          .          .          .          .          .          .
           .          .          .          .          .          .          .          .          .          .          .
  78.00    ...............................................................................................................
           .          .          .          .          .          .          .          .          .          .          .
           .          .          .          .          .          .          .      *   .          .          .          .
           .          .          .          .          .          .          .          .          .          .          .
           .          .          .          .          .          .          .          .          .          .          .
  72.00    ...............................................................................................................
           .          .          .          .          .          .          .          .          .          .          .
           .          .          .          .          .          .          .          .          .          .          .
           .          .          .          .          .          .          .          .          .          .          .
           .          .          .          .          .          .          *          .          .          .          .
  66.00    ...............................................................................................................
           .          .          .          .          .          .          .          .          .          .          .
           .          .          .          .          .          .          .          .          .          .          .
           .          .          .          .          .          .          .          .          .          .          .
           .          .          .          .          .          .          .          .          .          .          .
  60.00    ..........................................................*....................................................
           .          .          .          .          .          .          .          .          .          .          .
           .          .          .          .          .          .          .          .          .          .          .
           .          .          .          .          .          .          .          .          .          .          .
           .          .          .          .          .          .          .          .          .          .          .
  54.00    ...................................................*...........................................................
           .          .          .          .          .          .          .          .          .          .          .
           .          .          .          .          .          .          .          .          .          .          .
           .          .          .          .          .          .          .          .          .          .          .
           .          .          .          .          *          .          .          .          .          .          .
  48.00    ...............................................................................................................
           .          .          .          .          .          .          .          .          .          .          .
           .          .          .          .          .          .          .          .          .          .          .
           *          .          .          .  *       .          .          .          .          .          .          .
           .      *   .          .      *   .          .          .          .          .          .          .          .
  42.00    ..............*.......*........................................................................................

     0.1700E+05 0.1850E+05 0.2000E+05 0.2150E+05 0.2300E+05 0.2450E+05 0.2600E+05 0.2750E+05 0.2900E+05 0.3050E+05 0.3200E+05
     EMPRESARIOS AGRUPADOS, A.I.E.                                                                             PAGINA     6
                                                      **********************                           FECHA Thu Mar 10 2011
  GHESA INGENIERIA Y TECNOLOGIA, S.A                  * HBAL-06/ASME-1967  *
                                                      * ================== *
    DEPARTAMENTO MECANICA APLICADA                    **********************
  ==================================


              candu3                                                                          



          LA CORRIENTE     1 ENTRA AL EQUIPO     1,
          LA CORRIENTE     2 SALE DEL EQUIPO     1 Y ENTRA AL EQUIPO     2
          LA CORRIENTE     3 SALE DEL EQUIPO     2 Y ENTRA AL EQUIPO     3
          LA CORRIENTE     4 SALE DEL EQUIPO     3 Y ENTRA AL EQUIPO     4
          LA CORRIENTE     5 SALE DEL EQUIPO     4 Y ENTRA AL EQUIPO     5
          LA CORRIENTE     6 SALE DEL EQUIPO     5 Y ENTRA AL EQUIPO     6
          LA CORRIENTE     7 SALE DEL EQUIPO     6 Y ENTRA AL EQUIPO     7
          LA CORRIENTE     8 SALE DEL EQUIPO     7 Y ENTRA AL EQUIPO     8
          LA CORRIENTE     9 SALE DEL EQUIPO     8 Y ENTRA AL EQUIPO     9
          LA CORRIENTE    10 SALE DEL EQUIPO     9 Y ENTRA AL EQUIPO    10
          LA CORRIENTE    11 SALE DEL EQUIPO    10 Y ENTRA AL EQUIPO    11
          LA CORRIENTE    12 SALE DEL EQUIPO    11 Y ENTRA AL EQUIPO    12
          LA CORRIENTE    13 SALE DEL EQUIPO    12 Y ENTRA AL EQUIPO    13
          LA CORRIENTE    14 SALE DEL EQUIPO    13 Y ENTRA AL EQUIPO    14
          LA CORRIENTE    15 SALE DEL EQUIPO    14 Y ENTRA AL EQUIPO    15
          LA CORRIENTE    16 SALE DEL EQUIPO    15 Y ENTRA AL EQUIPO    16
          LA CORRIENTE    17 SALE DEL EQUIPO    16 Y ENTRA AL EQUIPO    17
          LA CORRIENTE    18 SALE DEL EQUIPO    17 Y ENTRA AL EQUIPO    18
          LA CORRIENTE    19 SALE DEL EQUIPO    18 Y ENTRA AL EQUIPO    19
          LA CORRIENTE    20 SALE DEL EQUIPO    19 Y ENTRA AL EQUIPO    20
          LA CORRIENTE    21 SALE DEL EQUIPO     3 Y ENTRA AL EQUIPO    21
          LA CORRIENTE    22 SALE DEL EQUIPO     9 Y ENTRA AL EQUIPO    22
          LA CORRIENTE    23 SALE DEL EQUIPO    22 Y ENTRA AL EQUIPO    23
          LA CORRIENTE    24 SALE DEL EQUIPO    21 Y ENTRA AL EQUIPO    24
          LA CORRIENTE    25 SALE DEL EQUIPO    20 Y ENTRA AL EQUIPO    25
          LA CORRIENTE    26 SALE DEL EQUIPO    25 Y ENTRA AL EQUIPO    26
          LA CORRIENTE    27 SALE DEL EQUIPO    26 Y ENTRA AL EQUIPO    27
          LA CORRIENTE    28 SALE DEL EQUIPO    27 Y ENTRA AL EQUIPO    28
          LA CORRIENTE    29 SALE DEL EQUIPO    28 Y ENTRA AL EQUIPO    29
          LA CORRIENTE    30 SALE DEL EQUIPO    29 Y ENTRA AL EQUIPO    30
          LA CORRIENTE    31 SALE DEL EQUIPO    30 Y ENTRA AL EQUIPO    31
          LA CORRIENTE    32 SALE DEL EQUIPO    31 Y ENTRA AL EQUIPO    32
          LA CORRIENTE    33 SALE DEL EQUIPO    32 Y ENTRA AL EQUIPO    33
          LA CORRIENTE    34 SALE DEL EQUIPO    33 Y ENTRA AL EQUIPO    34
          LA CORRIENTE    35 SALE DEL EQUIPO    34 Y ENTRA AL EQUIPO    35
          LA CORRIENTE    36 SALE DEL EQUIPO    35 Y ENTRA AL EQUIPO    36
          LA CORRIENTE    37 SALE DEL EQUIPO    36 Y ENTRA AL EQUIPO    37
          LA CORRIENTE    38 SALE DEL EQUIPO    37 Y ENTRA AL EQUIPO    38
          LA CORRIENTE    39 SALE DEL EQUIPO    38 Y ENTRA AL EQUIPO    39
          LA CORRIENTE    40 SALE DEL EQUIPO    39 Y ENTRA AL EQUIPO    40
          LA CORRIENTE    41 SALE DEL EQUIPO    40 Y ENTRA AL EQUIPO    41
          LA CORRIENTE    42 SALE DEL EQUIPO    41 Y ENTRA AL EQUIPO    42

          LA CORRIENTE    43 SALE DEL EQUIPO    26,

          LA CORRIENTE    44 SALE DEL EQUIPO    28,
          LA CORRIENTE    45 SALE DEL EQUIPO    30 Y ENTRA AL EQUIPO    50
          LA CORRIENTE    46 SALE DEL EQUIPO    31 Y ENTRA AL EQUIPO    50
          LA CORRIENTE    47 SALE DEL EQUIPO    33 Y ENTRA AL EQUIPO    48
     EMPRESARIOS AGRUPADOS, A.I.E.                                                                             PAGINA     7
                                                      **********************                           FECHA Thu Mar 10 2011
  GHESA INGENIERIA Y TECNOLOGIA, S.A                  * HBAL-06/ASME-1967  *
                                                      * ================== *
    DEPARTAMENTO MECANICA APLICADA                    **********************
  ==================================


              candu3                                                                          


          LA CORRIENTE    48 SALE DEL EQUIPO    34 Y ENTRA AL EQUIPO    48
          LA CORRIENTE    49 SALE DEL EQUIPO    36 Y ENTRA AL EQUIPO    47
          LA CORRIENTE    50 SALE DEL EQUIPO    37 Y ENTRA AL EQUIPO    47
          LA CORRIENTE    51 SALE DEL EQUIPO    39 Y ENTRA AL EQUIPO    43
          LA CORRIENTE    52 SALE DEL EQUIPO    40 Y ENTRA AL EQUIPO    43

          LA CORRIENTE    53 SALE DEL EQUIPO     5,

          LA CORRIENTE    54 SALE DEL EQUIPO     8,

          LA CORRIENTE    55 SALE DEL EQUIPO    11,

          LA CORRIENTE    56 SALE DEL EQUIPO    12,

          LA CORRIENTE    57 SALE DEL EQUIPO    14,

          LA CORRIENTE    58 SALE DEL EQUIPO    15,

          LA CORRIENTE    59 SALE DEL EQUIPO    17,

          LA CORRIENTE    60 SALE DEL EQUIPO    18,
          LA CORRIENTE    61 SALE DEL EQUIPO    23 Y ENTRA AL EQUIPO    18

          LA CORRIENTE    62 SALE DEL EQUIPO    23,

          LA CORRIENTE    63 SALE DEL EQUIPO    19,
          LA CORRIENTE    64 SALE DEL EQUIPO    24 Y ENTRA AL EQUIPO    19

          LA CORRIENTE    65 SALE DEL EQUIPO    24,
          LA CORRIENTE    66 SALE DEL EQUIPO    42 Y ENTRA AL EQUIPO    51
          LA CORRIENTE    67 SALE DEL EQUIPO     2 Y ENTRA AL EQUIPO    44
          LA CORRIENTE    68 SALE DEL EQUIPO     4 Y ENTRA AL EQUIPO    53
          LA CORRIENTE    69 SALE DEL EQUIPO    43 Y ENTRA AL EQUIPO    44
          LA CORRIENTE    70 SALE DEL EQUIPO    44 Y ENTRA AL EQUIPO    45
          LA CORRIENTE    71 SALE DEL EQUIPO    45 Y ENTRA AL EQUIPO    42
          LA CORRIENTE    72 SALE DEL EQUIPO    46 Y ENTRA AL EQUIPO    57

          LA CORRIENTE    73 ENTRA AL EQUIPO    46,
          LA CORRIENTE    74 SALE DEL EQUIPO    47 Y ENTRA AL EQUIPO    49
          LA CORRIENTE    75 SALE DEL EQUIPO    48 Y ENTRA AL EQUIPO    49

          LA CORRIENTE    76 SALE DEL EQUIPO    49,

          LA CORRIENTE    77 SALE DEL EQUIPO    50,
          LA CORRIENTE    78 SALE DEL EQUIPO    51 Y ENTRA AL EQUIPO    52
          LA CORRIENTE    79 SALE DEL EQUIPO    52 Y ENTRA AL EQUIPO    53
          LA CORRIENTE    80 SALE DEL EQUIPO    53 Y ENTRA AL EQUIPO    54
          LA CORRIENTE    81 SALE DEL EQUIPO    57 Y ENTRA AL EQUIPO    54
          LA CORRIENTE    82 SALE DEL EQUIPO    53 Y ENTRA AL EQUIPO    55
          LA CORRIENTE    83 SALE DEL EQUIPO    54 Y ENTRA AL EQUIPO    55
     EMPRESARIOS AGRUPADOS, A.I.E.                                                                             PAGINA     8
                                                      **********************                           FECHA Thu Mar 10 2011
  GHESA INGENIERIA Y TECNOLOGIA, S.A                  * HBAL-06/ASME-1967  *
                                                      * ================== *
    DEPARTAMENTO MECANICA APLICADA                    **********************
  ==================================


              candu3                                                                          



          LA CORRIENTE    84 SALE DEL EQUIPO    54,
          LA CORRIENTE    85 SALE DEL EQUIPO    55 Y ENTRA AL EQUIPO    56
          LA CORRIENTE    86 SALE DEL EQUIPO    57 Y ENTRA AL EQUIPO    56
          LA CORRIENTE    87 SALE DEL EQUIPO    56 Y ENTRA AL EQUIPO    45
     EMPRESARIOS AGRUPADOS, A.I.E.                                                                             PAGINA     9
                                                      **********************                           FECHA Thu Mar 10 2011
  GHESA INGENIERIA Y TECNOLOGIA, S.A                  * HBAL-06/ASME-1967  *
                                                      * ================== *
    DEPARTAMENTO MECANICA APLICADA                    **********************
  ==================================


              candu3                                                                          


          LA CORRIENTE     1 NO SALE DE NINGUN EQUIPO
            NO OBSTANTE LA CONFIGURACION PUEDE SER VALIDA

          LA CORRIENTE    43 NO ENTRA A NINGUN EQUIPO
            NO OBSTANTE LA CONFIGURACION PUEDE SER VALIDA

          LA CORRIENTE    44 NO ENTRA A NINGUN EQUIPO
            NO OBSTANTE LA CONFIGURACION PUEDE SER VALIDA

          LA CORRIENTE    53 NO ENTRA A NINGUN EQUIPO
            NO OBSTANTE LA CONFIGURACION PUEDE SER VALIDA

          LA CORRIENTE    54 NO ENTRA A NINGUN EQUIPO
            NO OBSTANTE LA CONFIGURACION PUEDE SER VALIDA

          LA CORRIENTE    55 NO ENTRA A NINGUN EQUIPO
            NO OBSTANTE LA CONFIGURACION PUEDE SER VALIDA

          LA CORRIENTE    56 NO ENTRA A NINGUN EQUIPO
            NO OBSTANTE LA CONFIGURACION PUEDE SER VALIDA

          LA CORRIENTE    57 NO ENTRA A NINGUN EQUIPO
            NO OBSTANTE LA CONFIGURACION PUEDE SER VALIDA

          LA CORRIENTE    58 NO ENTRA A NINGUN EQUIPO
            NO OBSTANTE LA CONFIGURACION PUEDE SER VALIDA

          LA CORRIENTE    59 NO ENTRA A NINGUN EQUIPO
            NO OBSTANTE LA CONFIGURACION PUEDE SER VALIDA

          LA CORRIENTE    60 NO ENTRA A NINGUN EQUIPO
            NO OBSTANTE LA CONFIGURACION PUEDE SER VALIDA

          LA CORRIENTE    62 NO ENTRA A NINGUN EQUIPO
            NO OBSTANTE LA CONFIGURACION PUEDE SER VALIDA

          LA CORRIENTE    63 NO ENTRA A NINGUN EQUIPO
            NO OBSTANTE LA CONFIGURACION PUEDE SER VALIDA

          LA CORRIENTE    65 NO ENTRA A NINGUN EQUIPO
            NO OBSTANTE LA CONFIGURACION PUEDE SER VALIDA

          LA CORRIENTE    73 NO SALE DE NINGUN EQUIPO
            NO OBSTANTE LA CONFIGURACION PUEDE SER VALIDA

          LA CORRIENTE    76 NO ENTRA A NINGUN EQUIPO
            NO OBSTANTE LA CONFIGURACION PUEDE SER VALIDA

          LA CORRIENTE    77 NO ENTRA A NINGUN EQUIPO
            NO OBSTANTE LA CONFIGURACION PUEDE SER VALIDA

          LA CORRIENTE    84 NO ENTRA A NINGUN EQUIPO
            NO OBSTANTE LA CONFIGURACION PUEDE SER VALIDA

     EMPRESARIOS AGRUPADOS, A.I.E.                                                                             PAGINA    10
                                                      **********************                           FECHA Thu Mar 10 2011
  GHESA INGENIERIA Y TECNOLOGIA, S.A                  * HBAL-06/ASME-1967  *
                                                      * ================== *
    DEPARTAMENTO MECANICA APLICADA                    **********************
  ==================================


              candu3                                                                          


 EL EQUIPO       1 GENERA LAS ECUACIONES     1 --     6
 EL EQUIPO       2 GENERA LAS ECUACIONES     7 --    12
 EL EQUIPO       3 GENERA LAS ECUACIONES    13 --    17
 EL EQUIPO       4 GENERA LAS ECUACIONES    18 --    23
 EL EQUIPO       5 GENERA LAS ECUACIONES    24 --    29
 EL EQUIPO       6 GENERA LAS ECUACIONES    30 --    32
 EL EQUIPO       7 GENERA LAS ECUACIONES    33 --    34
 EL EQUIPO       8 GENERA LAS ECUACIONES    35 --    40
 EL EQUIPO       9 GENERA LAS ECUACIONES    41 --    45
 EL EQUIPO      10 GENERA LAS ECUACIONES    46 --    48
 EL EQUIPO      11 GENERA LAS ECUACIONES    49 --    54
 EL EQUIPO      12 GENERA LAS ECUACIONES    55 --    60
 EL EQUIPO      13 GENERA LAS ECUACIONES    61 --    63
 EL EQUIPO      14 GENERA LAS ECUACIONES    64 --    69
 EL EQUIPO      15 GENERA LAS ECUACIONES    70 --    75
 EL EQUIPO      16 GENERA LAS ECUACIONES    76 --    78
 EL EQUIPO      17 GENERA LAS ECUACIONES    79 --    84
 EL EQUIPO      18 GENERA LAS ECUACIONES    85 --    91
 EL EQUIPO      19 GENERA LAS ECUACIONES    92 --    98
 EL EQUIPO      20 GENERA LAS ECUACIONES    99 --   101
 EL EQUIPO      21 GENERA LAS ECUACIONES   102 --   104
 EL EQUIPO      22 GENERA LAS ECUACIONES   105 --   107
 EL EQUIPO      23 GENERA LAS ECUACIONES   108 --   113
 EL EQUIPO      24 GENERA LAS ECUACIONES   114 --   119
 EL EQUIPO      25 GENERA LAS ECUACIONES   120 --   122
 EL EQUIPO      26 GENERA LAS ECUACIONES   123 --   128
 EL EQUIPO      27 GENERA LAS ECUACIONES   129 --   131
 EL EQUIPO      28 GENERA LAS ECUACIONES   132 --   137
 EL EQUIPO      29 GENERA LAS ECUACIONES   138 --   140
 EL EQUIPO      30 GENERA LAS ECUACIONES   141 --   146
 EL EQUIPO      31 GENERA LAS ECUACIONES   147 --   152
 EL EQUIPO      32 GENERA LAS ECUACIONES   153 --   155
 EL EQUIPO      33 GENERA LAS ECUACIONES   156 --   161
 EL EQUIPO      34 GENERA LAS ECUACIONES   162 --   167
 EL EQUIPO      35 GENERA LAS ECUACIONES   168 --   170
 EL EQUIPO      36 GENERA LAS ECUACIONES   171 --   176
 EL EQUIPO      37 GENERA LAS ECUACIONES   177 --   182
 EL EQUIPO      38 GENERA LAS ECUACIONES   183 --   185
 EL EQUIPO      39 GENERA LAS ECUACIONES   186 --   191
 EL EQUIPO      40 GENERA LAS ECUACIONES   192 --   197
 EL EQUIPO      41 GENERA LAS ECUACIONES   198 --   200
 EL EQUIPO      42 GENERA LAS ECUACIONES   201 --   204
 EL EQUIPO      43 GENERA LAS ECUACIONES   205 --   207
 EL EQUIPO      44 GENERA LAS ECUACIONES   208 --   210
 EL EQUIPO      45 GENERA LAS ECUACIONES   211 --   213
 EL EQUIPO      46 GENERA LAS ECUACIONES   214 --   219
 EL EQUIPO      47 GENERA LAS ECUACIONES   220 --   222
 EL EQUIPO      48 GENERA LAS ECUACIONES   223 --   225
 EL EQUIPO      49 GENERA LAS ECUACIONES   226 --   228
 EL EQUIPO      50 GENERA LAS ECUACIONES   229 --   231
     EMPRESARIOS AGRUPADOS, A.I.E.                                                                             PAGINA    11
                                                      **********************                           FECHA Thu Mar 10 2011
  GHESA INGENIERIA Y TECNOLOGIA, S.A                  * HBAL-06/ASME-1967  *
                                                      * ================== *
    DEPARTAMENTO MECANICA APLICADA                    **********************
  ==================================


              candu3                                                                          


 EL EQUIPO      51 GENERA LAS ECUACIONES   232 --   234
 EL EQUIPO      52 GENERA LAS ECUACIONES   235 --   237
 EL EQUIPO      53 GENERA LAS ECUACIONES   238 --   243
 EL EQUIPO      54 GENERA LAS ECUACIONES   244 --   249
 EL EQUIPO      55 GENERA LAS ECUACIONES   250 --   252
 EL EQUIPO      56 GENERA LAS ECUACIONES   253 --   255
 EL EQUIPO      57 GENERA LAS ECUACIONES   256 --   261
     EMPRESARIOS AGRUPADOS, A.I.E.                                                                             PAGINA    12
                                                      **********************                           FECHA Thu Mar 10 2011
  GHESA INGENIERIA Y TECNOLOGIA, S.A                  * HBAL-06/ASME-1967  *
                                                      * ================== *
    DEPARTAMENTO MECANICA APLICADA                    **********************
  ==================================


              candu3                                                                          


                  PRESION     84
 CORRIENTE NUMERO     1 --------  1.04366000E+03 4.55100000E+01 2.79320000E+03
 CORRIENTE NUMERO     2 --------  1.04366000E+03 4.55100000E+01 2.79320000E+03
 CORRIENTE NUMERO     3 --------  1.04268972E+03 4.55100000E+01 2.79320000E+03
 CORRIENTE NUMERO     4 --------  9.91005446E+02 4.55100000E+01 2.79320000E+03
 CORRIENTE NUMERO     5 --------  9.90672116E+02 4.55100000E+01 2.79320000E+03
 CORRIENTE NUMERO     6 --------  9.90164060E+02 4.55100000E+01 2.79320000E+03
 CORRIENTE NUMERO     7 --------  9.90164060E+02 4.20300000E+01 2.79320000E+03
 CORRIENTE NUMERO     8 --------  9.90164053E+02 2.00114350E+01 2.66796110E+03
 CORRIENTE NUMERO     9 --------  9.90164043E+02 2.00114350E+01 2.66796110E+03
 CORRIENTE NUMERO    10 --------  9.61660220E+02 2.00114350E+01 2.66796110E+03
 CORRIENTE NUMERO    11 --------  9.61660230E+02 1.32493850E+01 2.60500630E+03
 CORRIENTE NUMERO    12 --------  9.61660220E+02 1.32493850E+01 2.60500630E+03
 CORRIENTE NUMERO    13 --------  9.32465920E+02 1.32493850E+01 2.60500630E+03
 CORRIENTE NUMERO    14 --------  9.32465920E+02 9.55311040E+00 2.55760890E+03
 CORRIENTE NUMERO    15 --------  8.76008120E+02 9.55311040E+00 2.55760890E+03
 CORRIENTE NUMERO    16 --------  8.74050350E+02 9.55311040E+00 2.55760890E+03
 CORRIENTE NUMERO    17 --------  8.74050347E+02 9.45751040E+00 2.55760890E+03
 CORRIENTE NUMERO    18 --------  7.85169900E+02 9.45751040E+00 2.76200510E+03
 CORRIENTE NUMERO    19 --------  7.85169900E+02 9.36291040E+00 2.82327700E+03
 CORRIENTE NUMERO    20 --------  7.85169900E+02 9.28371040E+00 2.92871810E+03
 CORRIENTE NUMERO    21 --------  5.16842790E+01 4.55100000E+01 2.79320000E+03
 CORRIENTE NUMERO    22 --------  2.85038230E+01 2.00114350E+01 2.66796110E+03
 CORRIENTE NUMERO    23 --------  2.85038230E+01 1.94104350E+01 2.66796110E+03
 CORRIENTE NUMERO    24 --------  5.16842790E+01 4.41450000E+01 2.79320000E+03
 CORRIENTE NUMERO    25 --------  7.85169900E+02 9.08371040E+00 2.92871810E+03
 CORRIENTE NUMERO    26 --------  7.85169900E+02 4.40769430E+00 2.78656540E+03
 CORRIENTE NUMERO    27 --------  7.44812200E+02 4.40769430E+00 2.78656540E+03
 CORRIENTE NUMERO    28 --------  7.44812200E+02 1.85313350E+00 2.64328150E+03
 CORRIENTE NUMERO    29 --------  7.08419900E+02 1.85313350E+00 2.64328150E+03
 CORRIENTE NUMERO    30 --------  7.08419904E+02 7.45969370E-01 2.51264350E+03
 CORRIENTE NUMERO    31 --------  7.00034580E+02 7.45969370E-01 2.53814310E+03
 CORRIENTE NUMERO    32 --------  6.67202480E+02 7.45969370E-01 2.53814310E+03
 CORRIENTE NUMERO    33 --------  6.67202482E+02 4.56743840E-01 2.47323080E+03
 CORRIENTE NUMERO    34 --------  6.56051490E+02 4.56743840E-01 2.50963960E+03
 CORRIENTE NUMERO    35 --------  6.52709270E+02 4.56743840E-01 2.50963960E+03
 CORRIENTE NUMERO    36 --------  6.52709269E+02 2.71631660E-01 2.44358210E+03
 CORRIENTE NUMERO    37 --------  6.40945760E+02 2.71631660E-01 2.48329460E+03
 CORRIENTE NUMERO    38 --------  6.06844760E+02 2.71631660E-01 2.48329460E+03
 CORRIENTE NUMERO    39 --------  6.06844759E+02 1.47382120E-01 2.40868820E+03
 CORRIENTE NUMERO    40 --------  5.95283380E+02 1.47382120E-01 2.45110970E+03
 CORRIENTE NUMERO    41 --------  5.92243660E+02 1.47382120E-01 2.45110970E+03
 CORRIENTE NUMERO    42 --------  5.92243660E+02 4.03300000E-02 2.34467690E+03
 CORRIENTE NUMERO    43 --------  4.03577000E+01 4.40769430E+00 2.78656540E+03
 CORRIENTE NUMERO    44 --------  3.63923000E+01 1.85313350E+00 2.64328150E+03
 CORRIENTE NUMERO    45 --------  8.38532440E+00 7.45969370E-01 3.83847920E+02
 CORRIENTE NUMERO    46 --------  3.28321000E+01 7.45969370E-01 2.53814310E+03
 CORRIENTE NUMERO    47 --------  1.11509920E+01 4.56743840E-01 3.31171500E+02
 CORRIENTE NUMERO    48 --------  3.34222000E+00 4.56743840E-01 2.50963960E+03
 CORRIENTE NUMERO    49 --------  1.17635090E+01 2.71631660E-01 2.79808780E+02
 CORRIENTE NUMERO    50 --------  3.41010000E+01 2.71631660E-01 2.48329460E+03
     EMPRESARIOS AGRUPADOS, A.I.E.                                                                             PAGINA    13
                                                      **********************                           FECHA Thu Mar 10 2011
  GHESA INGENIERIA Y TECNOLOGIA, S.A                  * HBAL-06/ASME-1967  *
                                                      * ================== *
    DEPARTAMENTO MECANICA APLICADA                    **********************
  ==================================


              candu3                                                                          


 CORRIENTE NUMERO    51 --------  1.15613790E+01 1.47382120E-01 2.24448610E+02
 CORRIENTE NUMERO    52 --------  3.03972000E+00 1.47382120E-01 2.45110970E+03
 CORRIENTE NUMERO    53 --------  5.08056000E-01 4.55100000E+01 2.79320000E+03
 CORRIENTE NUMERO    54 --------  1.00000000E-05 2.00114350E+01 2.66796110E+03
 CORRIENTE NUMERO    55 --------  1.00000000E-05 1.32493850E+01 2.60500630E+03
 CORRIENTE NUMERO    56 --------  2.91943000E+01 1.32493850E+01 2.60500630E+03
 CORRIENTE NUMERO    57 --------  5.64578000E+01 9.55311040E+00 2.55760890E+03
 CORRIENTE NUMERO    58 --------  1.95777000E+00 9.55311040E+00 2.55760890E+03
 CORRIENTE NUMERO    59 --------  8.88804470E+01 9.45751040E+00 7.51972760E+02
 CORRIENTE NUMERO    60 --------  2.71843830E+01 1.91194350E+01 8.98237040E+02
 CORRIENTE NUMERO    61 --------  2.71843830E+01 1.94104350E+01 2.66796110E+03
 CORRIENTE NUMERO    62 --------  1.31944000E+00 1.94104350E+01 2.66796110E+03
 CORRIENTE NUMERO    63 --------  4.92398390E+01 4.34830000E+01 1.11185410E+03
 CORRIENTE NUMERO    64 --------  4.92398390E+01 4.41450000E+01 2.79320000E+03
 CORRIENTE NUMERO    65 --------  2.44444000E+00 4.41450000E+01 2.79320000E+03
 CORRIENTE NUMERO    66 --------  7.48458040E+02 4.03300000E-02 1.22005710E+02
 CORRIENTE NUMERO    67 --------  9.70280000E-01 4.55100000E+01 2.79320000E+03
 CORRIENTE NUMERO    68 --------  3.33330000E-01 4.55100000E+01 2.79320000E+03
 CORRIENTE NUMERO    69 --------  1.46010990E+01 1.47382120E-01 6.88004560E+02
 CORRIENTE NUMERO    70 --------  1.55713790E+01 4.55100000E+01 8.19183000E+02
 CORRIENTE NUMERO    71 --------  1.56214380E+02 2.55300000E-01 2.41552700E+02
 CORRIENTE NUMERO    72 --------  2.49460000E+00 4.23610000E+00 2.60300000E+03
 CORRIENTE NUMERO    73 --------  2.49460000E+00 4.23610000E+00 2.60300000E+03
 CORRIENTE NUMERO    74 --------  4.58645090E+01 2.71631660E-01 1.91813550E+03
 CORRIENTE NUMERO    75 --------  1.44932120E+01 4.56743840E-01 8.33538492E+02
 CORRIENTE NUMERO    76 --------  6.03577210E+01 2.71631660E-01 1.65769971E+03
 CORRIENTE NUMERO    77 --------  4.12174244E+01 7.45969370E-01 2.09987008E+03
 CORRIENTE NUMERO    78 --------  7.48458040E+02 3.83134995E-02 1.22005710E+02
 CORRIENTE NUMERO    79 --------  7.48458040E+02 1.91567498E+00 1.23225766E+02
 CORRIENTE NUMERO    80 --------  7.48458040E+02 7.85674976E-01 1.25453929E+02
 CORRIENTE NUMERO    81 --------  1.42350000E+00 4.23610000E+00 2.60300000E+03
 CORRIENTE NUMERO    82 --------  3.33330000E-01 4.55100000E+01 1.12551339E+03
 CORRIENTE NUMERO    83 --------  1.42350000E+00 4.23610000E+00 1.01629877E+03
 CORRIENTE NUMERO    84 --------  7.48458040E+02 3.06896552E+01 1.27573889E+02
 CORRIENTE NUMERO    85 --------  1.75683000E+00 4.55100000E+01 1.03701457E+03
 CORRIENTE NUMERO    86 --------  1.07110000E+00 4.23610000E+00 2.60300000E+03
 CORRIENTE NUMERO    87 --------  1.40643001E+02 2.55300000E-01 1.77599983E+02
     EMPRESARIOS AGRUPADOS, A.I.E.                                                                             PAGINA    14
                                                      **********************                           FECHA Thu Mar 10 2011
  GHESA INGENIERIA Y TECNOLOGIA, S.A                  * HBAL-06/ASME-1967  *
                                                      * ================== *
    DEPARTAMENTO MECANICA APLICADA                    **********************
  ==================================


              candu3                                                                          


 NUMERO DE NO CEROS EN LA MATRIZ=       900

                         ITERACION NUMERO    1 ERROR MAXIMO   1.613951E+01 (RELATIVO Y EN VALOR ABSOLUTO)
                                LA VARIABLE CON ERRMAX ES P(  80)
 NUMERO DE NO CEROS EN LA MATRIZ=       900

                         ITERACION NUMERO    2 ERROR MAXIMO   5.205697E+00 (RELATIVO Y EN VALOR ABSOLUTO)
                                LA VARIABLE CON ERRMAX ES H(  87)
 NUMERO DE NO CEROS EN LA MATRIZ=       900

                         ITERACION NUMERO    3 ERROR MAXIMO   1.570526E-11 (RELATIVO Y EN VALOR ABSOLUTO)
                                LA VARIABLE CON ERRMAX ES H(  71)
     EMPRESARIOS AGRUPADOS, A.I.E.                                                                             PAGINA    15
                                                      **********************                           FECHA Thu Mar 10 2011
  GHESA INGENIERIA Y TECNOLOGIA, S.A                  * HBAL-06/ASME-1967  *
                                                      * ================== *
    DEPARTAMENTO MECANICA APLICADA                    **********************
  ==================================


              candu3                                                                          


      CORR     CAUDAL         TEMPERATURA        PRESION       VOL ESPECIFICO      ENTALPIA         ENTROPIA          TITULO
       NO     (KGS/SG)            (C)             (BARA)          (M**3/KG)        (KJ/KG)         (KJ/KG/C) 


        1     1043.6600          258.1           45.5100           0.043417         2793.2           6.00644          0.9975
        2     1043.6600          258.1           45.5100           0.043417         2793.2           6.00644          0.9975
        3     1042.6897          258.1           45.5100           0.043417         2793.2           6.00644          0.9975
        4      991.0054          258.1           45.5100           0.043417         2793.2           6.00644          0.9975
        5      990.6721          258.1           45.5100           0.043417         2793.2           6.00644          0.9975
        6      990.1641          258.1           45.5100           0.043417         2793.2           6.00644          0.9975
        7      990.1641          253.3           42.0300           0.047105         2793.2           6.03619          0.9964
        8      990.1641          212.4           20.0114           0.092751         2668.0           6.07020          0.9315
        9      990.1640          212.4           20.0114           0.092751         2668.0           6.07020          0.9315
       10      961.6602          212.4           20.0114           0.092751         2668.0           6.07020          0.9315
       11      961.6602          192.5           13.2494           0.134841         2605.0           6.09576          0.9080
       12      961.6602          192.5           13.2494           0.134841         2605.0           6.09576          0.9080
       13      932.4659          192.5           13.2494           0.134841         2605.0           6.09576          0.9080
       14      932.4659          177.9            9.5531           0.181292         2557.6           6.11790          0.8927
       15      876.0081          177.9            9.5531           0.181292         2557.6           6.11790          0.8927
       16      874.0504          177.9            9.5531           0.181292         2557.6           6.11790          0.8927
       17      874.0504          177.5            9.4575           0.183092         2557.6           6.12176          0.8930
       18      785.1699          177.5            9.4575           0.203691         2762.0           6.57535          0.9940
       19      785.1699          197.0            9.3629           0.219064         2823.3           6.71340          1.0000
       20      785.1699          242.3            9.2837           0.247175         2928.7           6.93140          1.0000
       21       51.6843          258.1           45.5100           0.043417         2793.2           6.00644          0.9975
       22       28.5038          212.4           20.0114           0.092751         2668.0           6.07020          0.9315
       23       28.5038          210.9           19.4104           0.095614         2668.0           6.08188          0.9321
       24       51.6843          256.2           44.1450           0.044796         2793.2           6.01779          0.9970
       25      785.1699          242.0            9.0837           0.252628         2928.7           6.94110          1.0000
       26      785.1699          167.0            4.4077           0.445610         2786.6           6.96540          1.0000
       27      744.8122          167.0            4.4077           0.445610         2786.6           6.96540          1.0000
       28      744.8122          117.8            1.8531           0.925352         2643.3           7.00005          0.9730
       29      708.4199          117.8            1.8531           0.925352         2643.3           7.00005          0.9730
       30      708.4199           91.6            0.7460           2.081368         2512.6           7.04728          0.9341
       31      700.0346           91.6            0.7460           2.106287         2538.1           7.11718          0.9453
       32      667.2025           91.6            0.7460           2.106287         2538.1           7.11718          0.9453
       33      667.2025           79.1            0.4567           3.268887         2473.2           7.14569          0.9269
       34      656.0515           79.1            0.4567           3.324431         2509.6           7.24905          0.9426
       35      652.7093           79.1            0.4567           3.324431         2509.6           7.24905          0.9426
       36      652.7093           66.9            0.2716           5.303680         2443.6           7.28026          0.9240
       37      640.9458           66.9            0.2716           5.401002         2483.3           7.39706          0.9410
       38      606.8448           66.9            0.2716           5.401002         2483.3           7.39706          0.9410
       39      606.8448           53.6            0.1474           9.375096         2408.7           7.43438          0.9200
       40      595.2834           53.6            0.1474           9.557156         2451.1           7.56420          0.9379
       41      592.2437           53.6            0.1474           9.557156         2451.1           7.56420          0.9379
       42      592.2437           29.1            0.0403          31.551163         2344.7           7.77752          0.9136
       43       40.3577          167.0            4.4077           0.445610         2786.6           6.96540          1.0000
       44       36.3923          117.8            1.8531           0.925352         2643.3           7.00005          0.9730
       45        8.3853           91.6            0.7460           0.001037          383.8           1.21150          0.0000
       46       32.8321           91.6            0.7460           2.106287         2538.1           7.11718          0.9453
       47       11.1510           79.1            0.4567           0.001029          331.2           1.06464          0.0000
       48        3.3422           79.1            0.4567           3.324431         2509.6           7.24905          0.9426
       49       11.7635           66.9            0.2716           0.001021          279.8           0.91629          0.0000
       50       34.1010           66.9            0.2716           5.401002         2483.3           7.39706          0.9410
       51       11.5614           53.6            0.1474           0.001014          224.4           0.75026          0.0000
     EMPRESARIOS AGRUPADOS, A.I.E.                                                                             PAGINA    16
                                                      **********************                           FECHA Thu Mar 10 2011
  GHESA INGENIERIA Y TECNOLOGIA, S.A                  * HBAL-06/ASME-1967  *
                                                      * ================== *
    DEPARTAMENTO MECANICA APLICADA                    **********************
  ==================================


              candu3                                                                          


      CORR     CAUDAL         TEMPERATURA        PRESION       VOL ESPECIFICO      ENTALPIA         ENTROPIA          TITULO
       NO     (KGS/SG)            (C)             (BARA)          (M**3/KG)        (KJ/KG)         (KJ/KG/C) 


       52        3.0397           53.6            0.1474           9.557156         2451.1           7.56420          0.9379
       53        0.5081          258.1           45.5100           0.043417         2793.2           6.00644          0.9975
       54        0.0000          212.4           20.0114           0.092751         2668.0           6.07020          0.9315
       55        0.0000          192.5           13.2494           0.134841         2605.0           6.09576          0.9080
       56       29.1943          192.5           13.2494           0.134841         2605.0           6.09576          0.9080
       57       56.4578          177.9            9.5531           0.181292         2557.6           6.11790          0.8927
       58        1.9578          177.9            9.5531           0.181292         2557.6           6.11790          0.8927
       59       88.8804          177.5            9.4575           0.001124          752.0           2.11477          0.0000
       60       27.1844          210.1           19.1194           0.001173          898.2           2.42570          0.0000
       61       27.1844          210.9           19.4104           0.095614         2668.0           6.08188          0.9321
       62        1.3194          210.9           19.4104           0.095614         2668.0           6.08188          0.9321
       63       49.2398          255.3           43.4830           0.001264         1111.9           2.84218          0.0000
       64       49.2398          256.2           44.1450           0.044796         2793.2           6.01779          0.9970
       65        2.4444          256.2           44.1450           0.044796         2793.2           6.01779          0.9970
       66      610.6430           29.1            0.0403           0.001004          122.0           0.42443          0.0000
       67        0.9703          258.1           45.5100           0.043417         2793.2           6.00644          0.9975
       68        0.3333          258.1           45.5100           0.043417         2793.2           6.00644          0.9975
       69       14.6011           53.6            0.1474           1.990453          688.0           2.16881          0.1953
       70       15.5714          192.3           45.5100           0.001142          819.2           2.25260          0.0000
       71       18.3993          100.0            1.0132           0.346099          884.8           2.55508          0.2064
       72        2.4946          145.7            4.2361           0.409777         2603.0           6.54749          0.9355
       73        2.4946          145.7            4.2361           0.409777         2603.0           6.54749          0.9355
       74       45.8645           66.9            0.2716           4.015994         1918.1           5.73485          0.6996
       75       14.4932           79.1            0.4567           0.767425          833.5           2.49080          0.2174
       76       60.3577           66.9            0.2716           3.377756         1657.7           4.96887          0.5884
       77       41.2174           91.6            0.7460           1.677993         2099.9           5.91572          0.7530
       78      610.6430           29.1            0.5403           0.001004          122.0           0.42426          0.0000
       79      610.6430           29.2           14.5961           0.001003          123.6           0.42478          0.0000
       80      610.6430           29.5           13.4661           0.001004          124.9           0.42944          0.0000
       81        1.4235          145.7            4.2361           0.409777         2603.0           6.54749          0.9355
       82        0.3333          100.0            1.0132           0.001044          419.1           1.30685          0.0000
       83        1.4235          100.0            1.0132           0.001044          419.1           1.30685          0.0000
       84      610.6430           30.8           12.3361           0.001004          130.0           0.44660          0.0000
       85        1.7568          100.0            1.0132           0.001044          419.1           1.30685          0.0000
       86        1.0711          145.7            4.2361           0.409777         2603.0           6.54749          0.9355
       87        2.8279          100.0            1.0132           0.613854         1246.2           3.52368          0.3665
     EMPRESARIOS AGRUPADOS, A.I.E.                                                                             PAGINA    17
                                                      **********************                           FECHA Thu Mar 10 2011
  GHESA INGENIERIA Y TECNOLOGIA, S.A                  * HBAL-06/ASME-1967  *
                                                      * ================== *
    DEPARTAMENTO MECANICA APLICADA                    **********************
  ==================================


              candu3                                                                          





                                        INFORMACION GENERAL DE ELEMENTOS DIVISORES NORMALES


    EQUIPO        FLUJO DE        FLUJO DE        FLUJO DE        FACTOR DE        FACTOR DE        RELACION         RELACION 
                  ENTRADA         SALIDA 1        SALIDA 2
      NO          (KG/SG)         (KG/SG)         (KG/SG)          FLUJO 1          FLUJO 2         PRI/PRINC        SEC/PRINC
    ======       ==========      ==========      ==========      ===========      ===========      ===========      ===========
        2        1043.6600       1042.6897      0.97028000        32.205685       0.29969158E-01   0.99907031       0.92968975E-03
        3        1042.6897       991.00544       51.684279        30.609307        1.5963787       0.95043177       0.49568225E-01
        4        991.00544       990.67211      0.33333000        30.599011       0.10295605E-01   0.99966364       0.33635537E-03
        5        990.67211       990.16406      0.50805600        30.583319       0.15692388E-01   0.99948716       0.51283971E-03
        8        990.16406       990.16405      0.10000000E-04    67.410545       0.68080179E-06   0.99999999       0.10099337E-07
        9        990.16405       961.66022       28.503823        65.470000        1.9405454       0.97121303       0.28786971E-01
       11        961.66022       961.66022      0.10000000E-05    97.014075       0.10088186E-06    1.0000000       0.10398683E-08
       12        961.66022       932.46592       29.194300        94.068900        2.9451754       0.96964177       0.30358228E-01
       14        932.46592       876.00812       56.457800        120.67729        7.7775240       0.93945323       0.60546770E-01
       15        876.00812       874.05035       1.9577700        120.40759       0.26969884       0.99776512       0.22348765E-02
       23        28.503823       27.184383       1.3194400        1.9079325       0.92604730E-01   0.95371007       0.46289931E-01
       24        51.684279       49.239839       2.4444400        1.5685322       0.77867492E-01   0.95270438       0.47295620E-01
       26        785.16990       744.81220       40.357700        236.82000        12.832108       0.94860004       0.51399958E-01
       28        744.81220       708.41990       36.392300        500.60000        25.716366       0.95113896       0.48861041E-01
       31        700.03458       667.20248       32.832100        1121.1300        55.169238       0.95309932       0.46900683E-01
       34        656.05149       652.70927       3.3422200        1760.9300        9.0169019       0.99490555       0.50944477E-02
       37        640.94576       606.84476       34.101000        2705.9800        152.05969       0.94679581       0.53204190E-01
       40        595.28338       592.24366       3.0397200        4769.1650        24.477976       0.99489366       0.51063411E-02
       57        2.4946000       1.4235000       1.0711000       0.44273927       0.33313525       0.57063257       0.42936743    
     EMPRESARIOS AGRUPADOS, A.I.E.                                                                             PAGINA    18
                                                      **********************                           FECHA Thu Mar 10 2011
  GHESA INGENIERIA Y TECNOLOGIA, S.A                  * HBAL-06/ASME-1967  *
                                                      * ================== *
    DEPARTAMENTO MECANICA APLICADA                    **********************
  ==================================


              candu3                                                                          





                                    INFORMACION GENERAL DE TURBINAS DE VAPOR


                                 ENTRADA                       SALIDA
                      ----------------------------  ----------------------------
   EQUIPO    FLUJO    PRESION  TEMPERAT  ENTALPIA   PRESION  TEMPERAT  ENTALPIA  RELACION  FACTOR DE  EFICIENCIA  POTENCIA
     NO     (KGS/SG)   (BARA)    (C)      (KJ/KG)    (BARA)    (C)      (KJ/KG)  PENT/PSAL  FLUJO       (0/0)       (KW)


      7     990.1641  42.0300    253.28   2793.20   20.0114    212.40   2667.96      2.100    33.1483    88.35     124007.1
     10     961.6602  20.0114    212.40   2667.96   13.2494    192.48   2605.01      1.510    65.4700    84.10      60541.1
     13     932.4659  13.2494    192.48   2605.01    9.5531    177.91   2557.61      1.387    94.0689    82.60      44196.4
     25     785.1699   9.0837    241.99   2928.72    4.4077    166.96   2786.57      2.061   130.9400    93.04     111614.0
     27     744.8122   4.4077    166.96   2786.57    1.8531    117.84   2643.28      2.379   236.8200    91.36     106719.6
     29     708.4199   1.8531    117.84   2643.28    0.7460     91.64   2512.64      2.484   500.6000    88.35      92546.6
     32     667.2025   0.7460     91.64   2538.14    0.4567     79.11   2473.23      1.633  1121.1300    86.60      43309.7
     35     652.7093   0.4567     79.11   2509.64    0.2716     66.86   2443.58      1.681  1760.9300    86.16      43116.3
     38     606.8448   0.2716     66.86   2483.29    0.1474     53.63   2408.69      1.843  2705.9800    85.95      45274.5
     41     592.2437   0.1474     53.63   2451.11    0.0403     29.12   2344.68      3.654  4769.1650    62.27      63034.1
                                                                                                                  ---------
                                                                                                                   734359.6





                     ELEMENTO N§    41:  FLUJO VOLUMETRICO =  18362.3     M3/S, ELEP =  2306.17     KJ/KG
     EMPRESARIOS AGRUPADOS, A.I.E.                                                                             PAGINA    19
                                                      **********************                           FECHA Thu Mar 10 2011
  GHESA INGENIERIA Y TECNOLOGIA, S.A                  * HBAL-06/ASME-1967  *
                                                      * ================== *
    DEPARTAMENTO MECANICA APLICADA                    **********************
  ==================================


              candu3                                                                          



                LINEAS DE EXTRACCION DE TURBINA.-DIAGRAMA H-S.
                ==============================================

  2940.    ...............................................................................................................
           .          .          .          .          .          . *        .          .          .          .          .
           .          .          .          .          .          .          .          .          .          .          .
           .          .          .          .          .          .          .          .          .          .          .
           .          .          .          .          .          .          .          .          .          .          .
  2880.    ...............................................................................................................
           .          .          .          .          .          .          .          .          .          .          .
           .          .          .          .          .          .          .          .          .          .          .
           .          .          .          .          .          .          .          .          .          .          .
           .          .          .          .          .          .          .          .          .          .          .
  2820.    ...............................................................................................................
           .          .          .          .          .          .          .          .          .          .          .
           .          .        * .     *    .          .          .          .          .          .          .          .
           .          . *    *   .          .  *       .          .  +       .          .          .          .          .
           .          .          .          .          .          .          .          .          .          .          .
  2760.    .....*......................................*..................................................................
           .          .          .          .          .      *   .          .          .          .          .          .
           .          .          .          .          .          .          .          .          .          .          .
           .          .          .          .          .          .   *      .          .          .          .          .
           .          .          .          .          .          .          .          .          .          .          .
  2700.    ...................................................................*...........................................
           .          .          .          .          .          .          .          .          .          .          .
           .          .          .          .          .          .          .       *  .          .          .          .
           .          .       +  .          .          .          .          .          .          .          .          .
           .          .          .          .          .          .          .          .    *     .          .          .
  2640.    ............................................................+..................................................
           .          .          .          .          .          .          .          .          . *        .          .
           .          .          .          .          .          .          .          .          .         *.          .
           .          .        + .          .          .          .          .          .          .          .          .
           .          .          .          .          .          .          .          .          .          .          .
  2580.    ...............................................................................................................
           .          .          .          .          .          .          .          .          .          .          .
           .          .         *.          .          .          .          .          .          .          .          .
           .          .          .          .          .          .          .          .          .          .          .
           .          .          .          .          .          .         *.          .          .          .          .
  2520.    ...............................................................................................................
           .          .          .          .          .          .      *   .    *     .          .          .          .
           .          .          .          .          .          .          .          .          .          .          .
           .          .          .          .          .          .          .          .          .          .          .
           .          .          .          .          .          .          *          *          .          .          .
  2460.    ...............................................................................................................
           .          .          .          .          .          .          .          .       *  .          .          .
           .          .          .          .          .          .          .     *    .          .          .          .
           .          .          .          .          .          .          .          .          .          .          .
           .          .          .          .          .          .          .          .          .          .          .
  2400.    ...............................................................................*...............................
           .          .          .          .          .          .          .          .          .          .          .
           .          .          .          .          .          .          .          .          .          .          .
           .          .          .          .          .          .          .          .          .          .          .
           .          .          .          .          .          .          .          .          .          .          .
  2340.    ..............................................................................................*................

        5.62500    5.87500    6.12500    6.37500    6.62500    6.87500    7.12500    7.37500    7.62500    7.87500    8.12500
     EMPRESARIOS AGRUPADOS, A.I.E.                                                                             PAGINA    20
                                                      **********************                           FECHA Thu Mar 10 2011
  GHESA INGENIERIA Y TECNOLOGIA, S.A                  * HBAL-06/ASME-1967  *
                                                      * ================== *
    DEPARTAMENTO MECANICA APLICADA                    **********************
  ==================================


              candu3                                                                          





                         INFORMACION GENERAL DE CALENTADORES DE AGUA DE ALIMENTACION

                                               AGUA DE ALIMENTACION
                                     ENTRADA                      SALIDA                             DRENAJE
                         ----------------------------  ---------------------------  -------------------------------------------
   EQUIPO    FLUJO       PRESION  TEMPERAT  ENTALPIA   PRESION  TEMPERAT  ENTALPIA     FLUJO     PRESION  TEMPERAT  ENTALPIA
     NO     (KGS/SG)      (BARA)    (C)     (KJ/KG)     (BARA)    (C)     (KJ/KG)     (KGS/SG)    (BARA)    (C)     (KJ/KG) 


     53     610.6430      14.5961   29.18     123.57    13.4661   29.52     124.87      0.3333     1.0132  100.00     419.06
     54     610.6430      13.4661   29.52     124.87    12.3361   30.76     129.96      1.4235     1.0132  100.00     419.06



                             VAPOR                                        CASCADA
           ------------------------------------------    ----------------------------------------
   EQUIPO    FLUJO       PRESION  TEMPERAT  ENTALPIA       FLUJO     PRESION  TEMPERAT  ENTALPIA       TTD      DCA
     NO     (KGS/SG)      (BARA)    (C)     (KJ/KG)       (KGS/SG)    (BARA)    (C)     (KJ/KG)        (C)      (C)


     53       0.3333      45.5100  258.10    2793.20        0.0000     0.0000    0.00       0.00      70.482   70.817
     54       1.4235       4.2361  145.70    2603.00        0.0000     0.0000    0.00       0.00      69.238   70.482
     EMPRESARIOS AGRUPADOS, A.I.E.                                                                             PAGINA    21
                                                      **********************                           FECHA Thu Mar 10 2011
  GHESA INGENIERIA Y TECNOLOGIA, S.A                  * HBAL-06/ASME-1967  *
                                                      * ================== *
    DEPARTAMENTO MECANICA APLICADA                    **********************
  ==================================


              candu3                                                                          





                                         INFORMACION GENERAL DE CONDENSADOR PRINCIPAL


                              AGUA DE CIRCULACION
             ------------------------------------------------
    EQUIPO      CAUDAL    VELOCIDAD      TEMP.       TEMP.      PRESION      CALOR    
      NO      (M**3/SG)    (M/SG)      ENT. (C)    SAL. (C)      (MMHG)     ( KW  ) 

      42   *********************** *********** ***********     30.2500    1.33040E+06
     EMPRESARIOS AGRUPADOS, A.I.E.                                                                             PAGINA    22
                                                      **********************                           FECHA Thu Mar 10 2011
  GHESA INGENIERIA Y TECNOLOGIA, S.A                  * HBAL-06/ASME-1967  *
                                                      * ================== *
    DEPARTAMENTO MECANICA APLICADA                    **********************
  ==================================


              candu3                                                                          





                                         INFORMACION GENERAL DE BOMBAS


    EQUIPO       CAUDAL TOTAL       PRESION    PRESION   T.D.H.      REND.        POTENCIA         NO. BOMBAS
                   BOMBEADO         ENTRADA    SALIDA                             EN EL EJE        EN PARALELO
      NO      (KGS/SG)   (M**3/HR)  (BARA)     (BARA)      (M)       (0/0)     (KW)      (CV)

      52      610.6430  2207.1475    0.5403    14.5961    143.90     90.00     957.50   1301.84         3
     EMPRESARIOS AGRUPADOS, A.I.E.                                                                             PAGINA    23
                                                      **********************                           FECHA Thu Mar 10 2011
  GHESA INGENIERIA Y TECNOLOGIA, S.A                  * HBAL-06/ASME-1967  *
                                                      * ================== *
    DEPARTAMENTO MECANICA APLICADA                    **********************
  ==================================


              candu3                                                                          





                                        INFORMACION GENERAL DE SEPARADORES DE HUMEDAD


                            ENTRADA                         SALIDA VAPOR SECO              SALIDA DRENAJE
          -------------------------------------------- ---------------------------- ---------------------------
  EQUIPO    FLUJO    PRESION  TEMPER  ENTALPIA  TITULO    FLUJO    ENTALPIA  TITULO   FLUJO    ENTALPIA  TITULO  EFIC.  ARR.
    NO      (KG/S)   (BAR A.)  (C)    (KJ/KG)             (KG/S)   (KJ/KG)            (KG/S)   (KJ/KG)           (0/0) (0/0)

    17     874.0504     9.46  177.48   2557.61   0.893   785.1699   2762.01   0.994   88.8804    751.97   0.000  95.00  0.00
    30     708.4199     0.75   91.64   2512.64   0.934   700.0346   2538.14   0.945    8.3853    383.85   0.000  17.97  0.00
    33     667.2025     0.46   79.11   2473.23   0.927   656.0515   2509.64   0.943   11.1510    331.17   0.000  22.85  0.00
    36     652.7093     0.27   66.86   2443.58   0.924   640.9458   2483.29   0.941   11.7635    279.81   0.000  23.71  0.00
    39     606.8448     0.15   53.63   2408.69   0.920   595.2834   2451.11   0.938   11.5614    224.45   0.000  23.82  0.00
     EMPRESARIOS AGRUPADOS, A.I.E.                                                                             PAGINA    24
                                                      **********************                           FECHA Thu Mar 10 2011
  GHESA INGENIERIA Y TECNOLOGIA, S.A                  * HBAL-06/ASME-1967  *
                                                      * ================== *
    DEPARTAMENTO MECANICA APLICADA                    **********************
  ==================================


              candu3                                                                          





                                                INFORMACION GENERAL DE RECALENTADORES


                                                         VAPOR A RECALENTAR


                                ENTRADA                        SALIDA
                      ---------------------------   ---------------------------
   EQUIPO    FLUJO    PRESION  TEMPERAT  ENTALPIA   PRESION  TEMPERAT  ENTALPIA   CALOR ABSORBIDO   EFICIENCIA   LMTD   TTD
     NO     (KG/SG)    (BARA)    (C)      (KJ/KG)    (BARA)    (C)      (KJ/KG)         (KW)           (0/0)       C     C

     18    785.1699     9.458   177.48    2762.01     9.363   196.97    2823.28       48108.9         100.00    21.95  13.90
     19    785.1699     9.363   196.97    2823.28     9.284   242.34    2928.72       82789.2         100.00    30.99  13.90



                                                         VAPOR QUE RECALIENTA


                                ENTRADA                        SALIDA
                      ---------------------------   ---------------------------
   EQUIPO    FLUJO    PRESION  TEMPERAT  ENTALPIA   PRESION  TEMPERAT  ENTALPIA   CALOR CEDIDO  FACTORES DE TRANSFERENCIA
     NO     (KG/SG)    (BARA)    (C)      (KJ/KG)    (BARA)    (C)      (KJ/KG)       (KW)           UA          U

     18     27.1844    19.410   210.87    2667.96    19.119   210.11     898.24    48108.9       2192.        2192.    
     19     49.2398    44.145   256.24    2793.20    43.483   255.33    1111.85    82789.2       2672.        2672.    
     EMPRESARIOS AGRUPADOS, A.I.E.                                                                             PAGINA    25
                                                      **********************                           FECHA Thu Mar 10 2011
  GHESA INGENIERIA Y TECNOLOGIA, S.A                  * HBAL-06/ASME-1967  *
                                                      * ================== *
    DEPARTAMENTO MECANICA APLICADA                    **********************
  ==================================


              candu3                                                                          


